### ISSUE TITLE
Enhancement: Clear Browser Cache when Idle

### ISSUE THREAD

**Issue by spodermenpls** [mrdokenny/Cookie-AutoDelete#101]
### Describe the Bug/Feature

As a former user of Self-Destructing Cookies, I am very glad to see "Cookie AutoDelete" already in place as its successor, which does its job (in my case) even better than SDC. 

I noticed though that there seems to be no option implemented to delete the browser's cache, after a set idle time (like SDC had). I looked through the existing issues and documentations on here, but it doesn't seem to have come up yet. My question therefore is, is a "Clear Browser Cache when Idle"-function implementable, or is it prohibited by webExtension limitations?

**Comment by mrdokenny** [comment]
Yes it should be possible but I think that feature "should" probably be it's standalone extension as it can't make use of the whitelist/greylist.

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browsingData/removeCache

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/idle

**Comment by spodermenpls** [comment]
Is it really necessary to "exile" this function into a separate extension? It has been part of SDC for a long time, is closely linked to the purpose of this addon, and could be deactivated by those who don't want their cache being cleared automatically.

**Comment by mrdokenny** [comment]
I would rather have this feature and similar ones (which can be generalized as delete browsing data on idle) be in a separate extension that someone else can do.

**Comment by ghost** [comment]
@mrdokenny I think this is a good idea to have this just like self-destructing cookies had it. Why cant you integrate this? no need to have whitelist/greylist a part of clearing browser cache on idle.
Its a needed feature together with removing/clearing cookies.

**Comment by ke-d** [comment]
@2SI3NX The browsingData API has all these [data](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browsingData/DataTypeSet) that you could remove. The reason why those functions should be a separate extension is
- "Clearing Cache on Idle" doesn't rely on any of CADs functions
   - Localstorage is an exception cause there's a hostname parameter
- If I implemented for just cache, I would have to add settings for all of them, which can bloat the settings page
- I have to request the idle permission which will show up in an update
- Modularization of code so it is easier to manage

Anyways if no one creates it, then I'll probably make one at some point. :)

**Comment by spodermenpls** [comment]
@2SI3NX I discovered that uMatrix has a built-in "Cache clearing after set time" feature, maybe that's an alternative for you as well.

**Comment by ghost** [comment]
@spodermenpls thanks for the info, although the point is to have this in one addon just like SDC had it. and not to bloat firefox with an additional addon only to clear cache automatically.  SDC set the bar for users really high, they learned by having a sort of 'two in one' solution and thats why it was the best.

I believe Cookie-AutoDelete is the next best thing after SDC - however, missing features that the user was previously used to will make Cookie-AutoDelete look less impressive than SDC. i cant stress enough how important this is.

I have to manually clear cache because it:
1. grows too big (even though i can set a limit which will then cause corruption as stated in 2.)
2. and sometimes pages dont load properly because something went wrong in the cache.

@mrdokenny i have high hopes for Cookie-Autodelete and il report as many bugs as i can, i hope you can implement this feature. thanks very much.
