### ISSUE TITLE
[BUG] Popup window button placement with font-size <13px

### ISSUE THREAD

**Issue by relikd** [mrdokenny/Cookie-AutoDelete#1034]
**Describe the bug**
The button placement in the popup is broken for font sizes 10, 11, and 12 px. Above 13px is fine.
See these two images below for pixel sizes of 12 and 13 pixel respectively.

**To Reproduce**
not applicable

**Expected Behavior**
I expect the buttons to be placed beside each other.

**Screenshots**

![12px](https://user-images.githubusercontent.com/1321720/106143309-e5881980-6172-11eb-9b9e-e9648aab49c9.png)
![13px](https://user-images.githubusercontent.com/1321720/106143312-e6b94680-6172-11eb-8798-6b392c49bee8.png)

**Your System Info**

- OS: macOS 10.15
- Browser Info: Firefox 85
- CookieAutoDelete Version: 3.6.0

**Comment by kennethtran93** [comment]
Ah. Thets may be due to the font size that somehow triggered total width being small enough to trigger the change.

The buttons on new rows were designed for those that have decided to move the icon to the overflow menu, which has a max width smaller than if on the toolbar.

I'll see what I can do about the font size bug.

**Comment by kennethtran93** [comment]
Are you still having this issue?  I cannot reproduce the sizing error at this time.  All sizes from 10-15 are still on one line, Firefox 86/87

**Comment by relikd** [comment]
yes, I still experience this in 86. It is getting weirder though. Font sizes 10-12px on this very tab will still be shown below each other. A new about:blank window will display the buttons properly under 12px size but not on 10-11px. The extensions config page behaves similar to this github tab; all sizes 10-12px are below each other.

**Comment by kennethtran93** [comment]
![image](https://user-images.githubusercontent.com/6724477/110259400-5386e400-7f5c-11eb-9d0c-344d9318095e.png)

Hmmm...I cannot determine what exactly is causing this issue. I don't know if it is the OS or extensions causing the behavior you are seeing.  I've only set the min-width if I detected a chrome browser as they don't set the widths properly.  Otherwise Firefox usually does a decent job of setting the widths.

**Comment by relikd** [comment]
ah, the min-width is the culprit! Try removing all logs and you will get the text below. The very last sentence is what defines the min-width and which is smaller than the four buttons side by side. And since the buttons can be dynamically rearranged, they are indeed. I think this can be fixed by placing the four buttons inside a div and/or surround the buttons with non-breakable space.

<img src="https://user-images.githubusercontent.com/1321720/110298760-3f42f580-7ff5-11eb-8441-82af3a3de3c4.png" width="600" alt="screen">

**Comment by kennethtran93** [comment]
The min-width is only set if it is a Google Chrome browser.

Thanks for the update on how to replicate the issue.

At this time I'm using bootstrap classes.  Previously, I had let the flex wrap itself, but due to certain situations where the activated dropdown would become 'flashy' (an issue was raised for this), primarily when the popup is moved to the overflow menu, I subsequently decided to utilize bootstrap to make one button the full width if the container width is under the smallest available breakpoint in bootstrap (currently 576px).  There is no way to detect whether or not the popup is in the overflow menu at this time.

With the removal of a popup within a popup, I may be able to revert the forced line break.  I'll need to take a look later.
