### ISSUE TITLE
[BUG]  CAD Requests Container Tabs on Firefox

### ISSUE THREAD

**Issue by akasaka99** [mrdokenny/Cookie-AutoDelete#1111]
Hi-
I am getting a message in Firefox's Preferences Tab section "An extension, Cookie AutoDelete, requires Container Tabs." whereas FF Multi-Container is ALREADY active and always has been.
So why do I get this message, is it another extension that I need to add ?
Thanks

**Comment by kennethtran93** [comment]
> I am getting a message in Firefox's Preferences Tab section "An extension, Cookie AutoDelete, requires Container Tabs." whereas FF Multi-Container is ALREADY active and always has been.
> So why do I get this message, is it another extension that I need to add ?

You are getting this message because it is telling you that the container option is enabled and that you **CANNOT disable containers** through the options because at least one web-extension requires it.  
Nothing to do on your end.  

As a side note, Firefox's containers could be used without the Multi-Container web-extension as well.
