### ISSUE TITLE
[FEATURE REQUEST] Manage Cross Site Behaviour Of Whitelisted Cookies

### ISSUE THREAD

**Issue by fweth** [mrdokenny/Cookie-AutoDelete#1136]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Is your feature request related to a problem? Please describe.

Sometimes I want to store some cookies, but only expose them to certain websites.  For example, if I use my Google identity for Dropbox, I'd like to whitelist cookies from *.google.com but only expose them to *.google.com and *dropbox.com.  Would that be hard to implement?

### Describe the solution that you'd like

Rectrict exposure for whitelisted cookies to given patterns.

### Describe alternatives you've considered

Using Firefox's own blocker for third-party cookies, which is not that much customizable.

**Comment by kennethtran93** [comment]
I think this falls outside the scope of this web extension.

**Comment by kennethtran93** [comment]
Plus with Firefox's new total cookie protection (cross site cookies - which currently breaks most cookie webextensions when it comes to removing them) most third party sites would be kept isolated to the first party domain.

**Comment by fweth** [comment]
OK, I don't know much about cookies, but isn't it kind of pointless to whitelist e.g. Google because I have a Google account and then bring those Google cookies to every other website I visit, where they can be used for tracking if the website has Google analytics or whatever?  Or is this the wrong picture?

**Comment by kennethtran93** [comment]
You can attempt to just whitelist the cookies that are needed for the login, at the very least from mail.google.com and accounts.google.com for starters.

While I cannot guarantee this, cookies for authentication should not be treated the same as cookies for analytics, otherwise it may raise a security concern if so.  (i.e. Google Analytics' cookie is not the same as the one you used to login to google and vice versa).  Each cookie from the site should have its own purpose.

If you are using Firefox and are concerned with cross site cookies, I have some options to provide you at this time:
- Use their new Total Cookie Protection (strict privacy / custom w/ cross site cookie option).  This should cover what you are looking for, barring a couple of special exceptions that Firefox may have added in order for some selective sites to function properly.  This would break CAD for the time being as the WebExtension API has yet to fully support the new protection.
- Use Firefox Multi-Account Container webextension and/or the containers available in Firefox.  The containers feature would have already been enabled if CAD is installed and enabled.  By using containers you can keep cookies 'containerized'.  By adding in 
Firefox Multi-Account Containers, you can force certain sites to open in a specific container, thus limiting tracking a bit.  In my case, I have mail.google.com in a container called Personal.  I also have GitHub in a 'develop' container.  Github won't know as much about my gmail cookies, nor will Gmail know as much about my Github cookies as they are kept in different containers.
- Try a temporary container extension.  These are containers that are only kept 'temporarily', so once they are removed/deleted, the cookies in those containers should be gone as well.

We only remove any third-party cookies if they were created without you knowing for the most part, usually trackers and whatnot.  Blocking cookies is not what our extension will do at this time.

**Comment by kennethtran93** [comment]
While I understand that scripts can be blocked using NoScript webextension (usually by looking at its network requests) during page load, the same concept cannot apply to cookies.  However, if we were to look at network requests (which I do plan on doing), this would only allow us to see domains and clean up additional site data of third-party domains during regular cleanup triggers.

As cookies are stored internally, and are accessed by the sites via `document.cookie`.  The only way for a site not to see those cookies would be to rename the site value stored in each cookie.  Doing this is not as easy, as it may break some other sites that actually requires it (and would probably force you to login again).  If we were to rename/recreate any cookies, then your currently opened/existing tabs may not work properly either (and may think you are not logged in and force you to login again).

**Comment by kennethtran93** [comment]
Closing as won't fix/implement, for reasons stated above, and when alternate solutions are more feasible.  Your best alternative is either Firefox's Total Cookie Protection (cross-site cookies), temporary container, or firefox containers w/ Firefox Multi-Account Containers.

**Comment by fweth** [comment]
Thank you for the detailed answers!
