### ISSUE TITLE
Suggestion Merge Add-ons

### ISSUE THREAD

**Issue by zero77** [mrdokenny/Cookie-AutoDelete#118]
For easier maintenance and support, why don’t you merge Cookie-AutoDelete and History-AutoDelete in to one add-on and let the user decide what they want deleted automatically.
Thanks

**Comment by mrdokenny** [comment]
As of History AutoDelete 2.X.X, it doesn't make sense anymore since H-AD can auto delete URLs by directory like for example "youtube.com/results*", which will delete search results from youtube but not the actual videos itself.

So basically H-AD now a different set of features than before that doesn't make sense to merge.
