### ISSUE TITLE
Whitelist ignored? / Signed out of Wikipedia

### ISSUE THREAD

**Issue by rugk** [mrdokenny/Cookie-AutoDelete#119]
### Describe the Bug/Feature

When logging in to Wikipedia, I am regularly logged out despite the domain being on the whitelist.

### Steps for anyone to reproduce the bug

1. Go to de.wikipedia.org and change the setting to "never cleanup (whitelist)".
2. Login to de.wikipedia.org.(check the box to remember the user)
3. Close the tab and do something else.
4. Go back to wikipedia

### Your settings 

- OS/version: Linux
- Browser/version: Firefox 55
- Cookie AutoDelete version: 1.4.0
- third-party cookies in Firefox settings disabled (`network.cookie.cookieBehavior` = 1)
- only other changed `network.cookie` value is "network.cookie.prefsMigrated" (true)

**Comment by mrdokenny** [comment]
Try adding `wikipedia.org` manually instead.

**Comment by rugk** [comment]
Okay, I did so. But regardless of the result, this is a bug and it should work without such a manual intervention…

**Comment by mrdokenny** [comment]
It might because wikipedia.org is setting subdomain cookies such as xyz.wikipedia.org which wouldn't be protected if you just had `de.wikipedia.org`

**Comment by ingelres** [comment]
Instead of simply adding the domain of the current website (e.g., de.wikipedia.org), is it possible for the extension to look at the domains covered by the cookies set by the website (e.g., wikipedia.org if a cookie was set for this particular domain) and offer the user to choose which domain to whitelist ?

Another simpler alternative would be to always propose to whitelist either the current subdomain (e.g., de.wikipedia.org) or the whole domain (e.g., wikipedia.org).

**Comment by mrdokenny** [comment]
![screenshot 2017-08-30 07 49 50](https://user-images.githubusercontent.com/17077613/29878617-e22ed546-8d57-11e7-95ea-df8bdddddfcb.png)

Here's a sneak preview of the popup in a future version.

**Comment by rugk** [comment]
Oh, god, could you plese make it *a bit* easier to handle? I mean from a user experience POV. That is just so many buttons and buttons, which are only some text and stuff and options and…

Don't make that thing too complex. I just wanna set exceptions for cookies.

The functionality if good, but maybe move it into an "expert mode" or "advanced mode" or whatever… Or make the thing easy to handle.

One question I immediately have is why there is a "matched expression" **and** a "regular expression"? Why do you expose regular expressions to the ordinary user anyway. That is a real expert feature only some experts may use, so move it into the settings.

I actually requested to already simplify the popup you currently have, so features are nice, but UI/UX is important too… :smiley:

**Comment by mrdokenny** [comment]
![screenshot 2017-08-30 16 18 33](https://user-images.githubusercontent.com/17077613/29899213-ec3e51aa-8d9e-11e7-9393-7d7eaed47d6c.png)

>Don't make that thing too complex. I just wanna set exceptions for cookies.

Basically, this request #113 which will only apply to subdomains like addons.mozilla.org, and not say github.com.

What I'm adding is a quick way to add either just the domain itself or the domain and subdomains.

With this new system, you can do neat things like: 

`google.com` -> keep cookies from only google.com
`*google.com`-> keep cookies from google.com and subdomains
`*.google.com`-> keep only google.com subdomain cookies but not cookies from google.com

>One question I immediately have is why there is a "matched expression" and a "regular expression"? Why do you expose regular expressions to the ordinary user anyway. That is a real expert feature only some experts may use, so move it into the settings.

The regular expression column will probably be a placeholder for now (since I borrowed the code from History AutoDelete). The column is to basically show you what the expression is equivalent to in RegExp.

**Comment by mrdokenny** [comment]
Closing as there's nothing else to do here.
