### ISSUE TITLE
[SUPPORT]  No matter what I do I can't get the AT&T website to keep the cookie it needs to sign back in without a cell phone code

### ISSUE THREAD

**Issue by ng4ever** [mrdokenny/Cookie-AutoDelete#1258]
### Acknowledgements

- [x] I acknowledge that I have read the above items

### Please describe what you need support with

I tried all domains to whitelist. Maybe I am doing something wrong ? 

Any help appreciated. If possible.

**Comment by kennethtran93** [comment]
Unfortunately I don't use AT&T so I cannot offer much assistance myself.

- What browser and version are you using?
- What domain expressions have you put into the whitelist related to this site and what settings are each of those domain expressions?
- what site data have you enabled for cleanup?

**Comment by ng4ever** [comment]
Sorry for the late reply. 

Firefox 94.0.1 
signin.att.com and *.signin.att.com
None

**Comment by kennethtran93** [comment]
Are you using containers of any kind?

Can you provide a (sanitized) screenshot of the prompt that asks you for the code?

**Comment by ng4ever** [comment]
No containers. 

![pic](https://user-images.githubusercontent.com/17295139/142736995-4132a964-5218-4c4a-9f62-9698eda3b8b4.jpg)

**Comment by ng4ever** [comment]
Yes I check the box. Just wasn't checked in that screenshot sorry.

**Comment by kennethtran93** [comment]
> No containers.
> 
> ![pic](https://user-images.githubusercontent.com/17295139/142736995-4132a964-5218-4c4a-9f62-9698eda3b8b4.jpg)

Looks like in the URL, it seemingly redirects to a another att site (https://oidc.idp.clogin.att.com) either after login or to process the request.  Perhaps try adding that as well?  If you want, you can also try using *.att.com as the whitelist.

What other web extensions / addons do you have installed/running?

Do you have Firefox clean up cookies and site data on close?  
![image](https://user-images.githubusercontent.com/6724477/142747047-f0ea56bd-8858-4876-bbd4-8e1d29a1ef41.png)

Are you also using Firefox's cookie/site data manager (Manage Exceptions button)
![image](https://user-images.githubusercontent.com/6724477/142747091-15c4aba4-f1b5-4d1d-9832-86416a21eac7.png)



Also are you using Private Browsing mode by chance?  Private Browsing mode can either be permanently enabled or as needed, so that's why I also ask this question (shown in screenshot below)

Do you periodically clean up history in firefox?  It seems some cookies, cache, and other stuff can also be cleared through history as shown below:
![image](https://user-images.githubusercontent.com/6724477/142747005-5fc8983c-3b6b-4e7a-b63e-853e1b76f80d.png)

**Comment by ng4ever** [comment]
Ok thank you so much you figured it out! I added https://oidc.idp.clogin.att.com/ but already had *.att.com added. It works now without keep asking for a code if I select remember me on this device! 

Thanks again! 

I don't have any other cookies extensions installed if that is what your wondering. 

Also no I do not have Firefox clean up cookies and site data on close.

Really do not clean up history in Firefox either. Though I made sure to never do that but never did even when the problem existed.

**Comment by kennethtran93** [comment]
> Ok thank you so much you figured it out! I added https://oidc.idp.clogin.att.com/ but already had *.att.com added. It works now without keep asking for a code if I select remember me on this device!

The *.att.com should cover everything within att.com, so signin.att.com and oidc.idp.clogin.att.com is redundant, but it doesn't hurt to keep it in there.

Glad it worked out for you.

Closing as resolved.
