### ISSUE TITLE
[SUPPORT]  allmylinks.com cookie deleted on every tab open/close

### ISSUE THREAD

**Issue by gashtal** [mrdokenny/Cookie-AutoDelete#1261]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Please describe what you need support with

Hi,

Recently I noticed that in the Cookie AutoDelete log, there are very frequent messages about deleting one cookie from "allmylinks.com", despite the fact that I am not visiting this website. After some digging, I realized that a new cookie deletion message is generated for this domain by Cookie AutoDelete every time I open or close a new tab (and probably other events). This seemed quite suspicious to me, so I disabled all my add-ons except Cookie AutoDelete to see if any of my add-ons are injecting the cookie. To all my surprise, I noticed that the same thing still happens, so I am not sure what to make of it at this point. Does anyone have any idea about this behavior and what could be causing it? I have attached an example log below.

![allmylinks](https://user-images.githubusercontent.com/27990818/140660468-c00583ad-ad00-429a-a685-c6342011165f.png)

**Comment by kennethtran93** [comment]
Your issue may be the same as #807 - that is using the 'strict' mode in Firefox (or maybe standard mode is also doing it with the latest release), but use custom and change the cookie setting to 'cross-site tracking cookies' for the time being while I work on getting the dynamic partitions working.  Note that this will only affect future-created cookies.  You'll need to manually remove that cookie yourself.

**Comment by kennethtran93** [comment]
Closing as stale, presumably same as using 'strict' mode or cross-site cookies option.  With Firefox 94+, those cookies aren't returned to CAD for cleanup, so you shouldn't be getting any more of those messages at this time.

If this issue came from Google Chrome, please let me know.

**Comment by modelfe** [comment]
I'm not sure if this is related, but allmylinks.com seems to generate some strange cookies that aren't deleted by CAD or other cookie management extensions, including in Firefox 94.0.

If I select "Manage Data" in Firefox's Privacy & Security settings, I consistently find between 1-5 cookies from allmylinks.com after visiting the website, even on browser restart.

Other than not being deleted by CAD, I say these cookies are "strange" for two reasons; first, they persist even if I have only opened an allmylinks.com link in a temporary container which has since been deleted, and; second, they only seem to be visible in Firefox's "Manage Data" dialog. The Quick Cookie Manager extension, for example, shows no record of them.

I am **not** using "strict" mode. My privacy settings are as below. CAD is set to automatically clean, including all the data cleanup options. Using Firefox 94.0 on Linux.

![screenshot](https://user-images.githubusercontent.com/50790128/144937476-d6dd02bb-14b6-4cea-b284-884cd324de68.png)

**Comment by gashtal** [comment]
For future reference, it seems Cookie AutoDelete was actually failing to delete cookies related to "allmylinks.com" even though it claimed it is deleting them again and again. The constant messages about cookies having been deleted from "allmylinks.com" finally stopped when I manually deleted cookies related to that website using "Manage Data" on Firefox as mentioned by @modelfe above.
