### ISSUE TITLE
[FEATURE REQUEST]  Ability to Delete Entire Cache in Firefox when you close tab also make a timer

### ISSUE THREAD

**Issue by mikec7000** [mrdokenny/Cookie-AutoDelete#1390]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Is your feature request related to a problem? Please describe.

It would be so nice If you added an ability to add on option to automatically clean the cache when you close a tab, it's nice to clean the cookies but the cache has so much data stored about you that it would be a great addition to add and you could have an option to clean cookies and cache. For example I can make a setting where if I close a tab it cleans both cookies and cache.

Also I would love the ability to make a function where you can set a custom timer to clean the cookies and cache of the entire browser, you can set it in seconds or minutes and when the time comes in options you can make it so it can clean the entire browser of it's cache, local storage and cookies. This would be powerful.

### Describe the solution that you'd like

Ability to delete cache when you close a tab, not just cookies.  Also make a timer function that you can customized to delete cache and cookies on a user set preference in seconds, minutes.

**Comment by kennethtran93** [comment]
The ability to delete cache _was_ available up to Firefox 99.  A version update is being made to address the bug about missing site data cleanup from version 100+.

To enable cache cleanup alongside the cookie cleanup (when it is fixed in the next version), you'll need to go into settings and enable the cache cleanup.  Note that this _will_ make an attempt to clean the entire cache once checked/enabled.
![image](https://user-images.githubusercontent.com/6724477/169217485-8855b59a-75b5-4881-8e1b-57c894ec6b0b.png)

From then on, whenever you visit a site, we will then set a cookie (regardless if the site itself sets a cookie) that will then allow us to fetch and delete our cookie (thus providing us the domain to use to pass into the other site data cleanups).

As for a timer, this is not in the works at this time, but is probably already been requested earlier on.  The only triggers we have so far for automatic is on tab close, domain change, and browser restart, as well as the 'delay' once triggered.

**Comment by mikec7000** [comment]
Thank you,

This is exactly what I am looking for to clean the entire cache of the
browser, Sessions, Active Logins in Firefox. Site developers are getting
very sneaky now and deleting cookies just does not work anymore on some
sites. They now make data stuck in cache, active sessions that keep on
tracking you no matter how many times you clean your cookies. I function in
cookie auto delete for a deep clean cache setting would be great. I am
trying to mimic a way so that the addon clears the same way like if you
press ctrl+shift+del and everything gets checked and cleaned, would it be
able to do a deep clean like if you did a manual clean from the menu?

Do you have an estimate of the release date for the new version, this is
something I would really love asap.

Thanks for your help

**Comment by kennethtran93** [comment]
Version 3.7.0 has been released on Firefox.

**Comment by kennethtran93** [comment]
> I am trying to mimic a way so that the addon clears the same way like if you press ctrl+shift+del and everything gets checked and cleaned, would it be able to do a deep clean like if you did a manual clean from the menu? 

Not all site data types are implemented on this web extension at this time.  In addition, the functions that Firefox uses to clean up certain data may not be exposed through the web extension API.

> Do you have an estimate of the release date for the new version, this is something I would really love asap. Thanks for your help

Version 3.7.0 has been released on Firefox.
