### ISSUE TITLE
[Bug]  "clean all for this domain" fails to clean session storage, but "clean localstorage for this domain" does

### ISSUE THREAD

**Issue by zesty** [mrdokenny/Cookie-AutoDelete#1402]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Describe the bug

It's all in the title. I have all items checked under "Other Browsing Data Cleanup Options". Tested on rottentomatoes.com

### To Reproduce

1. browse to rottentomatoes.com
2. F12 and view Storage > Session Storage
3. Note about 5 k/v for com.adobe.reactor.*
4. Activate "clean all for this domain"

Actual: Session Storage intact

5. Activate clear localStorage for this domain

Actual: Session Storage cleared

### Expected Behavior

Session Storage included in "All"

### System Info - Operating System (OS)

linux Ubuntu 22.04 LTS

### System Info - Browser Info

Firefox 101.0

### System Info - CookieAutoDelete Version

3.7.0

**Comment by kennethtran93** [comment]
The function used when clicking the clean localstorage is different than the one used for All and the other browsing data types.  However, I may try to adjust it so that the localstorage script is ran instead of the browsingData one.

Unfortunately, there's no browsingData API yet to clean session storage (as far as firefox is concerned) at this time, so any session storage from this side requires the site to already be loaded in a tab as we execute a script within the active tab.

**Comment by zesty** [comment]
I don't follow the rationale for either/or. "Clean All" should mean to run all the scripts to clean all the things. Scorched earth.

**Comment by kennethtran93** [comment]
> I don't follow the rationale for either/or. "Clean All" should mean to run all the scripts to clean all the things. Scorched earth.

Agreed.  It just didn't click in my head when I designed that at that point in time to include this separate localstorage cleanup function (that only works in the popup) in the 'all' when the localstorage site data was executed as well.

And an interesting note is that on the Chrome side, it actually cleans localstorage and sessionstorage when the clean all button is pressed (i.e. using browsingdata api call instead of the custom localstorage function).

I'll force the function to run regardless when the 'all' is clicked - better to clean up multiple times than not.

**Comment by kennethtran93** [comment]
@zesty can you try the build from the linked PR to see if it does fix your issue?  I tested it myself and it does execute the localstorage function on the 'All' manual cleanup.

**Comment by zesty** [comment]
@kennethtran93 I'm not seeing where to download, but maybe the links expired?

**Comment by kennethtran93** [comment]
> @kennethtran93 I'm not seeing where to download, but maybe the links expired?

From the linked PR, enter the command found in one of the last posts by `github-actions` (tl;dr: `/get-build`).  You may need to refresh if you don't see any new posts after your posts has 3 emotions added by github-actions.

**Comment by kennethtran93** [comment]
I've pushed the next version that includes this fix, so when you see CAD updating to 3.8.0, you can give it a try then.

**Comment by zesty** [comment]
3.8.0 functions as expected for everything except Cache Storage, which is cleaned neither by "Clean All" nor by "Clean Cache", e.g. on twitter.com assets remain after both.

**Comment by kennethtran93** [comment]
Cache storage is different from cache. 

Firefox currently has no support for this while Chrome does. But to add this and other site data that we haven't added in, a redesign of the current options is needed otherwise it will be too large to list every single site data option in use.

There is already an open issue/request for this.
