### ISSUE TITLE
[SUPPORT] Whitelisted site cookies being deleted

### ISSUE THREAD

**Issue by ACYNED** [mrdokenny/Cookie-AutoDelete#1428]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Please describe what you need support with

I literally just downloaded this and there are a bunch of terminologies that I can't wrap my head around. I have read the FAQs, wiki and a few past issues but I cannot find a solution to my problem so I am posting it. 
I can't really word this properly, so I'll attach images of my CAD settings and upload a zip of my whitelist. 
Basically, I added a bunch of websites to the whitelist and tried the manual function, (clean, include open tabs) to clean all my cookies except my whitelist. Thank goodness for the cleanup log feature! Because it removed all of the cookies, and the whitelist apparently did not work as they were no green bubbles. Please help!

![image](https://user-images.githubusercontent.com/109496483/179442441-b70f0835-eeed-4944-a872-582743b651ea.png)
![image](https://user-images.githubusercontent.com/109496483/179442810-2343600a-f857-45c0-b361-597ec58ea760.png)
[CAD_Expressions_2022-07-18_13.47.16.json.zip](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/files/9129352/CAD_Expressions_2022-07-18_13.47.16.json.zip)

**Comment by kennethtran93** [comment]
The green bubbles are currently disabled and a fix will be looked at for the future. A request has already been made for this.

For now, as long as you don't see any of your configured domains on that list in red, then you can relax as it hasn't been touched by this extension.

**Comment by ACYNED** [comment]
I see. 
But for me it seems like my whitelist really doesn't work.
![image](https://user-images.githubusercontent.com/109496483/179449369-704e5633-0be2-406d-a93e-082524105293.png)
For example, I had google set as whitelisted but it still got rid of all the cookies from it.

**Comment by kennethtran93** [comment]
What is your expression that you entered in and what were the expression options for that one? 

EDIT:  Looking at your attachment that you supplied above, you actually do not have an entry for `google.com`, so that's why those cookies were removed. You configured a few subdomains of `google.com` (e.g. `*accounts.google.com`, but not the actual main/root domain `google.com`)

Make sure if you're whitelisting google, you also include the end TLD (`.com`, `.ca`, etc) or use wildcard `.*` after google.  **We check the complete domain string from beginning to end** (e.g. `https://www.google.com` would be checked as `www.google.com`), so `*google` would not match due to the end string not matching.  However, your expression would match `example.google` (if it was a real domain).

If you're whitelisting includes subdomains, ensure you have the dot between the asterisk and google (`*.google.com`) so that you don't accidentally keep cookies from unintended domains (e.g. `ping.hellogoogle.com`  <- this would match `*google.com`)

**Comment by ACYNED** [comment]
Thank you! I've done the changes and am happy I got it working now. Really appreciate your help! 
Seems like the whitelist was actually working! 
My issue was that I didn't use the wildcards properly; that is I needed to put wildcards in front of the name of the website so that it could work in some cases. Another thing was that some of my whitelists had `www.` attached. I think this was because I put the sites in originally by using the commas to separate the names. Seems like some of the websites got added with that which apparently made them not function properly. Finally, as you first said I couldn't actually see any green bubbles which made me assume none of my lists were working, but part of it actually was.
