### ISSUE TITLE
[Bug]  Other Browsing Data Cleanup Options Missing

### ISSUE THREAD

**Issue by tsuliwaensis** [mrdokenny/Cookie-AutoDelete#1644]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Describe the bug

When using the [Zen Browser](https://github.com/zen-browser), a fork of Firefox, the other browsing data cleanup options (Cache, IndexedDB, LocalStorage, etc.) do not appear on the settings page. The fork is based on Firefox 130 so it meets the version requirement. 

### To Reproduce

1. Open the extension settings while using Zen Browser
2. The cleanup options for Cache, IndexedDB, LocalStorage, etc. is missing

### Expected Behavior

The options should appear

### Screenshots

<img width="1157" alt="Screenshot 2024-09-09 at 9 07 28 AM" src="https://github.com/user-attachments/assets/9fcd75af-5c83-4e5c-8aff-1f412e95cee3">

Zen Browser

<img width="1166" alt="Screenshot 2024-09-09 at 9 07 41 AM" src="https://github.com/user-attachments/assets/d4a3f727-d133-4879-bc19-f30061de3f26">

Non-Zen

### System Info - Operating System (OS)

macOS

### System Info - Browser Info

Zen 1.0.0-a.37

### System Info - CookieAutoDelete Version

3.8.2

**Comment by sistemforum** [comment]
hi. i use zen browser too. It doesn't work because zen reports firefox as Firefox 1

Vanilla firefox (don't mind the outdated version):
![369471670-c10b69f2-9a4b-4c7d-84fa-8be8ac8a8b2e](https://github.com/user-attachments/assets/852888e2-7233-4f2e-bb51-d9474f039d2e)


Zen browser:
![369471797-c5ebe900-2b36-463c-aec3-91ef0b3a633c](https://github.com/user-attachments/assets/3ba2836f-4ee6-4beb-90bb-77c8f6d14156)

can you fix this issue for  zen browser.

**Comment by kennethtran93** [comment]
You'll need to ask Zen browser to change how they are returning the browser version.  The browser is also not one of our officially supported browsers so we can only provide support where we can.

If you know how to code and can try and find a patch for it, then feel free to fix it and create a pull request with your changes.  I'm not fond of just relying on the build ID (which appears to at least include the date built) to determine if we should enable those options as it may break the extension if it isn't supported or create further issues about the extension not being able to clean it up because somebody has a super outdated Firefox browser that doesn't actually contain those functions if we were to enable them.
