### ISSUE TITLE
Popup opens off-screen

### ISSUE THREAD

**Issue by paol** [mrdokenny/Cookie-AutoDelete#182]
In the new interface the popup always opens below the icon, regardless of whether there is room. This can make open almost entirely off-screen ([see screenshot](https://user-images.githubusercontent.com/315432/31576175-ada73584-b0ed-11e7-87a0-766d0df59777.png)).

In the old interface the popup would open above the icon in this situation, which is correct.

- OS/version: Kubuntu 17.04
- Browser/version: FF 56.0
- Cookie AutoDelete version: 2.0.0

**Comment by rddim** [comment]
Confirm. When the browser is maximized it is OK.

* OS/version: Windows 7 Pro x64
* Browser/version: FF 56.0.1 x64
* Cookie AutoDelete version: 2.0.0

**Comment by scmanjarrez** [comment]
Confirm. I have minized the window in order to achieve the result.
![2017-10-15 03_50_17-popup opens off-screen issue 182 cookie-autodelete_cookie-autodelete](https://user-images.githubusercontent.com/9284124/31580871-1f6921a0-b15c-11e7-93a2-00f8647c98e1.png)

- OS/version: Windows 10 Pro, 1703, x64.
- Browser/version: FF 56.0.1 x64
- Cookie AutoDelete version: 2.0.0

**Comment by ke-d** [comment]
Should be fixed in #180
