### ISSUE TITLE
discordapp.com cookie not deleted

### ISSUE THREAD

**Issue by mooms06** [mrdokenny/Cookie-AutoDelete#199]
### Describe the Bug/Feature
discordapp.com cookie not deleted, not after a minute, not after restart.

### Screenshot in which the bug can be seen
After a fresh restart:
https://i.imgur.com/NJDVzia.png

### Steps for anyone to reproduce the bug
Login on https://discordapp.com/, close the tab, wait a minute and/or restart the browser, the cookie is still here.
Discord.gg is erased though.

Not the same bug, but somewhat related: the site still remember you even if you remove all cookies from discord:  https://i.imgur.com/XQygrGv.gif
The only fix I found is to delete everything with F12->Storage when on https://discordapp.com/,
Also, removing all cookies from Firefox options works, but obviously you will lost your cookies white-listed by Cookie AutoDelete.
This one was reported [on Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1409496)

### Your settings 
Delete cookies after 1 min & on start

- OS/version: Windows 7 x64
- Browser/version: Firefox 56.0.1 x64
- Cookie AutoDelete version: 2.0.1

**Comment by MarkRH** [comment]
The discordapp.com cookie is erased for me: https://i.imgur.com/CninLxI.png but the login details are stored somewhere else.  I have to do like you did and do F12 -> Local Storage and delete it while on the discordapp.com Tab.  

Apparently this is stored somewhere different than the list of sites that appear when you click the Settings button in the Site Data section of Security/Privacy because I couldn't see it there.

Well, now I'm seeing it in that list of sites after logging back into it but even if I remove it from there, it still keeps me logged in.

**Comment by mooms06** [comment]
See this thread on reddit: https://www.reddit.com/r/firefox/comments/76zrwb/how_httpsdiscordappcom_is_remembering_me/

**Comment by ghost** [comment]
They fixed cleaning from Firefox preferences for 57 https://bugzilla.mozilla.org/show_bug.cgi?id=1409496#c27
CAD still needs https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/44

**Comment by MarkRH** [comment]
Yep, it does delete the discordapp.com local storage now through preferences that it was missing before. Now just got to wait for CAD to have the ability to do that as well.

**Comment by ke-d** [comment]
Closing cause CAD can delete localstorage as of the latest beta.
