### ISSUE TITLE
With delay 0, cookies not cleaned until another tab is closed

### ISSUE THREAD

**Issue by ElhemEnohpi** [mrdokenny/Cookie-AutoDelete#223]
### Describe the Bug/Feature
When "Delay before cleaning" is set to 0 in Firefox, cookies are not cleaned when the tab is closed, but only when yet another tab is closed.

### Steps for anyone to reproduce the bug

1. create a new profile in Firefox 57
2. install Cookie AutoDelete
3. enable auto-clean
4. open a new tab with www.github.com
5. close the tab, wait one minute, note that 6 cookies are deleted
6. set "Delay before cleaning" to 0
7. open a new tab with www.github.com
8. close the tab, wait as long as you want, note that cookies are not deleted
9. close any other tab, note that the 6 github cookies are now immediately deleted

### Your settings 
Firefox 57.0b14
macOS 10.12.6
Cookie AutoDelete	2.0.1

**Comment by katalystsol** [comment]
I have the same issue

**Comment by ke-d** [comment]
I haven't noticed this with Chrome so it might be an issue of how FF is handling the tab close.

So what could be happening is that the cookie cleanup activates before the `github` tab **fully** closes, which would mean `github's` cookies would not be deleted until another tab close. I'll look into it but I think this is a FF bug.

**Comment by katalystsol** [comment]
One thing that I’ve noticed for FF is that the cookies will get deleted either when you close the 2nd tab, or if you wait a minute or so (I haven’t timed it specifically but I’ll get notification maybe a minute afterward that the cookie has been deleted).

**Comment by cincinnatus0** [comment]
Facing same issue on Firefox 57.

**Comment by Hellbringer10** [comment]
I don't know if I should start a new issue or post here.  My issue is probably related and would be fixed if this is fixed.  Also I don't know if my issue is even really a supported feature.

I have some tabs that i never or almost never close and some that I want to come back later to but dont really need and im too lazy to actually bookmark.  So I use a unload/suspend/hibernate addon to unload them from memory then cookieautodelete to come in behind that to delete the cookies so my open tabs arent tracking me all around the internet.  This functionality works great in chrome/chromium and earlier versions of firefox.  

In the new version of firefox cookie autodelete doesnt register the suspend as an action and doesnt seem to "look" on its own if any tabs that should be there "disappeared".  So no matter what I set my wait time to (0 minutes or 1 minutes or 10 minutes), this will NEVER delete my suspended tabs cookies until I close another tab, which pretty much breaks the functionality for me since this is the main way I use the program.

**Comment by ElectricFeet** [comment]
I have the same issue on two different Macs with Firefox 57. 

- One is a new upgrade to FF57 and addition of C-AD. 
- The other is mine and I didn't notice this happening yesterday -- so it's very strange. Is it possible that it's conditional on other FF settings/plugins? I changed a few since yesterday.

**Comment by ElectricFeet** [comment]
OK, I just did some more testing on this. It's not that C-AD is waiting for the next tab to close to delete the cookies on the previous tab; it's more complex. It is deleting _some_ of the cookies when the first tab is closed and then deleting the rest when the next tab is closed.

Specific example: on Wikipedia, the wiki**M**edia cookies are deleted on tab closure, but the wiki**P**edia cookies are deleted when the next tab is closed.

Detailed steps below.


## Test 1

**Testing environment**: Firefox Quantum 57.0 (64-bit); MacOS 10.13 (High Sierra); all other extensions disabled, so only extension is Cookie-AutoDelete.

**C-AD Settings**: 
- Enable Automatic Cleaning? **ON** Delay **0**
- Log Total Number Of Cookies Deleted? **ON**
- Show Number of Cookies for that Domain? **ON**
- Show Notification After Cookie Cleanup? **ON**
- Clean Cookies from Open Tabs on Startup? **OFF**
- Enable Support for Firefox's Container Tabs? **OFF**

Firefox settings:
- Accept cookies from web sites **ON**
- Accept third-party cookies **Never**
- Keep Until **I close Firefox**

Steps: 
- Open Firefox
- Open "Preferences" > "Privacy and Security" > "Show Cookies": **Empty**
- Close "Show Cookies", but leave preferences tab open
- Open (empty) new tab and go to https://en.wikipedia.org/wiki/Main_Page 
- Switch to preferences and click "Show Cookies": 4 groups of cookies are shown, from en.wikipedia.org; login.wikimedia.org; wikimedia.org; wikipedia.org (on some wikipedia pages, sometimes(?) wikipedia also sets cookies from meta.wikimedia.org)
- Close "Show Cookies", but leave preferences tab open
- Open (empty) new tab
- Close Wikipedia tab --> C-AD says it has deleted login.wikimedia.org; wikimedia.org cookies (and this is verified in "Show cookies")
- Close (empty) new tab --> C-AD says it has deleted en.wikipedia.org; wikipedia.org (and this is verified in "Show cookies")

## Test 2
All of the above, but with C-AD Delay set to 1 minute, C-AD deletes all the cookies correctly.

Hope this helps track the bug down.
