### ISSUE TITLE
Lastpass

### ISSUE THREAD

**Issue by EkalbM** [mrdokenny/Cookie-AutoDelete#233]
### Describe the Bug/Feature
Cookie Auto Delete disconnects Lastpass when Firefox is closed.

### Your settings 

- OS/version: Windows 10 Fall Creators
- Browser/version:  Firefox 56.0.2
- Cookie AutoDelete version: 2.0.1

**Comment by WagnerGMD** [comment]
You had forgot to mention the exact version of LastPass.

PS : I will assume the trouble might be related to LastPass. Because I had try the WebExtension (LastPass_v4.1.80.2_Beta) and it was better but it's remain buggy... LastPass was disconnect just after a restart browser. And no  at this moment, it was the unique addon which was installed

**Comment by EkalbM** [comment]
Sorry, here is the Lastpass plugin version (with Firefox): 4.2.1.21
See: https://addons.mozilla.org/fr/firefox/addon/lastpass-password-manager/

**Comment by ke-d** [comment]
I think I had something similar happen with SDC. I think manually whitelisting `*.lastpass.com` should fix it.

**Comment by thejeff77** [comment]
Adding a filter for *.lastpass.com doesn't do the trick. Seems like it might keeps its data in some container with a guid name for the browser extension.

**Comment by kennethtran93** [comment]
@thejeff77 If it does uses a container, you would see it in Firefox as an actual container, and the list is shown here: `about:preferences#containers`.

If we did clean that cookie, you would be able to see it in the log entries and could undo them.  Then you can check which cookie it is and whitelist that domain.

I've seen in some domains that they utilize a separate domain for API calls.  e.g. example.com and exampleapi.com or apiexample.com
