### ISSUE TITLE
No documentation on how to import (contains suggested text)

### ISSUE THREAD

**Issue by ElectricFeet** [mrdokenny/Cookie-AutoDelete#238]
There is currently no documentation on how to import (at least, there isn't in the documentation page of the wiki, and I cannot see any anywhere else).

I suggest something like the text below. (I presume that this is the correct way to do it; I worked it out by doing an export and then trial and error).

### <a name="importing-expressions"></a>Importing Expressions

- Create a .json file with the format: 

	```
	{
	  "default": [
	    {
	      "expression": "github.com",
	      "listType": "GREY"
	    },
	    {
	      "expression": "example.com",
	      "listType": "WHITE"
	    }
	  ]
	}
	```

	specifying, for each domain expression, "WHITE" or "GREY" (to be whitelisted or greylisted).

- In the Settings panel, select the "Import Expressions" button in the "List of Expressions" tab.

- Choose the .json file you just created.

**Comment by ke-d** [comment]
Good idea but I expect most people to just use the Settings UI.

**Comment by ElectricFeet** [comment]
Glad you like it :-)

Note that this ***is*** using the settings UI. It's just that you need to know the format of the file to be imported in order to use the settings UI.

**Comment by gwemmie** [comment]
This issue definitely needs addressing. I just went through an hour of hell trying to import a list of domains that I had already gone through an hour of hell typing by hand, because Cookie Monster's developer abandoned it years ago and it had no export option.

When I tried recreating the proper import format from what I got when I exported, I got an error that doesn't tell me anything:

`SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 12 column 1 of the JSON data"`

(Line 12 column 1 was the open brace of the second entry in the file). From there, I figured maybe I'm supposed to have a randomly generated ID for each entry just like the exported ones do. So, because I'm insane, I made a bash script to generate 9-character random alphanumeric sequences and add said sequence to the first occurence of "id": "", and ran that in a loop.

When that didn't work, I went into the storage.json file and used regex to get rid of all the whitespace from my own JSON file (and swap the positions of the listType and storeId entries of each item, because they're in an opposite order when exported vs stored in storage.json) and put those entries in that storage.json file, only to find that Cookie AutoDelete had responded by forgetting all of its settings.

It would have been nice to know an hour ago that all I needed to do was Google for this issue and find this information that only even exists because *another* user figured it out by trial and error. It would have been REALLY nice to have had that information from the beginning. It's easy to assume you don't need to provide that information if people are only ever exporting and importing from your extension, or from extensions with the same format, but that does NOT describe the current state or use cases of cookie-managing browser add-ons. I imagine countless people who are migrating to Firefox 57 and who care about their cookies are having similar trouble, because this extension does not document how you can go from a list of domains to a nice imported white/greylist.

**Comment by alexbelea** [comment]
Honestly struggling with importing as well. I'm trying to switch back to firefox and was using "Vanilla Cookie Manager" which just exports a list of domains one under the other in a text format, no scripting. I thought just pasting that into the Import UI (where the examples go by "domain coma space")  would work, they got added all in one row, however it didn't work and I lost all logins I had already made. 

This needs to be as simple as just pasting all the domains together in the UI

**Comment by gwemmie** [comment]
I just spent over an hour converting a plain list of domains into an importable format with good old search/replace. You can do that in 30 seconds by taking the following steps:

-Make sure the domains are in the format "*.domain.com/org/etc". I started out with them being just "domain.com/org/etc" and found that that did not include subdomains, while having the *. in front DID still include when there is no subdomain (like http://twitter.com), which I was worried about (I don't know a lot about domain matching rules; I'm just a simple regex man).

-Add a newline at the beginning of the file, so that there's one blank line above the first domain.

-Make sure there is no blank line at the end of the file.

-Using a text editor that supports searching for the newline character (depends on your OS; \n on Linux, \r\n on Windows, something else that I don't remember on Mac; for the purposes of this tutorial I'll be referring to them as just \n), search for `\n` and replace it with:
`    {\n      "expression": "`.

-Add a blank line at the end of the file.

-Search for:
`\n    {`
and replace it with:
`",\n      "listType": "WHITE",\n    },\n    {`
Change "WHITE" to "GREY" for the items that you want greylisted. If you want a lot greylisted, I recommend separating the greylisted ones into a separate file until after this step, so that you can replace with "GREY" instead of "WHITE", and then just appending them to the bottom of the whitelist file.

-Pay attention to the code that last step added. It should be this:
`",
      "listType": "WHITE",
    },`
Add that, WITHOUT the comma at the end, to the final entry, so that it is also a complete entry. We're omitting the comma because it's the end of the list, and a comma implies there are more items after this one. You'll have to do this twice if you had a separate greylist file, and you'll have to also make sure that only ONE of those last items (whichever one is last in the final file that has both lists) is missing the comma.

-Finally, add the bookends of the entire file. To the beginning:
`{
  "default": [`
Followed by a newline, so that the first entry looks like:
`{
  "default": [
    {
      "expression": "*.domain.com",
      "listType": "WHITE",
    },`
And to the end:
`  ]
}`
So that the last entry looks like:
`    {
      "expression": "*.domain.com",
      "listType": "WHITE",
    }
  ]
}`

And now the file is ready to import.

EDIT: Welp. It turns out Github's code blocks inexplicably refuse to pay attention to all the whitespace I put in there to make the code look nice. So, when you follow these steps, the files will seem ugly and unreadable, because all my indentation and newlines are gone. But don't worry--it will still work! Javascript is one of many programming languages that mostly ignores whitespace.

**Comment by fichtennadel** [comment]
I really miss the ease it was possible to import in V1. V2 is mapping storage and import format 1:1, which is not a necessity IMHO.

Especially right now when so many people have to migrate from their pre-FF57 extensions, any easy import method would be great.

Hint for the reader: I downgraded to V1.4.4 (https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/versions/), imported as plain text list and then upgraded to V2.

**Comment by askeydev** [comment]
Vanilla on Chrome was much easier to import/export.
AutoDelete could not process a comma separated list - tries to accept the string as one entry
I agree with the lack of documentation - users needed to know the JSON format.
  https://spacetelescope.github.io/understanding-json-schema/reference/object.html
I Entered 2 items on the whitelist (one at a time) and exported them to a file (below).  Deleted and reimported - that worked, but still gave a non-whitespace error.  JSON is not simple/quick for humans. 
Suggestion: Have a way to import/export a simple list.  This would be good for moving from other platforms.
Also tell it during import which list you are importing to. (override JSON listType)

**My test export/import with 2 entries:**
{
  "default": [
    {
      "expression": "finance.yahoo.com",
      "storeId": "default",
      "listType": "WHITE",
      "id": "HJQFzwkWG",
      "cookieNames": []
    },
    {
      "expression": "www.google.com",
      "storeId": "default",
      "listType": "WHITE",
      "id": "rkpLMvJWM",
      "cookieNames": []
    }
  ]
}

**Comment by ke-d** [comment]
I added https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentation#importing-expressions-courtesy-of-electricfeet to the doc.
