### ISSUE TITLE
Firefox 56 not supported?

### ISSUE THREAD

**Issue by ghost** [mrdokenny/Cookie-AutoDelete#281]
It seems cookies arent actually deleted even though it says they are deleted.
Is it possible to fix this and support firefox 56?

**Comment by Joel889** [comment]
Working for me on FF 56.0.2

**Comment by hasufell** [comment]
Same here under FF 57.0.1. This plugin does not work.

Switched to https://addons.mozilla.org/en-US/firefox/addon/self-destructing-cookies-1/ which works perfectly (apparently not "opensource" though)

**Comment by ghost** [comment]
So i found the issue. I had to leave this at default (false) `privacy.firstparty.isolate` so the cookies can get deleted.

**Comment by hackel** [comment]
I'm experiencing very strange behaviour with this add-on.  I get notifications frequently about cookies being deleted, yet I'm not sure it's actually working.  When I view my cookies, I see all kinds of domains I have not whitelisted, even after manually pressing "Clean, including open tabs."  However, clearly *some* cookies are being deleted.  I get signed out of my Google account, for example, but when I view my cookies, it shows cookies still existing for google.com and all kinds of other subdomains.

I had first party isolation enabled, which I have since disabled but it hasn't made a difference.  My understanding is that if I clear my whitelist, close all tabs, and clean my cookies, it should erase *all* my cookies.  I'm using FF 57.0.1 from Ubuntu.

**Comment by ke-d** [comment]
@hackel After disabling FPI, you have to clear all cookies from FF cookie manager to give it a fresh start.

**Comment by hasufell** [comment]
Doesn't fix it for me, cookies are still not deleted and it's reproducible on two installs. This isn't a "support" issue in any case.

**Comment by ghost** [comment]
@hasufell did you try it with a fresh firefox profile?

**Comment by hasufell** [comment]
Yes

**Comment by ghost** [comment]
Thats strange. its working for me on firefox 56.0. Making sure privacy.firstparty.isolate is disabled and After manually cleaning cookies and restarting the browser it should work.
