### ISSUE TITLE
Documentation : explain what greylisting does.

### ISSUE THREAD

**Issue by odwulf** [mrdokenny/Cookie-AutoDelete#303]
I searched for the meaning of greylisting in this extension and its documentation. Either it isn't there or it's hard to find. It might be an issue of something so obvious for devs and power users that nobody thought about explaining it.

In a broader view, it might be an worthwhile addition to have a couple paragraphs somewhere to explain to users who have never used a cookie deletion extension how it works and what it does.

**Comment by sorin-davidoi** [comment]
If you hover over the buttons you will see a tooltip explaining what they do. But you are right, it should probably be explained in the documentation.

**Comment by ke-d** [comment]
I just added:

https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentation#greylisting

**Comment by PF4Public** [comment]
Hi there, I have a similar issue with greylisting.

Turns out greylisting works differently if changing options.

Please document how "Keep all cookies" checked/unchecked affects greylisting.
I was confused by the fact, that checking specific cookies from this option made this greylisted entry behave like whitelisted. I mean those selected cookies were preserved indefinitely, even though the list is grey.

**Comment by kennethtran93** [comment]
@PF4Public Please start a new issue with the above.  That may be an actual bug instead.
