### ISSUE TITLE
[Feature Request] Storage Viewer

### ISSUE THREAD

**Issue by zero77** [mrdokenny/Cookie-AutoDelete#314]
Can you please implement a storage viewer, like the storage tab in Firefox developer menu.
Because, once you have left a web page in Firefox, to my knowledge you can’t see what still being stored by that domain.
Thanks

**Comment by ke-d** [comment]
This is somewhat similar to #272. The reason why I don't have any plans for this anytime soon is that I probably have to create the UI myself and there are already other extensions that do similar things.

https://addons.mozilla.org/en-US/firefox/addon/editthiscookieaddon/
https://addons.mozilla.org/en-US/firefox/addon/a-cookie-manager/

If you want other browsingData besides cookies (localstorage/indexDB), then it is impossible since there no API to enumerate them.

**Comment by zero77** [comment]
Essentially I am meaning the storage tab in Firefox developer menu but, that still accessible when the tab/domain is closed and overviews all domains.

 So more extensive than #272 but a simpler read only UI, although, I appreciate some of the APIs may not be available yet.

To my knowledge there aren't any other extensions available.

Also, this could help with debugging to make sure cookie water delete is working properly.

**Comment by kennethtran93** [comment]
I'm marking this request as not implementing due to the following:
- outside the core features of the extension (mainly removal of data from domains).
- At this point (correct me if I'm wrong), the only enumerable item are cookies still.  For that use https://addons.mozilla.org/en-US/firefox/addon/a-cookie-manager/
- Webextensions can only remove some data (e.g. localStorage) by blindly providing the hostname/domain if it is already known, or just clear it all.
- Storage Viewer (Firefox) / Application (Chrome DevTools) uses internal functions NOT available through webextensions.
