### ISSUE TITLE
privacy.userContext.extension & CookieAutoDelete

### ISSUE THREAD

**Issue by mooms06** [mrdokenny/Cookie-AutoDelete#334]
Hi,

I have no use of containers tab feature and I haven't checked the option to delete cookies from containers tab, but CookieAutoDelete is still adding the pref `privacy.userContext.extension	CookieAutoDelete@kennydo.com` forcing the containers tab feature to be enabled in Firefox.

It seems to me it's a bug, because I would like to disable this feature in Firefox but CookieAutoDelete don't allow me that.

- OS/version: Windows 7 x64
- Browser/version: 58 x64 final
- Cookie AutoDelete version: 2.1.0

**Comment by ke-d** [comment]
This depends on #152. Might be best to just ignore it for the time being?

**Comment by mooms06** [comment]
My question remains: why do you add a pref (locking the containers feature to on)  if the user is not using the feature ?
Can't you only add the key if the feature is enabled by the user ?
I would like to disable it but right now I can't.

Thanks.

**Comment by ke-d** [comment]
> why do you add a pref (locking the containers feature to on) if the user is not using the feature ?

Apparently that what the documentation states:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/contextualIdentities

>From Firefox 57 onwards, if an extension that uses the contextualIdentities API is installed, then the contextual identities feature will be enabled automatically.

I wonder if Tree Style Tabs has the same problem since it also uses Containers?

Either way permissions cannot be dynamically added or removed. If you *really* don't want Containers to be enabled you can build the extension without this line but you are on your own:

https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/blob/2.X.X-Branch/extension/manifest.json#L43

Or you can wait for #152 and ignore the Containers feature?

**Comment by mooms06** [comment]
>From Firefox 57 onwards, if an extension that uses the contextualIdentities API is installed, then the contextual identities feature will be enabled automatically.

I see, that's bad design imho.

I don't have the time/knowledge/will to build my own, but thanks for taking the time to answer.

Regards.
