### ISSUE TITLE
Notify that localStorage was cleaned for a website

### ISSUE THREAD

**Issue by grenzor** [mrdokenny/Cookie-AutoDelete#339]
Currently, the notification showed is worded as something like "3 cookies deleted" so it's unclear whether localStorage was was on or deleted from the website. Is it possible to add in the notification an indication of localStorage (like "3 cookies & localStorage deleted for ...") whenever that is also deleted?

**Comment by ke-d** [comment]
So currently I can do **get**, **set**, and **remove** for cookies since there's a dedicated API for that.

Since there's no localstorage API and it's lumped into the browsingdata API which only support **remove**, this is currently impossible. I would probably need a **get** API call.

Though there might be a way by using Web APIs but it seems hackish and not very reliable.

**Comment by kennethtran93** [comment]
whoops for stale...

In any case this is only partially fixed in the sense that manual cleaning of localstorage now has that notification.

**Comment by kennethtran93** [comment]
With the additional site data being cleanable by hostname, I took this chance to include notifications (manual and automatic cleaning) and activity log entries (only for automatic cleaning) for those as well.
