### ISSUE TITLE
firefox 54b11, auto delete sometime not working

### ISSUE THREAD

**Issue by phonphen** [mrdokenny/Cookie-AutoDelete#34]
firefox 54b11, auto delete sometime not working
set time for auto delete  0 minute
but sometime after close tab, cookies is not deleted

**Comment by mrdokenny** [comment]
One of two options

1. If "sometimes" you mean the notification does not show up?

I think that the cookies are cleared just the notification API has a problem with [quickly creating notifications ](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/notifications/create) which can happen when you close many tabs in a short period.

> If you call notifications.create() more than once in rapid succession, Firefox may end up not displaying any notification at all.

This is one of the reason why the minimum is 1 minute. Anything lower is at your own risk.

2. Cookies from the same base domain are not deleted. So if you have say developer.mozilla.org and bugzilla.mozilla.org, and close all tabs of developer.mozilla.org, cookies from both sites are not deleted cause you still have bugzilla.mozilla.org open which shares mozilla.org.

**Comment by Strayer** [comment]
Cleanup doesn't work for me on 54.0b14 (macOS) too.

I can see a lot of Cookies in the settings for both the default tab container and my other one. The addons settings still show a container I deleted and not a new one I created since then… maybe this is related?

Neither closing tabs nor clicking "Cookie Cleanup" or "Cookie Cleanup (ignore open tabs)" does anything, stats always show 0 cookies cleaned this session.

**Comment by mrdokenny** [comment]
@Strayer Container Mode is still **experimental**. I haven't done much QA for Adding/Removing Containers, so it's probably the Container cache not updating after removing/adding. 

1. Try using exporting your whitelist 
2. Switch to 1.3.0 under GitHub Releases
3. Restore Default Settings (this should make a new cache with all your current containers)
4. Reimport your whitelist

**Comment by Strayer** [comment]
Updated to 1.3.0, reset the settings and imported the whitelist again. Containers are now correctly displayed, so that is fixed for now – may make sense to open a separate issue for this to track the issue, won't have enough time to work on it myself :/

The cleanup still doesn't work though… any way I can debug what the extension is doing or if it is throwing any errors? I have no experience with WebExtensions on Firefox, so I don't really know how to provide better information :(

**Comment by mrdokenny** [comment]
@Strayer I made #41 

https://developer.mozilla.org/en-US/docs/Tools/Browser_Console

To debug, click the Cleanup buttons and see if there's anything that appears in the console.

**Comment by Strayer** [comment]
Okay, I saw an error that seemed similar to #40, so I updated to 1.3.1 – I'm not entirely sure if I had the same issue, but it is working again.

This was the error I saw:
TypeError: re.exec(...) is null[Weitere Informationen]  background-webpack.js:133:10

**Comment by mrdokenny** [comment]
@Strayer Hmm that means you probably had a non standard top level domain as the RegExp that I put only checks for a-z and not numbers or symbols. Good to know that it's fixed for you.
