### ISSUE TITLE
Cookie AutoDelete doesn't clear cookies completely !!

### ISSUE THREAD

**Issue by on1no** [mrdokenny/Cookie-AutoDelete#359]
Please See The Youtube Video Link its will explain everything 
https://youtu.be/4O-WgyfbENw

**Comment by ghost** [comment]
Why not just copy this text here?

**Comment by on1no** [comment]
Hi gwarser
My English is very bad and I use a Google translator to write
Google translation is not as clear as human translation so video explanation is better and easier for me

**Comment by ke-d** [comment]
Looks like it might be a cache problem rather than cookies problem (I checked that the site doesn't use localstorage or IndexDB). I'm considering an option to wipe cache periodically in #356 

Your other "cookie" extension not only clears cookies btw. It deletes basically everything including localstorage, IndexDB, cache, etc.
