### ISSUE TITLE
can this addon keep the protected cookies?

### ISSUE THREAD

**Issue by rezad1393** [mrdokenny/Cookie-AutoDelete#365]
I have reported the difference in this 
"https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/248"

is there anyway for this addon to keep the protected addon for not whitelisted addon?

**Comment by ke-d** [comment]
If you "protect" a cookie in one extension, then it's only protected from that extension only (through it's internal logic). Other extensions are still able to delete it because it's using an API to delete it.

So to answer your question: No, you would have to whitelist the cookie for both extensions.

**Comment by rezad1393** [comment]
I dont understand.
if I "protect a cookie in an addon as you say why then cookie-autodelete addon doeesnt delete it?(so it protects it)
