### ISSUE TITLE
Improvement to delete all Tracking Cookies (Local Storage, Channel ID etc.)

### ISSUE THREAD

**Issue by JimLoose** [mrdokenny/Cookie-AutoDelete#38]
I really love your Chrome extension approach, unfortunately it doesn't help at all because most big intrusive services track you down much deeper (they already know, Cookies are out)

Please have a look in `chrome://settings/cookies` on your own Cookies (i call Local Storage stuff Cookies as well) which are not deleted by your Cookie AutoDelete

![bild 2017-06-05 at 12 07 19](https://cloud.githubusercontent.com/assets/195000/26779917/9fab0914-49e7-11e7-8d78-cecb9e967f85.png)

![xvv6uqs](https://cloud.githubusercontent.com/assets/195000/26780156/a277f8c2-49e8-11e7-9ab1-6892da9da6d1.gif)

**Comment by mrdokenny** [comment]
Nice GIF. ;)

I wrote this in the description of the extension page: 

> - This Extension can't clear LocalStorage yet
See:
https://bugs.chromium.org/p/chromium/issues/detail?id=78093

What I'm looking for is an API that selectively clears site data by hostname. The only APIs is [browsingdata](https://developer.chrome.com/extensions/browsingData) which is an all or nothing approach by time frame which is not what I'm looking for. There's probably extensions that already use that API

FWIW, it seems like that bug might never get fixed in Chrome. Firefox might implement the API that I need sooner than Chrome.

**Comment by crssi** [comment]
@mrdokenny 1st I would like to thank you for doing this, really. :)
2nd: is there any ETA known for Firefox implementation? I don't mean your ETA, but Mozilla's. ;)

**Comment by mrdokenny** [comment]
@crssi 
1. Thanks!
2. Not sure about ETA since this [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1340511) is P5.

**Comment by mrdokenny** [comment]
I made #44 to discuss and deal with this issue. Please direct future discussion over there.
