### ISSUE TITLE
twitter cookies still won't stay

### ISSUE THREAD

**Issue by zzcool500** [mrdokenny/Cookie-AutoDelete#389]
no matter how much i whitelist everything that has to do with twitter it still forgets my login because of this addon, i just need to close my browser and reopen it and it forgot my twitter login completely, any idea why this is happening? i use chrome but it's the same on vivaldi

**Comment by nowherecoding** [comment]
Don't worry, it has nothing to do with CAD. There is something wrong with Twitter.

Workaround: Enter incorrect password. The second page that loads has a remember me option. Check this and enter correct password.

**Comment by zzcool** [comment]
Then why did it start as soon as I installed the extension worked fine before

**Comment by nowherecoding** [comment]
Don't know, it started about a month ago. I have tested it in a browser without the addon installed. Didn't work either. I installed CAD only last week.

**Comment by zzcool** [comment]
Tried doing what you said type the wrong password check the remember me checkmark it still forgets everything and every single whitelist option for twitter is whitelisted, this only started when i installed the extension on chrome it worked fine always worked fine then i installed the extension and the same thing as on vivaldi happens it forgets, i tried turning off auto cleaning of cookies i tried unchecking the  clear on open tabs etc nothing works.

**Comment by zzcool** [comment]
.twitter.com | ^\.twitter\.com$ | Whitelist
-- | -- | --
  | *.twitter.com | (^\|\.)twitter\.com$ | Whitelist

**Comment by neekt** [comment]
This is almost certainly a Twitter issue and not an issue with Cookie AutoDelete. Instead of logging in from the home page, try logging in from https://twitter.com/login/ and selecting 'Remember me'

**Comment by zzcool500** [comment]
still doesn't work as soon as i close vivaldi or chrome and reopen it the login is gone

**Comment by ke-d** [comment]
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/FAQ:-Common-Questions-and-Issues#why-are-examplecoms-cookies-being-keptcleaned

Hopefully version 2.2.0 and the cleanup log helps! If `twitter.com` doesn't show up in the log, then some other extension or tool is affecting those cookies.

**Comment by zzcool** [comment]
oddly enough it shows nothing in the logs, but it still forgets, not even in edge does it remember, i have no idea why this is happening or why it started as soon as i installed this addon.

**Comment by wohali** [comment]
Not trying to issuejack, but I'm seeing the same problem (though I haven't tried Edge). I'm having a similar issue with github.com - a domain where this clearly should be working.

A story in 3 pictures:

Picture 1 shows my whitelisting for github while having this very page open:
![mwsnap-077](https://user-images.githubusercontent.com/112292/40554355-72aa3636-6013-11e8-9a18-52b0e6614cb1.png)

Picture 2 is what happens when I close this page's tab:
![mwsnap-078](https://user-images.githubusercontent.com/112292/40554358-75d20956-6013-11e8-8e4e-9792593a2f82.png)

Picture 3 is the cleanup log (yes, it is enabled in settings):
![mwsnap-079](https://user-images.githubusercontent.com/112292/40554360-77c44cf6-6013-11e8-93d5-3f55849a6e8b.png)

When this plugin's auto-clean function is disabled, closing then re-opening a GitHub tab does not log me out.

Could this be related to private browsing mode (which I have enabled via "Always use private browsing mode") or disabling localstorage (which is currently enabled for me)?

**Comment by steptayl** [comment]
Same problem here: cookies whitelisted in CAD get deleted. Browsers want us to accept them. If CAD could save/restore whitelisted cookies it would be very useful but ...

**Comment by zzcool** [comment]
would be useful if there was a function to apply the cookie when you visit the website so that it's turned off when you're not on the website this prevents any kind of tracking even by website you want to save the logins for

**Comment by kennethtran93** [comment]
@wohali Your issue is a different issue, which has been already answered in a different (more-recent) issue (see #500, #537, #546).

@zzcool that would probably not fall into any scope of this webextension, but possibly a new web extension instead.

@zzcool @zzcool500 Is this still an issue in the 3.X.X versions?  If not, or after a few days, I'll close this

**Comment by kennethtran93** [comment]
Closing due to stale issue and referencing older versions.
