### ISSUE TITLE
[Feature Request] Display Third Party Domains and Sub Domains In Menu

### ISSUE THREAD

**Issue by zero77** [mrdokenny/Cookie-AutoDelete#391]
Can you please display all third party domains and sub domains that are being used on that page and their amount of cookies, in the drop down menu, like uMatrix dose.
Thanks

![33213085-ff74afd8-d0f3-11e7-8232-4c204925d274](https://user-images.githubusercontent.com/16563034/39472237-07c51cc2-4d40-11e8-8a36-da2dd5cee3a0.png)

**Comment by ke-d** [comment]
I'm not sure if that's possible with the APIs that I am requesting right now.

Those extensions I believe are using the [Webrequest API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest) which causes the *Access browser activity during navigation* to appear in the permission request. So this may or may not happen since people do get concerned when a new version request new permissions. #317

**Comment by armby1960** [comment]
It doesn't have to be as detailed as the uMatrix example.  Just a list of the domains similar to the matched domain list.  Cookie-AutoDelete must know what they are because they get deleted when the tab/window is closed.  Manually white/grey-listing them after the closure via the settings menu is difficult and susceptible to errors.

**Comment by csgit18** [comment]
This is actually a very important feature.  Many websites use a secondary domain and set cookies for that domain which must remain available in order for things to function properly.  Without CAD helping me learn which cookies are being set, I have to do a guessing game using the cleanup logs.

Example 1:  If I have auto-cleanup set, and these "invisible" cookies disappear because I didn't greylist them, all of a sudden I have unexplained issues.  (Today I kept losing a support chat session because of this problem.)  
Example 2:  Some websites use these secondary domain cookies to hold your identity and recognize your computer (browser profile, really) as being previously authenticated.  If you lose these cookies, you keep having to go through additional authentication (2FA).

Hope you'll consider adding this feature soon.

**Comment by kennethtran93** [comment]
> It doesn't have to be as detailed as the uMatrix example. Just a list of the domains similar to the matched domain list. Cookie-AutoDelete must know what they are because they get deleted when the tab/window is closed. Manually white/grey-listing them after the closure via the settings menu is difficult and susceptible to errors.

Not that I want this issue/feature to be bumped up, but I'll help clarify why the additional permission is needed:  The only way (that I know of that) this webextension 'knows' is when it compares the site url from the cookies in storage to the white/grey lists and open tabs.  If you have multiple sites opened, then this extension won't know which third-party cookie is which.

**Comment by armby1960** [comment]
The extension doesn't need to know which third-party cookie is which.  It just needs to display the ones updated by then current sites open.  Then just like the ones that match the url, the user makes the decision which to white/grey list.  If I had any doubts about some cookies, I would only white/grey list them while only having the site open where I need them.

And you wouldn't have to display them for everyone.  It could be an option for the extension.  You could default it to Off so that it doesn't change the change the current user interface unless it is something someone specifically wants.

I do appreciate the reply.   Thank you!
Dean


    On Monday, April 22, 2019, 6:52:10 PM EDT, Kenneth T <notifications@github.com> wrote:  
 
 

It doesn't have to be as detailed as the uMatrix example. Just a list of the domains similar to the matched domain list. Cookie-AutoDelete must know what they are because they get deleted when the tab/window is closed. Manually white/grey-listing them after the closure via the settings menu is difficult and susceptible to errors.


Not that I want this issue/feature to be bumped up, but I'll help clarify why the additional permission is needed: The only way (that I know of that) this webextension 'knows' is when it compares the site url from the cookies in storage to the white/grey lists and open tabs. If you have multiple sites opened, then this extension won't know which third-party cookie is which.
