### ISSUE TITLE
Unable to import whitelist in Chrome 66

### ISSUE THREAD

**Issue by mawie** [mrdokenny/Cookie-AutoDelete#396]
I'm trying to import my cookie whitelist from Firefox (v60, 64-bit) to Chrome (v66.0.3359.181, 64-bit). After importing the list to Chrome the settings page just shows me 6 entries although I have more sites whitelisted. And if I visit a site where Cookies are whitelisted, it just shows me the red symbol and all the cookies get deleted.

I already tried to reinstall the add-on and even Chrome but the problem still exists. The interesting thing is, if I export the whitelist from Chrome it shows all my whitelisted sites although the add-on doesn't recognize them.

Exporting and importing the whitelist in Firefox works without any issues.

I'm using the latest version of Cookie AutoDelete (2.2.0) on Windows 10 1803 64-bit (April Update).

**Comment by mawie** [comment]
I was able to fix the issue myself by comparing an exported Cookie-AutoDelete whitelist from Firefox and Chrome. I opened them with Notepad++ and noticed that in the export from Firefox the "storeId" was called "defaultWhiteList" instead of "default". After changing it to "default", I was able to import the whitelist in Chrome without any issues.

**Comment by ke-d** [comment]
Probably have to fix some inconsistencies with the storeId as the Firefox default storeId is different than Chrome's.

**Comment by Urbs3w** [comment]
I was unable to import a white list too into Chrome 76 until I added `"storeId": "default"` for each entry.

When I didn't include the storeID while importing, then exported the filters to see what went wrong, I noticed that the entries I had imported were saved to a section named `undefined`. instead of `default`.

Should the [Wiki](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentation#importing-expressions-courtesy-of-electricfeet) be updated?

Currently stated syntax:
```
 {
   "default": [
     {
       "expression": "github.com",
       "listType": "GREY"
     },
     {
       "expression": "example.com",
       "listType": "WHITE"
     }
   ]
 }
```

Syntax for Chrome that worked for me:
```
 {
   "default": [
     {
       "expression": "github.com",
       "listType": "GREY"
       "storeId": "default"
     },
     {
       "expression": "example.com",
       "listType": "WHITE"
       "storeId": "default"
     }
   ]
 }
```

**Comment by kennethtran93** [comment]
The documentation has been updated to include storeId, and thus will close this issue now.

Thanks @Urbs3w .
