### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by happysurf** [mrdokenny/Cookie-AutoDelete#4]
CA is a good web extensions start for manage the cookie automatically.
These are my suggestions:
- CA must be read the existing cookie exceptions list in Firefox, because is very annoying add again all the web sites;
- When a site is added in white list the CA icon must change the color ( i.e. green) otherwise I don't know what is the current condition if not click on the icon.
- Cookie Cleanup option what delete?

Thanks.

**Comment by mrdokenny** [comment]
1. I don't have access to that list in WebExtensions from what I see. Though I think my way is better since you have a way of exporting the whitelist where in SDC you couldn't.

2. I could probably add that through the color of the number badge that displays how many cookies for that site.

3. Cookie Cleanup does the same thing as if you close a tab and waited.

**Comment by SW1FT** [comment]
> I could probably add that through the color of the number badge that displays how many cookies for that site.

I don't use the badge of any extension because it looks ugly, could you just change the background of the icon from blue to green or red (or whatever other color you want) depending on the cookie deletion state of the website?

**Comment by mrdokenny** [comment]
That background color is part of the icon. So the background can only be changed if I have different colored icons and swap them on the fly, where as the badge is easier cause I can just change the color hex value.

One thing I'm wondering is how often do you check if the site is in the whitelist? Because I feel once you have every site you wanted in the whitelist, you don't need to check the cookie deletion state as often.

**Comment by SW1FT** [comment]
> One thing I'm wondering is how often do you check if the site is in the whitelist? Because I feel once you have every site you wanted in the whitelist, you don't need to check the cookie deletion state as often.

That's true, but maybe you can just gray out the icon if it's not deleting cookies on a page, similar behavior to uBlock Origin where if it's not active the icon is gray.

**Comment by mrdokenny** [comment]
You can try this now in 1.1.0. I think you might be using FF Dev/Nightly with signing off. So in that case, to try it, you can download the .zip of this repo and dragging the zip to the FF addon manager.

There's some work left to be done such as making the badge color match and overall general color consistency, but basic functionality is there.

I will upload the new version once I'm happy with the features and once AMO reviews my extension (which I don't know when that will be :( )

**Comment by mrdokenny** [comment]
Uploaded 1.1.0 to AMO and now waiting for first review. Queue: 112/503
