### ISSUE TITLE
Cookie prompt

### ISSUE THREAD

**Issue by davidhedlund** [mrdokenny/Cookie-AutoDelete#400]
"Firefox used to allow you to be notified every time a Web site attempted to set a cookie. You could decide to accept or reject the cookie as well as specify the cookie lifetime and whether to use your choice for all cookies from the Web site, thereby updating your cookie preferences. This feature was removed in Firefox version 44.0." - https://www.savarese.org/patches/firefox.html

IceCat (a Firefox ESR-based browser) users have asked the developer to restore the cookie prompt (see https://savannah.gnu.org/bugs/?49603) but that will require extra maintenance, I know that the developer won't have time for that.

Could you please implement a cookie prompt in Cookie Autodelete?

**Comment by chiraag-nataraj** [comment]
Wait, this was a thing in earlier Firefox releases? :open_mouth: I had no idea...I know that some browsers like w3m or elinks have the same option (iirc).

This should be implementable via cookies.onChanged.addListener (https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/cookies/onChanged)

**Comment by ke-d** [comment]
This might also require https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onHeadersReceived, which means requesting an additional permission (webrequest) that I'm not comfortable requesting currently, at least until I do a blacklist.

Might be best for someone else to make this and maintain it as it would be a different cookie policy and philosophy.
CAD:
- Accept all now, clean what you don't want later
- Set it and forget it
Cookie Prompt:
- Accept/Reject some cookies now
- A lot of manual labor

Also, I can easily maintain features that I actively use CAD since I use these features everyday. Features I that I don't find myself using, won't get the same treatment. So it's better for me and the stability of CAD's main core features to turn this issue down and let someone else do it. 

Though I might allow other extensions to access the whitelist/greylist by exposing an API in case a potential cookie prompt extension comes out.
