### ISSUE TITLE
,

### ISSUE THREAD

**Issue by ghost** [mrdokenny/Cookie-AutoDelete#412]
/

**Comment by Grossdm** [comment]
Hey @triune, remember that many of us are using Firefox!

Some of us cannot tolerate the security risks of using Chrome.

**Comment by triune** [comment]
@Grossdm Chrome is more secure than any other browser if you neglect the fact you're sharing a lot of data with Google. This I don't personally mind.

Regardless, this ticket was aimed at the Chrome Webstore implementation of Cookie Autodelete as a feature for that particular variant. I'd imagine the implementation could abstract Chrome Sync and Firefox Sync so that it was cross-browser.

**Comment by ke-d** [comment]
> As simple as the topic states, implementation is probably more difficult than this one line of text I'm writing!

Yeah this requires making a backend server which would go against the [privacy policy](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Privacy-Policy). Closing in favor of #30
