### ISSUE TITLE
Cookie per domain, not per website (Global Subdomain checkbox)

### ISSUE THREAD

**Issue by heubergen** [mrdokenny/Cookie-AutoDelete#45]
### Describe the Bug/Feature
Currently the extensions seems to keep all cookies that a website save e.g. when I add pcgames.de to the website, Cookie AutoDelete also keep the cookie forum.pcgames.de, login.pcgames.de.
For my understand, Cookie AutoDelete should only keep cookies for pcgames.de strictly.

### Steps for anyone to reproduce the bug

1. Fresh profile, install Cookie AutoDelete
2. Whitelist cookies only for pcgames.de 

### Your settings 

![screen-000253](https://user-images.githubusercontent.com/5529410/27138298-838f8800-5120-11e7-8c63-04affbbe6ae5.png)

- OS/version: Win7 Pro x86
- Browser/version: Firefox Nightly 56 x86
- Cookie AutoDelete version: 1.3.1

**Comment by mrdokenny** [comment]
Well, people have been asking for that behavior. See #3

**Comment by heubergen** [comment]
I had some stupid things in my head so I needed to edit my previous request.

I understand that it is always about keep the balance between the normal users who wish a simple solution and the pro users who wish a more advanced solution.
May you could do it like that:
Whitelist *.google.com - google.com and all subdomains
Whitelist google.com - google.com only

**Comment by heubergen** [comment]
Yes, that would also be helping :)

**Comment by collectorgeneral** [comment]
@mrdokenny That is an excellent idea, having a "Whitelist Domain" option or something along those lines. 
Please do update here when you get around finishing that, since I have C-AD currently disabled, it is a bit annoying since most of the websites are a bit painful to work with without domain whitelisting.

**Comment by mrdokenny** [comment]
@collectorgeneral 
> it is a bit annoying since most of the websites are a bit painful to work with without domain whitelisting.

What do you mean cause Whitelisting domains in 1.3.0+ works like this. You add google.com and cookies from *.google.com are protected so drive.google.com would be protected.

In 1.2.0, whitelisting google.com only protected google.com and not drive.google.com.

What this issue is proposing is an option to switch between 1.2.0 whitelisting behavior and 1.3.0 whitelisting behavior.

**Comment by collectorgeneral** [comment]
@mrdokenny Woops, upon a bit more investigation, I may have found a couple of issues with the current domain system implementation you have. I will open another issue since it does not belong here.

**Comment by mrdokenny** [comment]
Added a setting called "Enable Check for Subdomains" that can be tested in 1.4.0b1.

**Comment by heubergen** [comment]
looks great, thank you!

**Comment by mrdokenny** [comment]
So there's this setting in SDC: 
![capture](https://user-images.githubusercontent.com/17077613/27408682-bad162da-5692-11e7-8147-19081683e824.PNG)
Anyone know if that setting is the same as the option I added in this issue or is it something completely different?

**Comment by 07416** [comment]
@mrdokenny Does the "Enable Check for Subdomains" setting work with the "clear all cookies for this domain" setting?

**Comment by mrdokenny** [comment]
@07416 No
