### ISSUE TITLE
Notification popup off-screen

### ISSUE THREAD

**Issue by ncoleman** [mrdokenny/Cookie-AutoDelete#462]
### Describe the Bug

The Notification popup appears to align its top-right corner with the CAD icon on the extension toolbar.  If this icon is on the left of the screen, the Notification box is too large and its left side disappears off the left edge of the screen.  It becomes unusable.

Because of the FAQ entry about not being able to move the popup, I'm entering this as a bug instead of a feature request since it renders the extension unusable.  A simple fix would be to set the popup location to the right of the screen instead of tying it to the location of the extension's icon.  The font is large.  Perhaps an alternative fix would be to use a smaller font.

###  More
It takes dozen(s) of icons on the toolbar before the popup is pushed off the left edge of the screen.  A temporary fix is to move the icon to the right, but this is inconvenient if you have your icons grouped into "categories" and your cookies category is to the left.  It means CAD's icon is off by its lonesome on the right side.  There are other workarounds such as hiding some other icons in order to "drag" the CAD icon to the right.   However, these are inconvenient.

### Re-Opening
This report may be re-opening the bug report that led to fix #180.

### Screenshot in which the bug can be seen

![2018-11-17-092028_1920x997_scrot](https://user-images.githubusercontent.com/594168/48654815-dcf01080-ea4a-11e8-8f43-53e35523bb69.png)

### Versions
- OS/version:  Linux, Debian 9.6 Stretch
- Browser/version:  Iridium 2018.5  (Chromium-based)
- Cookie AutoDelete version: 2.2.0 (I think)

**Comment by ke-d** [comment]
![untitled](https://user-images.githubusercontent.com/17077613/50543763-53794580-0b95-11e9-9c2d-20d50101ebe2.png)

Maybe it's a OS issue as this is on Windows?
@ncoleman

**Comment by pv** [comment]
On Linux (Firefox 66, Gnome 3.32, Wayland), when the popup open outside the window (as in the image above in https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/462#issuecomment-450534449), the buttons on the popup are not clickable, which is annoying. One has to unmaximize Firefox and move the window around to somehow make CAD open the popup inside the window.

The popup also tends to open so that it goes partially off-screen (for example when CAD icon on the right and the Firefox window maximized), and one has to unmaximize and move the window around to get it right.

**Comment by porjo** [comment]
I'm having this issue since migrating to Firefox on Wayland (previously I was using Firefox on X11). In my case the popup disappears off the right hand side of the screen, and I'm also unable to click any of the buttons (e.g. 'Whitelist'). I can however tab through the buttons, and hit space bar as a work around.

Other extensions with popup panels don't have this problem e.g. Ublock Origin, KeepassXC-Browser however these are contained within the Firefox window which could explain why.

**Comment by kennethtran93** [comment]
Doing a bit of housekeeping - is this still an issue?  I'm running Windows and X11 at this time and the popup fits accordingly within the screen.

**Comment by porjo** [comment]
Not an issue for me anymore - the popup stays within the firefox window and is fully visible. Thanks

**Comment by kennethtran93** [comment]
I'm going to close it for now then.  Most likely it was a OS-dependent bug back then.
