### ISSUE TITLE
All preferences were erased / reset to defaults

### ISSUE THREAD

**Issue by hackel** [mrdokenny/Cookie-AutoDelete#472]
### Describe the Bug/Feature

This is possibly a dupe of #273, but a lot has changed since then.  I opened up Cookie AutoDelete's preferences today, and noticed that all of my settings were gone/reset to defaults, counters reset, etc.  Needless to say, this is very distressing as I had quite an extensive list of expressions defined per-container.

Unfortunately I don't have a lot more information than that.  There is a zero byte browser-extension-data/CookieAutoDelete@kennydo.com/storage.js.corrupt file, I don't know if that suggests it could have been an OS/hardware issue that truncated the settings file?  Some type of automatic backup would definitely be appreciated.

### Your settings 

All settings lost and reset to defaults.  Previously, I had:
Enable Automatic Cleaning? y
Delay Before Cleaning:Second(s)? 15s
Enable Cleanup on Domain Change? yes
Enable Cleanup Log and Counter? yes
Show Number of Cookies for that Domain? yes
Show Notification After Cookie CleanupSecond(s)? no
Clean Cookies from Open Tabs on Startup? yes
Enable Support for Firefox's Container Tabs? yes
Localstorage Cleanup (Firefox 58+)? yes

- OS/version: Ubuntu 18.10
- Browser/version: Firefox 65.0b3
- Cookie AutoDelete version: 2.2.0

**Comment by ke-d** [comment]
Hmm I had this happen once to all my extensions and it was due to
https://bugzilla.mozilla.org/show_bug.cgi?id=1406181

Basically, they are switching from storage.js to indexedDB. This setting controls that `extensions.webextensions.ExtensionStorageIDB.enabled`.

Generally, erased settings don't happen unless settings are corrupted from which CAD will start anew. 

> Some type of automatic backup would definitely be appreciated.

I don't know how much has changed but extensions don't have access to write to file system without an external program. This seems mostly an external issue and without much information there isn't much I can do.
