### ISSUE TITLE
Feature Request -- a way to preserve individual cookies from a domain you do not wish to whitelist.

### ISSUE THREAD

**Issue by lac22** [mrdokenny/Cookie-AutoDelete#492]
I am not sure that this is even possible.  

But Google keeps sending me  "A privacy reminder from Google", or rather the Swedish version of the same.  Since I am not logged into a google account, it is trying to save the information that "I have read and accepted the privacy policy" in a cookie.   Which then gets deleted, of course.  I would like a way to just preserve that single cookie and continue deleting any others that google tries to inflict upon me.

This is clearly just a convenience.  Thank you for this most excellent program.

I am using FireFox Quantum 64.0 on debian linux.

**Comment by StephGbzh** [comment]
You can already do that since version 3.0.0, it's just not very intuitive.

You start by adding the site to the whitelist and then immediately untick "Keep All Cookies".
(Or you go in the settings and for that site, untick "Keep All Cookies")

That will show a list of all the cookies known for that site and you can choose to tick only the one(s) you really want to whitelist.
All other cookies will be deleted as usual.

**Comment by lac22** [comment]
YAY!  Thank you very much.

**Comment by clairity** [comment]
hi, new users (like me) would appreciate some quick documentation on the "Keep All Cookies" (and "Keep Localstorage") option. i was trying to puzzle it out myself but luckily found this github issue. thanks!

**Comment by ke-d** [comment]
Just added:

https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentation#whitelisting-individual-cookies

**Comment by lac22** [comment]
Thank you very much for the doc, too.
