### ISSUE TITLE
Cookies deleted when redirected to paydirekt payment site

### ISSUE THREAD

**Issue by Qhilm** [mrdokenny/Cookie-AutoDelete#505]
When booking a train ticket on bahn.de and choosing paydirekt as a payment method at the end, even though it is done inside the same tab and "Enable Cleanup on Domain Change" is disabled, all cookies from bahn.de get deleted (I saw the notification while on paydirekt webpage), thus the browser is unable to return to the bahn.de booking page (“invalid session” or something like that is displayed) and one has to painfully chase to get reimbursed (because payment _was_ successful).

I had this issue on booking.com with paydirekt as well, thus I am confident it is related to paydirekt.

- OS/version: macOS 10.14.3
- Browser/version: Vivaldi 2.3.1440.48
- Cookie AutoDelete version: 3.0.1 (Chrome)

**Comment by AggravatingSignUpExperience** [comment]
What rules do you have defined? My experience is that a "lack of matching rule" means delete any cookie right away (possibly after you leave that domain).

You could define a whitelist rule matching everything, but that will make it ignore ALL other rules since whitelist rules are evaluated first.

I reported this problem, but have not heard back since clarifying my point.

**Comment by Qhilm** [comment]
I don't have this issue when selecting PayPal somehow... If I don't close
the tab and of "cleanup on domain change" is disabled, then no cookies
should be deleted, is my understanding.

**Comment by AggravatingSignUpExperience** [comment]
My experience is that if it hits the bottom of the rules without matching a rule it is deleted right away. This doesn't seem to be intended behavior, but my bug report on it (in the context of the private container -- which you are not allowed to add any rules for) states that this is intended behavior (without clarifying).

I mentioned that no logs were saved (which I mentioned ONLY for debugging purposes), and that I was not permitted to make any rules (and since there were no rules) everything was deleted right away (rather than when the private session ended). I was told that it was intentional and my bug was closed. I'm just not sure _which_ of those things were intentional or why. (logs: fine, can't make rules for private container: why??, everything deleted right away if no rule matches: why??)

I don't think you are in private mode so the lack of logs doesn't apply to your case, nor does the inability to make rules for that container.

I don't know what rules you have defined, but if you don't have whitelist rules defined then your cookies get deleted right away for any non-matching sites. I would think the preferred default behavior would be to not touch cookies that don't match any rules. (having this be user configurable would be even better)

Possible workarounds for your case: Have a second tab open for all sites you don't want cookies deleted for. Make a whitelist rule for every site which would otherwise match no rules.

**Comment by Qhilm** [comment]
That's not my experience, it does not delete any cookies until I close the tab. Except for this specific case of course....
I can put bahn.de on the grey list, but then I need a rule for every site were I pay using this payment method, which is not practicable.

**Comment by ke-d** [comment]
What I do in this scenario is to disable Auto-clean, not the most convenience solution, but it is a workaround.

**Comment by AggravatingSignUpExperience** [comment]
I'm not 100% clear on what the intended action of they greylist is in this program, but it seems if you were to whitelist ✱.bahn.de (or possibly greylist it depending on what that's supposed to do) it would solve your problem. (not that it would fix the same problem on other sites that you don't know about yet)

**Comment by Qhilm** [comment]
The greylist is for deleting cookies when the browser is closed/restarted. The whitelist means cookies are never deleted.

**Comment by AggravatingSignUpExperience** [comment]
And no match apparently means delete the cookies as quick as possible (maybe not if a tab still has that domain in the address bar). This isn't working out great for me.

**Comment by kennethtran93** [comment]
If you enable automatic cleaning and set delay to something like 15 seconds, would that work better?

**Comment by AggravatingSignUpExperience** [comment]
No not at all, if I haven't  explicitly defined a site I don't want it's cookies touched. 15 seconds later doesn't help at all.

**Comment by PhrozenByte** [comment]
> What I do in this scenario is to disable Auto-clean, not the most convenience solution, but it is a workaround.

@mrdokenny A solution might be another form of greylist, let's call it "changelist": If you add `paydirekt.de` (or PayPal, or any other payment service, or even OAuth services) to the "changelist", CAD's "Cleanup on Domain Change" feature is bypassed when someone changes from a arbitrary source domain (e.g. `bahn.de`) to `paydirekt.de`. All cookies from `bahn.de` won't get auto-deleted unless the user leaves `paydirekt.de`.

*Example:* One adds `paydirekt.de` to the "changelist". The user opens `bahn.de` to buy a train ticket. `bahn.de` sets some cookies. While checking out his ticket, the user is redirected to `paydirekt.de`. However, because `paydirekt.de` is in CAD's "changelist", the cookies from `bahn.de` won't get auto-deleted (i.e. navigating to `paydirekt.de` won't trigger auto-deletion of the source domain). The user finishes the payment process and is redirected back to `bahn.de` - which works just fine, because the cookies of `bahn.de` weren't deleted. For the sake of completeness: If the user is currently on `paydirekt.de`, but is redirected/navigates to any other domain but the source domain (e.g. `google.com`), auto-deletion is triggered (i.e. cookies from `bahn.de` being auto-deleted).

I've no idea how much work it would require to implement this or whether it's even possible. IMHO it's the only reason why I can't recommend CAD to non-techies like my father (they just won't understand why they can't pay with `paydirekt.de`). Anyways, CAD is a amazing project no matter what! :heart:

**Comment by kennethtran93** [comment]
The best course of action for this is to temporarily disable autoclean, or add the previous site into a greylist/clean on browser restart before the payment happens.

**Comment by htsmi** [comment]
I think I'm missing something here... according to the documentation with "Enable Cleanup on Domain Change" false, shouldn't cookies be kept until the tab is closed? Of course I have "Enable Automatic Cleaning" true, without that it won't clean cookies when I close the tab. I'm having the same issue as the original reporter on a number of sites, and I thought that turning off "Enable Cleanup on Domain Change" was supposed to prevent that.

**Comment by kennethtran93** [comment]
CAD will continue to trigger for *any* tab that was closed as well, and looks at the state of opened tabs/domains at that time.

It also depends on whether or not the payment was done from a new tab that the other site opened as well, so that closing would also trigger the cleanup (after the delay)

**Comment by htsmi** [comment]
Hmm, so you're saying that if I start on one domain but end up on another, and then close another tab that was open to the original domain, all that domain cookies will be cleaned? I understand why that would happen and how it could cause some unexpected cleanup. I don't think that is the whole picture here though.

I'll have to see if I can replicate this again, but I remember it was a problem on Office 365 login which obnoxiously jumps between somewhere around five domains. Of course the complete solution would require accounting for which tab cookies originated in, that may not be possible and is probably beyond the scope of this program at this point.

**Comment by kennethtran93** [comment]
CAD triggers cleanup when any tabs are closed. It will look at the state of opened tabs at that time. If the domain you want to keep is not opened or on the lists at the time of triggered cleanup, then it will be removed. 

Yes disable the domain change for now until you have figured out which domains you want to keep. If you have time, you can try to do screen recordings of the url bar and replay them to see the url used.

**Comment by htsmi** [comment]
So it appears that what happened, at least with Office 365, is that it jumps through so many different domains and at a certain point insists on opening a link in a new tab, so when I close the old tab, all the cookies from the previous domains get cleared. Which is a little unexpected but technically makes sense. So I've just made it a point to keep the old tabs open and that seems to have solved it.
