### ISSUE TITLE
Cookie Autodelete on Waterfox

### ISSUE THREAD

**Issue by PeterBesenbruch** [mrdokenny/Cookie-AutoDelete#513]
I am running Cookie Autodelete 3.0.1 on Waterfox 56.2.8 for Linux. I have found it deletes cookies when it is supposed to. Indeed, it works fine. The only issue is that the extension says it does not support Waterfox. The minimum is Firefox 59. The Mozilla add-on site will not let me download, so I went with a Softpedia download, supposedly for Windows. Waterfox dutifully reports the extension as incompatible, but lets it work anyway. It works well.

Perhaps you could allow the download without forcing me to jump through such hoops?

**Comment by ke-d** [comment]
The reason why the minimum version was bumped was because First Party Isolation + CAD doesn't work unless you are on a FF version of 59 or higher. And also containers mode might be buggy on WaterFox from what I seen from previous bug reports. 

But if you don't use either of these features, then you can also install CAD from the releases tab.

https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/releases

**Comment by PeterBesenbruch** [comment]
On Sat, 13 Apr 2019 08:32:56 -0700
Kenny Do <notifications@github.com> wrote:

> The reason why the minimum version was bumped was because First Party
> Isolation + CAD doesn't work unless you are on a FF version of 59 or higher.
> And also containers mode might be buggy on WaterFox from what I seen from
> previous bug reports. 
> 
> But if you don't use either of these features, then you can also install CAD
> from the releases tab.
> 
> https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/releases

Thank you. No, I don't use containers, and I use your extension exclusively
automated, ongoing cookie deletion.

**Comment by kennethtran93** [comment]
Closing issue as it is resolved and that it is also not an officially supported browser.
