### ISSUE TITLE
import text file

### ISSUE THREAD

**Issue by Kristianwhittick** [mrdokenny/Cookie-AutoDelete#527]
Feature

It would be nice to be able to import plain text files to the white list if the data has been sourced from elsewhere.
As it is I would have to format the data into JSON and try and generate the ID's

**Comment by Kristianwhittick** [comment]
Feature

It would be nice to be able to import plain text files to the white list if the data has been sourced from elsewhere.
As it is I would have to format the data into JSON and try and generate the ID's

**Comment by kennethtran93** [comment]
>  As it is I would have to format the data into JSON and try and generate the ID's

The ID can simply be a comment or randomness as CAD will regenerate the IDs anyway.

With the recent enhancement of using comma-separated URLs in the textbox, it should be fine to do that instead of importing.

Even plain text files would need to be formatted in a way for us to read it, including the list type as well for each url.  There is no selecting which list it falls under during import.
