### ISSUE TITLE
Extension not working in [Android] Kiwi Browser (Chromium based)

### ISSUE THREAD

**Issue by 05nelsonm** [mrdokenny/Cookie-AutoDelete#528]
### Describe the Bug/Feature

Cookies not being automatically cleared upon exit of tab or browser

### Screenshot in which the bug can be seen

Verification that cookies have not been deleted:

In Kiwi Browser's Clear Data section (cookies still there.
![Screenshot_20190510-133341_Kiwi_Browser](https://user-images.githubusercontent.com/44778092/57545424-4e3cbc00-7328-11e9-82df-eaec214a905a.png)

No deleted cookies in CAD's logs.
![Screenshot_20190510-133317_Kiwi_Browser](https://user-images.githubusercontent.com/44778092/57545427-4ed55280-7328-11e9-887d-71e2b9c0ee63.png)

### Steps for anyone to reproduce the bug

•install Kiwi Browser from Play Store
•install CAD on Kiwi Browser for Android via the chrome extension store
•enable automatic cleanups, etc.
•close tabs and/or browser
•start browser back up and check to see if cookies were deleted

### Your settings 
![Screenshot_20190510-132955_Kiwi_Browser](https://user-images.githubusercontent.com/44778092/57545279-d8385500-7327-11e9-90e1-2a16f841f80f.png)

- OS/version: Android 8.1.0; SM-G965F Build/OPM7.181205.001 /// LineageOS 15.1-20190403-microG-star2lte
- Browser/version: Kiwi Browser 74.0.3729.136
- Cookie AutoDelete version: 3.0.2

**Comment by wokawoka** [comment]
I was going to open the same issue today! 
I confirm the same problem.
Having it fixed would be just great

**Comment by kennethtran93** [comment]
Chrome support is only valid on Desktops.  Native Chrome browsers on Android don't have webextension support (at least not for this webextension nor any with 'cookie' keyword on it) so I don't think we can do much here.

Check with the author of that browser app to see if they have successfully implemented the chrome.cookies API (https://developer.chrome.com/extensions/cookies).

At this point, the 'Available for Android' option in the Chrome Web Store links that web app/extension to its Play Store version, which is technically a separate app altogether.

**Comment by 05nelsonm** [comment]
yup...

https://github.com/kiwibrowser/android/blob/master/chrome/common/extensions/api/cookies.json

EDIT:

All my other extensions all work properly, too.

**Comment by kennethtran93** [comment]
Hmmm...It's not that [the author] doesn't want to support it, but much like Opera and Waterfox, support isn't guaranteed for those either.

Also that page may have been simply forked over from the chromium project - not sure how he actually packaged it all into an APK and made it work.

See if the XDA community have any details on making it work, as some may have gotten it work. If you can troubleshoot and figure out where that bug is on that browser, then by all means leave a detailed bug screenshot showing where the error is.

**Comment by kennethtran93** [comment]
Closing this issue due to unofficially supported browser.

**Comment by Maxxee** [comment]
"Closing this issue due to unofficially supported browser."

Wtf is wrong with you! So technically you are not willing to do anything. Useless extension then, doesn't work. Ridiculous.

**Comment by kennethtran93** [comment]
If you think you can figure out what issue(s) are preventing that browser from working properly (and may even have a fix for it) then by all means let me know and/or submit a PR with the fixes needed to make it work (and won't interfere with existing functionality for Firefox desktop, Firefox Android, or Google Chrome desktop).

**Comment by kennethtran93** [comment]
> "Closing this issue due to unofficially supported browser."
> 
> Wtf is wrong with you! So technically you are not willing to do anything. Useless extension then, doesn't work. Ridiculous.

Also comments like these are demoralizing and makes some people (me included) not want to even attempt to look into it in the future. Had it been worded otherwise, I may have even taken part of my day in the near future to see if it is a quick fix or not.

**Comment by Maxxee** [comment]
I'm just wondering why you didn't use all the time in the last few years to fix the code, maybe also have a look at Kiwi's code.

Okay, that's absolutely no problem at all. It's the only extension anyway, no competition, so development is stuck anyway. And if it's gone, then all privacy features/protections are gone anyway.
I only hope that privacy browsers will include such functionality, so that no extensions are needed. That's even safer anyway.

**Comment by Maxxee** [comment]
PS: I found out that CAD works and deletes site data when Kiwi browser starts. For this the browser app has to be force-closed.

**Comment by Maxxee** [comment]
> > "Closing this issue due to unofficially supported browser."
> > Wtf is wrong with you! So technically you are not willing to do anything. Useless extension then, doesn't work. Ridiculous.
> 
> Also comments like these are demoralizing and makes some people (me included) not want to even attempt to look into it in the future. Had it been worded otherwise, I may have even taken part of my day in the near future to see if it is a quick fix or not.

So now you resort to trolling, because I use the phrase what the frak (courtesy of BSG) aka. wtf, to justify your obvious unwillingness to even look deeper into the issue.

This is indeed even more ridiculous than your blatant shutdown by simply adjusting to "unofficially supported browser".

**Comment by Rubiginosa** [comment]
> If you think you can figure out what issue(s) are preventing that browser from working properly (and may even have a fix for it) then by all means let me know and/or submit a PR with the fixes needed to make it work (and won't interfere with existing functionality for Firefox desktop, Firefox Android, or Google Chrome desktop).

Just an update on this if y'all ever have the time to work on it... the extensions seems to work just fine now **except** for automatic cleaning. Manually cleaning works perfectly.

**Comment by htsmi** [comment]
I'm sorry some people were rude to you here, I personally appreciate all you've done in offering your work here for all of us for free! I've started using Kiwi Browser lately since it seems like the only decent option left for browser extensions on Android. Firefox has just become a total embarrassment, no full extensions support, no tablet UI, no printing, no about:config so I can't even disable telemetry or use a custom sync server for over a year.

Cookie AutoDelete at least appears to work properly, and clear everything, not just cookies, but like the others noted, it doesn't trigger on tab close. It also appears not to trigger on domain change when that's turned on, but it does trigger on browser restart or manual cleaning. This is probably not fully implemented APIs but just curious if you can check that since I don't have the expertise to do that myself.

**Comment by Rubiginosa** [comment]
It looks to me like one of the recent Kiwi updates fixed this. At least with notifications enabled, AutoDelete triggers as expected.

**Comment by qol3m** [comment]
It seems to work, but not in the specified time frame (e.g. 30 seconds). It usually takes way longer and I am unable to figure out how it works. In any case, thanks for making it work.
