### ISSUE TITLE
[Suggestion] Auto-whitelist domain on log-in

### ISSUE THREAD

**Issue by TRPB** [mrdokenny/Cookie-AutoDelete#532]
Firstly, thank you for this great addon. One feature that would be nice is if cookie autodelete required as little user-intervention as possible.

If I log into a website I almost certainly want to allow cookies on that site. It would be good if it was possible to automatically whitelist a domain if I submit a form with `<input type="password">`.

**Comment by kennethtran93** [comment]
That would require executing a script on that tab itself, thus adding extra processing time for each tab to detect if any such input is available (and possibly more than one).  What you're also implying to do is to override the original submit button to first inform the webextension that the submit button is being clicked, then actually click it.  This webextension only checks the data provided by the browser tab object when each tab gets updated (tabs.onUpdate).  We don't know how it was updated (either the history back/forward buttons, form submit, link clicks, etc).  A malicious website could create a hidden form with input type password which would then be submitted if you were to say click on a link (or even a button).  This may be pushing the boundaries of security and privacy of having a webextension see the html code and modify it secretly in the backend (even though we do have permissions for that).  I believe user intervention is required so that you're only choosing whether or not to grey or white list it (i.e. logging in only for that browser session or as allowed by the site), as well as whether to keep localstorage and any additional cookies from that site that doesn't necessarily have to do with the credentials.

**Comment by kennethtran93** [comment]
After a revisit to this, I think I'm going to close this as not implementable at this time due to my comment above.

**Comment by elypter2** [comment]
is it possible to check i a login is saved in the password manager for a certain domain?

**Comment by kennethtran93** [comment]
> is it possible to check i a login is saved in the password manager for a certain domain?

You would need to manually check the password manager itself, and the steps to do it depends on your browser.  Webextensions do not have the ability to check anything in the browser password managers.
