### ISSUE TITLE
Whitelist not working when "Always use private browsing mode" is selected

### ISSUE THREAD

**Issue by idealist1** [mrdokenny/Cookie-AutoDelete#537]
This is tested on Firefox 67 clean profile.

If you have selected "Always use private browsing mode" or "Never remember history", the whitelist won't work (it will still delete the cookies).

I'm not sure if this is intentional, but whitelist doesn't override "Delete cookies and site data when Firefox is closed" and the cookies are still deleted after Firefox restart.

**Comment by kennethtran93** [comment]
This is intentional as you're configuring Firefox itself to remove them.   Firefox has its own internal whitelist that is accessed through Firefox Preferences.  The webextension whitelist only works within this extension's internal code.  Firefox removing the cookies itself is outside this webextension's actions.

**Comment by kennethtran93** [comment]
Closing due to specified Firefox Settings specified as mentioned above.  Your Firefox settings take precedence over the web extension.
