### ISSUE TITLE
Issue with Gmail and e10s

### ISSUE THREAD

**Issue by Evpok** [mrdokenny/Cookie-AutoDelete#54]
C-AD seems to be affected by [Firefox bug #1338309](https://bugzilla.mozilla.org/show_bug.cgi?id=1338309)  : after installing C-AD (and then, even if it is disabled and even in safe mode), if opened in an e10s-enabled window, Gmail (with Gmail and Google properly whitelisted) will complain that cookies are disables and refuse to load. If opened in a non-e10s window, it works as it should.

**Comment by mrdokenny** [comment]
You should follow the template if you are reporting a bug.

I am unable to reproduce this, which means do a refresh Firefox (because SDC might have messed up your profile somehow?) and only install Cookie AutoDelete and then report back.

**Comment by collectorgeneral** [comment]
@Evpok I had the exact same issue a while ago while trying to restore my profile. This has nothing to do with C-AD since I experienced the issue before I started using the addon. I tried clearing cookies but to no avail. The only solution is to do what @mrdokenny suggested, create a new profile and it should solve your problem.

**Comment by Evpok** [comment]
I solved the issue by deleting my `permission.sqlite`, so it might have been some leftover from an old SDC install…

**Comment by 07416** [comment]
@Evpok The file is `permissions.sqlite`.
