### ISSUE TITLE
Feature request: blacklist

### ISSUE THREAD

**Issue by ElhemEnohpi** [mrdokenny/Cookie-AutoDelete#543]
### Describe the Bug/Feature

For reasons that aren't clear to me, issue #134 has been closed. So I'm opening a new issue, to request the blacklist feature again.

Sites on the blacklist would never be allowed to set cookies (or, technically, cookies would be instantly deleted). This is similar to the black "instantly" cleanup type rule available in the [Forget Me Not](https://addons.mozilla.org/en-US/firefox/addon/forget_me_not/) addon.

Ideally this could be set per container, so a site could be allowed to set cookies within the container used for it, but not in other containers. It would also be nice to have the option of setting this as the default, for sites that otherwise have no rule set.

**Comment by kennethtran93** [comment]
My apologies there - Since in the original post there was a browser listed that wasn't supported and an old CAD version listed, I had presumed that it was a bug of some sort.  I've reopened that feature and removed the browser and CAD version to reflect that it's a feature request.  Feel free to add any notes back into the original one if need be.

**Comment by kennethtran93** [comment]
Repopened Issue #134 - post blacklist feature (per container I suppose now) there.
