### ISSUE TITLE
Chrome Web Store – 404

### ISSUE THREAD

**Issue by YoRHa-A5** [mrdokenny/Cookie-AutoDelete#545]
Hi, I tried downloading the extension for a Chromium based browser, but the link to the store gives me a 404.

**Comment by kennethtran93** [comment]
Hmmm... I certainly don't see it either at this time.  I wonder what Google Chrome WebStore is up to this time...

In the meantime, you can try and download directly from this repository and install it manually:  https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/releases

Keep in mind that we only support Mozilla Firefox and Google Chrome at this time. Derivatives of those, including WaterFox and other Chromium-based browsers are not guaranteed to work fully and are not supported at this time.

**Comment by kennethtran93** [comment]
@mrdokenny There's probably something on your end that needs to be resolved to get this webextension to show up again on the Chrome web store.

**Comment by ke-d** [comment]
It got taken down due to a new policy change.

https://blog.chromium.org/2019/05/taking-action-on-deceptive-installation.html

Specifically they have a problem with `irrelevant, misleading, or excessive keywords in app descriptions, titles, or metadata`, which I submitted a revision, cleaning up the description a bit. But it's still under compliance review and they have removed the listing in the store in the meantime. 🤷‍♂

**Comment by Snipy2k4** [comment]
when will this be fixed?

**Comment by kennethtran93** [comment]
If it's still under compliance review, then it's up to Google at this point...

**Comment by Snipy2k4** [comment]
Thanks for the feedback

**Comment by albert71292** [comment]
Hope Google puts it back in the store soon. I use the extension in Opera, and it works fantastic!

**Comment by miguelusque** [comment]
Hi!

Same issue here.

Please, let us know when solved! I will use the zip version as a workaround.

And thank you for this fantastic tool! I love it!!!

**Comment by YoRHa-A5** [comment]
Yay, it's back :)
