### ISSUE TITLE
Automatic localstorage cleanup doesn't work

### ISSUE THREAD

**Issue by meelten** [mrdokenny/Cookie-AutoDelete#556]
### Describe the Bug/Feature

Automatic localstorage cleanup doesn't work although the option in settings is checked.
There are no errors in notifications or in cleanup log.
I don't use containers tabs and don't have support for containers enabled.
Manually cleaning localstorage through toolbar icon and Clean menu **works as intended**. Only automatic cleanup doesn't.

### Steps for anyone to reproduce the bug

I in particular noticed it on site filmweb.pl. Visit any random movie pages, e.g.:
https://www.filmweb.pl/Terminator
https://www.filmweb.pl/Predator
https://www.filmweb.pl/film/Matrix-1999-628

Now, right above the very bottom of the site you should see those movies in "ostatnio odwiedzone" (recently visited) section. Close tabs and check back if localstorage was cleared.

### Your settings 

- OS/version: arch linux
- Browser/version: firefox 68.0.1 64bit on linux
- Cookie AutoDelete version: 3.0.2

**Comment by Klimmbimmel** [comment]
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/FAQ:-Common-Questions-and-Issues

Check the FAQ: it seems like not all types of cookies can be deleted by CAD. (
"What is the state of the WebExtension API to clean X data?") Check out the type of the cookies. (I don't know how to do that.)

I had the issue with gaming websites for the first time now. 

**Your settings**
- OS/version: Windoze 10
- Browser/version: firefox 68.0.1 64bit
- Cookie AutoDelete version: 3.0.2

**Comment by kennethtran93** [comment]
@meelten Hmmm...I can't seem to duplicate the results after trying to visit that site through the three links. (Mind you I also temporarily trusted the domain through the NoScript extension as well as temporarily disabled adblock for that site too).  By results, I mean that I don't even see that named section you are referring to at the bottom of the page.  Unfortunately as it is not displayed in English, I cannot help as much as I would be able to.

As a final note, the site may be storing details outside of localstorage and cookies (e.g. Session Storage/IndexDB, which we cannot clear by host due to API limitations).
However, if you were to 
1. visit those pages (ensuring that the recently visited section fills up)
2. manually clear localstorage and cookies using the popup clean dropdown section
3. refresh your page and see that your recently visited pages came up empty
(presumingly what you mentioned above), then
4. revisit those pages (ensuring that you see the recently visited section fill up again)
5. close all related open tabs
6. wait for the auto notification for that site
7. try opening that site again to see if that section is still populated

and it is still populated afterwards, then it would then need to be looked into further.  Note that the automatic cleaning runs the same function as the manual one, so logically it would have cleaned it up already.

**Comment by cookiengineer** [comment]
I wanted to confirm that some websites were also not automatically delete-able via CAD in autoclean mode. I'm using Chromium 75, also happens in 76.

Websites that were using localstorage in my case:

- appdb.winehq.org
- shop.tympanus.net
- old.reddit.com
- services.amazon.de (and bunch of aws domains)
- www.linkedin.com

(...) there are some others, of course, but the appdb.winehq.org website is a good testing start, I would guess. Above domains were not part of any rules/expressions, so they should've been all deleted.

When looking at the [utils](https://appdb.winehq.org/js/utils.js?f=1510071002) code on the appdb website, they do nothing more than just setting keys via `localStorage[some_random_id] = 'true'` and that's pretty much their API usage.

**Comment by rugabunda** [comment]
On FireFox I had dozens of local storage, and hundreds of third and first party cookies left behind both by CAD & SDC; [CookieBro ](https://addons.mozilla.org/en-US/firefox/addon/cookiebro/)got rid of all of that without any issues.

**Comment by ctechols** [comment]
I was able to reproduce the problem in a fresh firefox profile where CAD was the only extension installed.

I left CAD settings as default with the exception of enabling 'Localstorage Cleanup'
I visited 'www.epicgames.com'
I closed the www.epicgames.com tab.
I waited for the notification indicating the cookies from epicgames.com were deleted.
I visited the 'Manage Cookies and Site Data' section of firefox preferences.
www.epicgames.com is in the list with 10.6MB of storage listed.

For good measure I also restarted firefox.  I confirmed the site data was still present after the restart.

**Comment by kennethtran93** [comment]
@cookiengineer Chrome localstorage was previously unavailable, thus no localstorage removal was done for chromium browsers.  Tracking via #523. 

@rugabunda could you elaborate on which sites I could test and figure out the reason why it is not removing said items?  I would also need your CAD and firefox cookie settings as well.

**Comment by pera** [comment]
@kennethtran93 I am currently experiencing this problem with Firefox 69.0.1 (64-bit) + CAD 3.0.2 on this website at least: https://www.indiehackers.com/
(the firebase localstorage key is never deleted)

**Comment by rhendric** [comment]
@kennethtran93 Go here for a quick and easy test: https://jsbin.com/nujewoxojo/edit?output

Reloading the page should increment the counter. Clearing local storage manually with CAD resets the counter, but waiting for the autodelete notification does not.

I'm running FF 71.0b7 (64-bit) and CAD 3.0.2.

**Comment by SpaceClicker** [comment]
Just an FYI, I'm running Firefox version 70.0.1 and it appears to work fine for me.  It automatically clears the 3 cookies (session, session.sig, last) that are set by the page after I close the tab for https://jsbin.com/nujewoxojo/edit?output.  If I go back to the page the counter has reset and indicates "1" again.

**Comment by pj-camp** [comment]
I can confirm this on my browser. Cookies are deleted but local storage is not. In fact, to actually clear local storage, I have to do so manually. Since that should do the same thing as automatic clearing, it seems like the automatic part is what is failing. Notably, this happens on Google. In addition to direct inspection, when I look in the logs there is no mention of local storage being cleaned, only cookies. I've tried both letting it do its thing on its own as well as creating greylists with both cookies and local storage unchecked. Doesn't matter. It isn't a huge deal for me since a couple of clicks on my way out does the cleaning, but I'm curious why that would happen.

**Comment by kennethtran93** [comment]
Small update for this issue:

- Localstorage cleaning actions are NOT logged into the activity log yet at this time - only cookies.  The hostnames are being passed into the removeLocalStorage browser function.  I'll try to rework the activity log at a later point in time.
- The difference between manual 'Clean Localstorage for this domain' and the auto localstorage cleanup, is that the manual one relies on the existing tab, to which we push a small function to that page to clear it's localstorage via `window.localstorage.clear()`.  The auto cleaning relies on browsingData.removeLocalStorage({hostnames: hostname}) function provided by the WebExtension API.

**Comment by kennethtran93** [comment]
A bug is found and is in progress of getting fixed.  There were multiple duplicate issues so there was some additional  info gathered that helped me debug this.

**Comment by cookiengineer** [comment]
Awesome! :+1:
