### ISSUE TITLE
More suggestion than issue

### ISSUE THREAD

**Issue by tedomedo** [mrdokenny/Cookie-AutoDelete#558]
This addon doesn't show cookies nor all domains. It shows only domain of a site which i watch. 
On some sites i want to be always logged in. With this addon i can't protect some cookies. That's why please show all cookies and let us delete them individually even if we're on empty tab.

**Comment by kennethtran93** [comment]
There are other web extensions that will allow you to show all stored cookies irregardless of which tab you are in, as well as delete them. (https://addons.mozilla.org/en-CA/firefox/addon/a-cookie-manager/ or https://addons.mozilla.org/en-CA/firefox/addon/cookie-quick-manager/)


Through this web extension, there are ways to see individual cookies that you want to keep/delete, though the site would need to set that cookie up first in order to save it.  First is to visit the site in question, then open the popup.  Whitelist/greylist the site first, then uncheck `Keep All Cookies` to see the cookies being stored by that site.  Alternatively, once a site has been whitelisted/greylisted, visit the Expression Table in Settings, then uncheck `Keep All Cookies` to see all cookies stored by that site.

To restore deleted cookies by this web extension, this setting MUST be enabled beforehand:  `Enable Cleanup Log and Counter`.  Note that previously deleted cookies prior to enabling this feature are (most likely) not recoverable at least by this extension.  Then you can undo all the cookies that were deleted on a particular cleanup timestamp.  What I do is that I would look the details of the deleted cookie for domains to keep, then manually add it into the expressions table in settings before restoring it.

**Comment by Grossdm** [comment]
> This addon doesn't show cookies nor all domains. It shows only domain of a site which i watch.
> On some sites i want to be always logged in. With this addon i can't protect some cookies. That's why please show all cookies and let us delete them individually even if we're on empty tab.

@tedomedo, I agree with @kennethtran93 about [Cookie Manager](https://addons.mozilla.org/addon/a-cookie-manager).

I have used it for a long time, and the developer even implemented a suggestion/request from me.

Perhaps you have already resolved your problem from @kennethtran93's reply, but if not I would first suggest that you re-read his post carefully.

If you are still stuck, then the basic procedure would be:
1. Add the domain of a site that you want to protect from logout to the whitelist. **If** you are not currently logged in and viewing that site, then you must access the "List of Expressions" in addon settings, i.e. `about:addons`.
2. You should probably add the site as `*.example.com`, at least until you have reviewed how the site stores its cookies.
3. As soon as the site is added, uncheck the "All Cookies" box. This displays a list of cookies, each with a checkbox for you to choose to protect.

Note that **CAD** does not show the contents (or other details) of cookies.
For that, I again suggest the addon I mentioned above.

Best of luck - I hope this helps.

P.S./N.B.
I just thought of a scenario which would require an additional step.
If you have (as your issue suggests) allowed **CAD** to delete cookies for the sites of interest, then there won't be any cookies for you to review as I described in step 3.
In that case:

    2.5. Login to example.com, and continue to step 3.

(I couldn't find a way to add a fractional list item in the markup. If anyone knows how I might have handled that better, suggestions or guidance is welcome.)

**Comment by kennethtran93** [comment]
Closing due to stale issue.  There are other extensions which does this already and it is most likely out of CAD's scope.
