### ISSUE TITLE
An issue with greylisting

### ISSUE THREAD

**Issue by PF4Public** [mrdokenny/Cookie-AutoDelete#559]
Hi there, I have an issue with greylisting.

Turns out greylisting works differently if changing options.

Please document how "Keep all cookies" checked/unchecked affects greylisting.
I was confused by the fact, that **checking specific cookies** from this option made this greylisted entry behave like whitelisted. I mean those selected cookies were preserved indefinitely, even though the list is grey, which removes the differentiation between grey- and white-list.

**Comment by kennethtran93** [comment]
I've just tested using greylist and checking specific cookies to keep after restart.  It had cleared all but those cookies as stated in the recent cleanup log.

![(50) YouTube - Firefox Developer Edition](https://user-images.githubusercontent.com/6724477/63733127-08025e80-c82c-11e9-9a2e-6e5ca15e8b53.png)

For comparison, below is the previous log entry before this one, which shows all cookies being deleted.
![(50) YouTube - Firefox Developer Edition_3](https://user-images.githubusercontent.com/6724477/63733198-3aac5700-c82c-11e9-9ae0-8c8397541606.png)

---

Also, if said site was still part of your opened tabs upon browser restart, then you would need to check this option in order to remove said cookies, otherwise the cookies would not be removed as Firefox would already have those sites/tabs in place BEFORE the webextension was able to execute its greylist cleanup.
![Cookie AutoDelete Settings - Firefox Developer Edition](https://user-images.githubusercontent.com/6724477/63733270-7e06c580-c82c-11e9-8208-07307903f5bb.png)

---
For clarity, I am using Windows 10 Enterprise/Pro, with Firefox Developer Edition 69.0.b16 64-bit and CAD 3.0.2

**Comment by PF4Public** [comment]
I've tried this again and it seems that by the time "Clean Cookies from Open Tabs on Startup" occur, website was already opened with all the previous cookies in place. So that the webpage gave an impression of me being still logged-in. Refreshing the page reveals, that sometime inbetween these two events, cookies were actually removed.

This is actually logical. Should this be probably documented somewhere? Like: "Removing cookies upon browser start may happen _after_ the tab has been completely loaded, giving the impression, that cookies were not deleted". Or something like this…

**Comment by kennethtran93** [comment]
I'll add a note in documentation regarding this.  Unfortunately I don't think it can be easily fixed at this time.

**Comment by kennethtran93** [comment]
Closing this as a documentation note has been added to the 'Clean Cookies from Open Tabs on Startup' and 'Greylisting'.

Apologies for the rather long delay in resolving this.

If you really want the site to not even know about the cookie on startup, this webextension would require additional permission `webrequestblocking` which should 'block' the tab from loading via a redirect to a blank page or something similar, and would require you to hit the back button to continue, thus giving the extension some time to perform its cleanups, or add additional code to 'redirect'  you back to that original url after the cleanups are done.  Either of which would take additional resources from the CPU side to handle timings.  I'm not sure having this additional permission is really worth it at this time.

**Comment by PF4Public** [comment]
I do realise, that it is not a trivial thing to fix, therefore, mentioning that in docs should be enough.
