### ISSUE TITLE
Wise 365 PRO deletes settings every time it's run.

### ISSUE THREAD

**Issue by GozerOfTheGozerians** [mrdokenny/Cookie-AutoDelete#562]
If I run Wise Care 365, and do it's functions PC checkup and PC cleanup, all settings are gone!

Steps to reproduce:
Install Wise and run it. (Hundreds of millions use it. So we got a serious issue here!)

Possible fix: a save button, and saving the file into a type or place Wise does not flag at. 
Also this file should do a mini SHA code in CAD so the program knows this file only holds -the correct- settings code. If the SHA does not match, the file is deleted, and the user get's a popup the SHA was changed. (A hacker/dragnet/etc counter who resets it to 'open doors')

Windows 7+newest firefox here.

**Comment by kennethtran93** [comment]
The settings are stored using Firefox's own storage mechanisms through indexDB.  

I'm referencing previous issue to perhaps shed some background info:  #472, #516 

Also putting the newest firefox doesn't help as it would change as time passes and firefox gets updated.  Putting the exact version would help especially when older dated issues get looked into and the version isn't listed.

**Comment by kennethtran93** [comment]
I'm marking this issue as invalid as it is caused by an external program.  
We do not know how Wise flags file for cleanup and I myself do not use Wise at all.  Perhaps if you have the Wise cleanup log files then you can decipher how Firefox-related things get deleted.

Closing for no response to my earlier response.
