### ISSUE TITLE
Please help me configure CAD So it will delete ALL cookies except ones in white list!

### ISSUE THREAD

**Issue by rezpower** [mrdokenny/Cookie-AutoDelete#566]
I am not sure if I am doing something wrong or if the problem is with the extension. But what I need to do is simple and yet can't get it done. I want cookie auto Delete to keep the cookies that I have added to my white list and when I restart the browser to delete ALL other cookies. When I check in both chromium (edge) or firefox white list cookies are kept, but there are many other cookies remaining that have not been deleted!

Can someone please help me with this issue?

**Comment by kennethtran93** [comment]
could you screenshot your settings and upload it here for me to see?  In terms of what your expression table should show is your sites in the whitelisted area and '*' for greylist if you want to delete all other cookies upon restart.  Also what firefox cookie settings are you using?

**Comment by rezpower** [comment]
Thank you very much for your help kennethtran93. I had my whitelist correctly configured. But did not have the greylist setting as you mentioned. I added * to the greylist.

Now my greylist look like this:
https://ibb.co/n0YQRZr

was i right to uncheck "keep all cookies" & "keep local storage" ?

here is a screenshot of my settings:
https://ibb.co/G5790Vc
For firefox I have not made any particular costume setting for cookies and i am using the default 
https://ibb.co/zfSx72r

but even after the changes still I see undeleted cookies!
https://ibb.co/7Gk6PpG

**Comment by kennethtran93** [comment]
Ideally you would only use '*' in greylist if you want to keep all cookies until the browser restart.  If you want the cookies to be removed 15 seconds after tab close while the browser is still running then the greylist is not what you need.  
As for browser restart, if you have tabs open from the previous session, then those sites would NOT get its data erased unless the option to clean open tabs on startup is checked.

P.S:  Some Gmail's cookies you checked off for * are under *.google.com's area:
![Cookie AutoDelete Settings - Mozilla Firefox](https://user-images.githubusercontent.com/6724477/64069092-60a07580-cbf7-11e9-9efa-730299c594e9.png)

If there are other cookies leftover upon restart (and after the startup cleanup phase), please provide that screenshot (Manage Data button on the firefox cookie settings in your screenshot) and we could look into those further.

As for the CCcleaner one, because you have enabled the cleanup log and counter, it stores the cookies somewhere else outside of Firefox's regular cookie area so that in the event you need to restore those cookies from that specific timestamp you can.  I'm not sure how CAD stores the backup of it at this time, but CAD was only meant to prevent other websites from the browser side to eavesdrop on cookies, not from an external program on the computer.
(The screenshot given is also blurry so I cannot see what's happening/left).

PS:  Non listed cookies will NOT be deleted on browser close, but browser startup.


This issue may be duplicate of #564 now if you're referring to an external program.

**Comment by kennethtran93** [comment]
If this issue is ultimately related to CCleaner detection then I'm afraid I'll need to close this issue as irrelevant due to external program outside of the firefox browser.  I'll leave it open for now if you need any further assistance.

**Comment by bobdig** [comment]
I have the same problem, it seems CAD just doesn't work. 

I give an example. On the following site I add two products to the "comparison list".
After closing and restarting FF the comparison is still shown. 

![Clipboard01](https://user-images.githubusercontent.com/46788742/64096369-be50d100-cd61-11e9-8369-d3274fa8e972.jpg)

![2](https://user-images.githubusercontent.com/46788742/64096657-81390e80-cd62-11e9-8ff2-2a6676acd11a.jpg)

![3](https://user-images.githubusercontent.com/46788742/64096666-839b6880-cd62-11e9-8119-5678526d3ca3.PNG)

**Comment by kennethtran93** [comment]
@bobdig Please create a new issue as it is not relevant to the original poster's issue.

In your case you have greylisted all sites but you left the 'keep all cookies' checked as well as 'keep localstorage' checked.  That essentially acts like a whitelist since you're keeping everything.

If you want to keep all cookies until browser restart, then just **clear the checkbox** for 'keep all cookies' and 'keep localstorage'. To keep specific cookies and localstorage forever, use whitelist.  The checkboxes act like what you would like to keep.

**Comment by bobdig** [comment]
It doesn't change anything if I delete this greylist, it doesn't matter. Some time ago it was advised to have such a rule for deleting cookies for open tabs.

**Comment by kennethtran93** [comment]
If you wish then simply uncheck the two checkboxes shown in the site popup (or via the Expression Table in Settings).

I have updated the FAQ to reflect how to remove all non-whitelisted cookies upon restart with the above extra step.

**Comment by bobdig** [comment]
It is not deleting it, pls try for yourself. 

![Clipboard01](https://user-images.githubusercontent.com/46788742/64106430-77220a80-cd78-11e9-83be-ef97f5596921.jpg)

**Comment by kennethtran93** [comment]
ok.  I will check up on this in a bit.  I had a non-English site in another issue that may be similar to yours that I could not reproduce as well.

Are you using any private browsing of some sort for this?

**Comment by bobdig** [comment]
Hi, that would be great. 
Here are my settings, I don't use private browsing. 

![a1](https://user-images.githubusercontent.com/46788742/64230452-326bb000-ceed-11e9-845c-d07472389c00.PNG)

![Capturebb](https://user-images.githubusercontent.com/46788742/64230804-13215280-ceee-11e9-85f5-262ccec37688.PNG)

![a](https://user-images.githubusercontent.com/46788742/64230462-35ff3700-ceed-11e9-8021-6880023d8c18.PNG)

![Captureb](https://user-images.githubusercontent.com/46788742/64230470-3b5c8180-ceed-11e9-86a0-b763b90f3c6d.PNG)

**Comment by kennethtran93** [comment]
@bobdig Sorry for the late reply.  I had noticed that you disabled the cleanup log function, hence it would not show up any logs even after you click manual clean.  I'm not too sure if the cookie list would repopulate automatically after a manual clean.  Did you try reopening the CAD popup after manual clean to see if the cookies were still in use?  I'd suggest enabling the cookie log function so that we can further troubleshoot this.

**Comment by kennethtran93** [comment]
Also I'm not sure if other cookie web extensions may also affect the proper functionality of CAD either.

**Comment by kennethtran93** [comment]
@bobdig is this still an issue for you?  Does the cleanup logs help solve anything?

**Comment by kennethtran93** [comment]
Closing due to stale issue as original author seems to have their issue resolved.  @bobdig please open another issue if it is still ongoing.
