### ISSUE TITLE
Session Cookie Behaviour Unclear

### ISSUE THREAD

**Issue by Integralist** [mrdokenny/Cookie-AutoDelete#569]
## Describe the Bug/Feature

Session cookies potentially breaking expectations when trying to log into bank account.

### Describe the bug

If I log into my bank account and then attempt to click around the interface (or even just refresh the current page) I get immediately sent back to the login page again (even though I was able to login and have also whitelisted the domain).

Looking through the FAQ I noticed a comment about Session cookies being treated differently but reading the issue it linked didn't help to elucidate what should be done in my particular scneario.

The session cookies set by my bank don't have 'session' or any obvious pattern to their name to be able to add those as an additional whitelisting features.

### Your settings 

- OS/version: macOS 10.14.5
- Browser/version: Firefox 68.0.2
- Cookie AutoDelete version: 3.0.2

### Expectation

Ideally a better explanation of why Session cookies might be problematic and how to resolve issues with them.

**Comment by kennethtran93** [comment]
I presume this doesn't happen when CAD is disabled or the autocleanup is disabled as well?

For testing sake what bank site were you using?  For your reference a session cookie isn't when there's the name 'session' in the cookie.

![Cookie Manager - Mozilla Firefox](https://user-images.githubusercontent.com/6724477/64227359-05d97900-ce98-11e9-82dd-370d7cfd3dfa.png)

It is usually set by the site that utilizes the cookie itself, in terms of either having an expiry date set in the future, or none at all (that would imply a session cookie).

Unfortunately because it is a confidential page you're accessing, it will not be easy to troubleshoot as I don't think I would be able to see the source code of that page to detect how cookies are being set through the site.

As a side note, sites like gmail.com need 3rd party cookies, some from google.com, in order for gmail to stay logged in.  Perhaps your bank may have another site/subdomain used?

What other web extensions do you have enabled in Firefox?

**Comment by Integralist** [comment]
> I presume this doesn't happen when CAD is disabled or the autocleanup is disabled as well?

It doesn't happen when using a browser without CAD, correct. As far as 'autocleanup' is concerned, that's only going to trigger once the browser is restarted (according to the docs) so that shouldn't be a problem.

> For your reference a session cookie isn't when there's the name 'session' in the cookie.

Yup. The only reason I mentioned 'session' being in the name of the cookie is because it looked like that was being suggested as a thing to search for in the other GitHub issue the FAQ linked to (hence my confusion).

> For testing sake what bank site were you using?

This also makes it difficult to debug because I'm hesitant to share with the world what bank i use.

> Unfortunately because it is a confidential page you're accessing, it will not be easy to troubleshoot as I don't think I would be able to see the source code of that page to detect how cookies are being set through the site.

Indeed. But here is a breakdown of the cookies I see set once I'm authenticated...

- `.example-bank.org`
- `.secure.example-bank.org`
- `.www.example-bank.org`
- `check2.example-bank.org`
- `secure.example-bank.org`

And here are the patterns I have 'greylisted'...

- `*.example-bank.org`
- `*.secure.example-bank.org`
- `secure.example-bank.org`

**Comment by kennethtran93** [comment]
Just too keep this at the back of my mind, is this still an issue on the latest versions of Firefox?

Also, seeing as you had mentioned those cookies being set while authenticated, what cookies are remaining after the page refreshes/redirected back to login?  Are they also the same cookie values?

I cannot think of a way to reproduce your scenario at this time.   Also for the behaviour of session cookies, you'll need to look at Firefox's documentation on how they treat session cookies.

**Comment by Integralist** [comment]
Feel free to close as I appreciate this isn't going to be easy to reproduce and solve.
