### ISSUE TITLE
clean cookies for the domain of the current tab when it is closed

### ISSUE THREAD

**Issue by mentat6059** [mrdokenny/Cookie-AutoDelete#574]
have a "blacklist" for domains in a tab where cookies are deleted only when that tab is closed

**Comment by sircu** [comment]
Another request for exactly this, please!

**Comment by kennethtran93** [comment]
...so you would like to keep the hidden 3rd party (tracking) cookies that are set via those domains?

**Comment by mentat6059** [comment]
no, l'd like to remove them. Any cookies that are created by the web site in the tab are removed when the tab is closed. For example, a news website sets cookies that allows 4 free articles per month. When the 4th article is reached I can manually remove cookies and get another 4 articles. What would be nice is to be able to specify a domain who's cookies are automatically deleted when a tab for that domain is closed.

**Comment by kennethtran93** [comment]
is this presuming that there are other tabs with that domain still in use?  If not then you can just enable the 'include open tabs' as part of cleaning.

The title is slightly misleading in a sense.

**Comment by mentat6059** [comment]
doesn't the "clean, include open tabs" clean cookies for all open tabs irrespective of the domain of the current tab ?
the title should have been "clean cookies for the domain of the current tab when it is closed"

**Comment by kennethtran93** [comment]
Yes, but at the very least it won't clean domains that are in the grey or white lists.

Unfortunately it is not as easily as listening to when the tab closes (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/onRemoved) as they don't give back the URL/domain.  We would need to keep track of each tab number that has that domain upon load.  This has a side effect that if the browser were to restart, the tab numbers/id may change and that tab would need to be reloaded first so that it would go back into a tracking list again before you close that tab.

In the interim you can just manually clean including open tabs.  it always goes through the grey and white lists before cleaning.

We do not know specifically which 3rd party cookies are set for each tab.  We just look at the overall domains in the cookie jar and go from there.

**Comment by kennethtran93** [comment]
Quick question - does the clean, include open tabs setting option fulfill your needs?  I may close this as that would be the solution to your issue.

**Comment by mentat6059** [comment]
I don't use your add-in anymore using an other add-in to remove cookies
