### ISSUE TITLE
Delay time --> more ways to use?

### ISSUE THREAD

**Issue by Bruce-Bane** [mrdokenny/Cookie-AutoDelete#576]
Hello guys!

Can/if i set a delay time = 1.008.000 s (equivalente to 1 week) on autoclean feature? If so, the cookie would be deleted after 7 days without reentering that page?

There is a way to set an amount of time before each cleaning. For example: Clean all cookies (except whitelist) each 30 days.?

**Comment by kennethtran93** [comment]
You can try testing that on your own.  
As you said above, convert the minutes or days to seconds.  
Due to the size that is used to store that number, it may or may not be feasible.  Most people would like it to be in seconds so that the 3rd party cookie trackers can't extract much information from your history.
