### ISSUE TITLE
Blacklisting sites to force cleanup

### ISSUE THREAD

**Issue by salva-maiorano** [mrdokenny/Cookie-AutoDelete#580]
the current cleanup logic is focus on cleaning all sites, with the exception of sites that are whitelisted
it would be nice to have a domain whitelisted (not cleaning it up), and have only include a subdomain where you want to perform the clean up
eg
```
*.google.com      -> whitelist
*.mail.google.com -> blacklist
```
another particular case is to handle the cleanup of only the sites you select, leaving all the other sites untouched 
```
*             -> whitelist
*.badsite.com -> blacklist
```
ps: great app!

**Comment by kennethtran93** [comment]
This duplicates other issues relating to blacklisting.  I suggest you search up the github issues for features and comment/react to those before creating a new issue/feature..

Closing due to duplicate of #134.  If any of the above details aren't already in that issue, feel free to add additional comments to it.
