### ISSUE TITLE
Something wrong (bug...) at Firefox startup cleaning

### ISSUE THREAD

**Issue by LaurentGrenet** [mrdokenny/Cookie-AutoDelete#581]
Hi,

there is something wrong in cleansing at browser startup, which makes it un-complete.
Let me provide a detailed example :

I connect myself to my personal account on https://www.trainline.fr/
I specify that I have no rule, neither grey nor blank, to this domain, and that all options are checked in CookieAD settings, inc Local Storage cleansing

If I close the tab, and/or inside this tab, I switch to another domain, and that, after getting the pop-up stating that cookies have been deleted, I go back to the same site, it appears that cleaning has been correctly done, since I'm no more connected to my personal account.

But if I do NOT close the tab and do NOT switch inside the tab to another domain, but **rather** close Firefox itself, when I restart Firefox, (and after waiting for cleansing pop-up) it appears that **cleansing is not correctly done**, since if I go back to the site, I'm already connected to my personal account.

I have checked with "Cookie Manager" : after pop-up stating that cleansing has been done, in both cases, either in the first case (ie. without closing firefox itself) or in the second (ie. at browser restart), in both cases, no more cookie remain relative to this domain.

So I suspect that problem comes from an incorrect cleansing of Local storage.

This is quite similar to issue #345 I raised on Jan 30th 2018, but that has been fixed for long, and seems to be again there.... apparently for different cause, but with same result....

- OS/version: W7 Pro 64 
- Browser/version: Ffx 69.0.3
- Cookie AutoDelete version: 3.0.2

**Comment by mexson** [comment]
From my understanding, it could be because you enabled "restore previous session" in FF settings.

In this case, FF restarts, Cookie AutoDelete deletes all cookies except those which belongs to openned tabs, and since yourtrainline.fr is openned, cookies are not cleared.

Did you check "Clean Cookies from Open Tabs on StartUp" in Cookies AutoDelete ?

**Comment by LaurentGrenet** [comment]
Hi,
no, of course, I do NOT enable "Restore previous session". If I did it, I obviously wouldn't be surprised by the result, and I wouldn't raise the issue....

And for sure, I have checked "Clean Cookies from Open Tabs on StartUp" in Cookies AutoDelete....

Last, but not least, I'm now 100% sure there is something wrong with cleansing of local storage : The best proof : I just checked with FF Options, and I can see I have a lot and a lot of "Local data" for sites without  any relative rule in CAD. Since no rule, neither blank list, nor grey list, these data should have been removed by CAD....
To be very specific, when I write "a lot and a lot", currently there are "local data" for 24 different sites. 
Some of them are here (according to what says FF) for a quite long time : several days, weeks or even months for some of them.
These most likely correspond to sites I had a tab open on it when I closed FF, and I do not have visited since.
I can remove them manually, thanks to FF Options, but CAD should have cleansed them automatically

**Comment by SpaceClicker** [comment]
It's my understanding that what you are seeing is probably IndexedDB data, not localstorage (I believe both IndexedDB and localstorage are included in the "Storage" number.)  IndexedDB can not be cleared on an individual domain basis by the API, so CAD cannot clear it.

Perhaps there should be an option to clear ALL IndexedDB (if the API supports it) but that might break certain websites.

**Comment by LaurentGrenet** [comment]
I'm afraid your understanding is wrong....

I just did a test (you can easily reproduce) with the website https://www.lemonde.fr/
After surfing this website, then closing FF, then reopening FF, and waiting for cleansing by CAD (and getting a message : cookies deleted for lemonde.fr), it remains data for the website, according to FF options;
But if we go a little bit deeper in the details, using Tool/Web development/Storage inspector, we can see that Indexed DB is empty.... while Local storage is not....

And please do not forget the initial startpoint of this thread : Bug I mention with trainline.fr is 100% due to a non-cleansing of Local storage. Nothing relative to IndexDB....

**Comment by SpaceClicker** [comment]
Do that same test with another site that does not set localstorage and you can see the same thing.

For instance I went to www.ghacks.net and looked at all storage using storage inspector.  It only sets a single cookie, no localstorage, indexDB, etc.

Then I closed the tab for that site and CAD indicated it deleted the cookies, which it did, but looking in about:preferences#privacy, Manage Data it still says there is 64.0 KB of storage for www.ghacks.net (and 0 Cookies).

Since localstorage wasn't set for this site, that 64KB is most likely not localstorage.  I have no idea what it is, but unlikely to be localstorage, and I assume the same for the trainline.fr site.

One problem is that looking at the storage with Firefox's "storage inspector" requires you to visit the web page, so you can't see what is set for a site unless you are currently visiting it (which sets localstorage) so it's not possible to see what was deleted automatically by CAD using this method.

However, what you CAN do is visit the site, view "storage inspector" and see what is set (cookies and localstorage for the tainline.fr site) and then manually tell CAD to "Clear localstorage for this domain".  For me this works fine and "storage inspector" then shows that localstorage is cleared.  You can then tell CAD to "Clear cookies for this domain" and you will see that the cookies are gone in "storage inspector" (note that you tell CAD to clear these things from the  "Clean" menu on the CAD menu.
So while this doesn't prove that CAD is automatically clearing these things, it does prove that CAD is able to clear these things, and most likely it is doing so automatically.

**Comment by SpaceClicker** [comment]
UPDATE:  I reread your original post and see you are referring to what happens after you restart the browser.  So even though there is still 64KB storage, it may have nothing to do with your particular problem, but it is still a curiosity.

I did a test with a restart of the browser, and you are right.  If you have a tab open to www.trainline,fr when you exit the browser and the restart the browser, localstorage will not have been deleted.
But I have "Restore previous session" enabled, so perhaps this is expected?  Although it kind of defeats the purpose of the option if it doesn't work with that option enabled.

**Comment by LaurentGrenet** [comment]
I give you the point about these 64K. What are these ? 
Most of the sites that were showing data in about:preferences#privacy were showing a lot more than 64K : in term of MegaBytes for some of them.... So my asumption is now that it probably includes also "classic cache" : And I just had a look using MZCacheView (from NirSoft.net), and it seems to match...

**BUT THE ISSUE IS NOT THERE.**

Pls have a look on my initial post.
For the website Trainline.fr, it is quite important to have LocalStorage cleansed, since it is there that the site stores login credentials, and NOT thanks to a cookie....

And what I raise is the fact that if you close all the tabs relative to a site, or re-use these tabs for another site, at CAD cleansing, LocalStorage is cleansed (and in particular login credentials for Trainline.fr are removed) as well as cookies. This is OK

BUT if you shut down FireFox  **WHILE TABS ARE OPEN** (BTW this is always the case : when you close FF, there always still remain at east one or more open tabs...), when reopening FF (with "Restore previous session" **disabled**), initial cleasing done by CAD removes remaining cookies **BUT DO NOT REMOVE** corresponding LocalStorage. And **THIS is the BUG**.
And in the particular case of TrainLine.fr, it makes you already logged in....

**Comment by SpaceClicker** [comment]
Yes, if you look at the post before yours you will see that I realized I misunderstood the problem.

It does look like there may be a problem with it clearing localstorage when a tab is open and you close and restart the browser.

It should clear localstorage for all sites that are not in the whitelist when the browser starts.

Perhaps the problem is related to how CAD knows what domains to clear.  It can iterate the cookies and delete those on a per-domain basis, but it cannot iterate the localstorage, so the best it can do is blindly clear localstoarge for all sites that have cookies and are not in the whitelist.

I am assuming this is why CAD sets a special cookie for sites that don't set any cookies themselves, so that this function will work (cookieForLocalstorageCleanup).

I don't know if session restore also restores cookies, but since you are not using it is is probably not relevant.

I noticed that trainline.fr sets 2 cookies in the ".trainline.fr" domain that expire +2 hours from the current time.  At first I thought maybe it might be related to the cookies being expired (and removed) when Firefox starts, but that does not appear to be the case.

Another thing I noticed is that while the cookies have the domain ".trainline.fr" associated with them, localstorage has "www.trainline.fr".  I don't know if the problem could be as simple as CAD trying to clear ".trainline.fr" in localstorage when it should be clearing "www.trainline.fr".

I'm just guessing here and should probably just let someone with more knowledge answer. :-)

**Comment by LaurentGrenet** [comment]
OK, this time we agree ;-)

And yes, your asumption is OK : It's for this reason that CAD sets a special cookie for sites that don't set any cookies themselves.
And if you have a look at my initial post, you can see I'm refering the issue #345 : Actually, the bug  at this time was that this special cookie was set as a "session cookie", and then was no more there at FF restart....

And since there is potentially an issue if the cookies set by the WebSite have an expiration date, maybe it would be better that CAD sets this special cookie IN ANY CASE, even if the websites sets its own cookies. Maybe this would solve also the issue I raised ?

**Comment by SpaceClicker** [comment]
I don't know enough about how the APIs work or how Firefox works.

When a key expires, I'm not sure when it is deleted (I still see expired cookies even after a restart), but I also don't know if CAD would still see them for purposed of clearing localstorage (assuming the key expired between then the browser last shutdown and when it was restarted).

I also don't know if clearing the localstorage for domain .trainline.fr would also clear the localstorage for www.trainline.fr.

According to [this](https://stackoverflow.com/questions/4026479/use-localstorage-across-subdomains) thread it seems to indicate that they would be treated as separate domains, which may mean that clearing one does not clear the other.  Although that thread is from about 10 years ago, so not sure if anything has changed.

But if they're treated separately (unlike cookies) then that would explain why they are not getting deleted.  However, why does it work when you close the tab?  I can only assume it is keeping better track on what domains have been visited while the addon is running (perhaps in memory) and only using the cookies when it needs to delete localstorage upon browser start.

As long as CAD is able to know what domains have localstorage (or at least what domain were visited in the session), it should be able to set the correct cookies with the correct domains to allow it to clear localstorage on startup.

**Comment by LaurentGrenet** [comment]
I just did a test, which do not provide a solution, but maybe could help someone to **understand** where exactly the problem stands.

I have created a White list rule for domain trainline.fr, but unchecking the box "Keep local memory" and unchecking also "Keep cookies". 
Such a rule asking to do not keep anything should produce the same result as a lack of rule on the domain....
But actuall, it **DOES NOT**. With this "strange" rule, the bug mentioned is no more there ! And local storage for trainline is deleted by CAD, **even if it is at FF startup**.

I then imagine that with an even more global "strange" rule, ie.
- domain *
- do NOT keep local storage
- do NOT keep cookies
this could avoid the bug, whatever the website.
But unfortunately, this doesn't work. With this "global" strange rule, the bug is still there, and local storage is not deleted by CAD when it is at FF startup....

**Comment by SpaceClicker** [comment]
Very interesting find, I'm sure that will help to track down the root cause of the problem.

**Comment by kennethtran93** [comment]
@SpaceClicker 
> Another thing I noticed is that while the cookies have the domain ".trainline.fr" associated with them, localstorage has "www.trainline.fr". I don't know if the problem could be as simple as CAD trying to clear ".trainline.fr" in localstorage when it should be clearing "www.trainline.fr".

You are actually correct.  My findings today indicate that the subdomain must be included (including the www if so).

**Comment by LaurentGrenet** [comment]
Hi Kenneth,

contrary to what you say, this bug is NOT AT ALL fixed ! I would say it's even worse now than before.
If you have a look at bug's description (in my 1st post of this thread), you can see that bug (ie. lack of cleansing of storage relative to the trainline.fr domain) occured "only" if I closed Firefox without closing first the tab opened on the domain, nor switching this tab to another domain.

Now, with your "fix", local data of Trainline.fr are NEVER cleansed ! Whatever the way you close tab or Firefox.... Once you logged into Trainline, you are never logged out except if you choose to explicitely log out.
And nevertheless, I get the pop-up and the record of cleansing of cookies.
This means that, at least with this website, local data are NEVER cleansed.... while
- my general settings require for local data cleansing
- absolutely no rule is there relative to this domain....

At least, before the "fix", the bug was active only in some cases. Now, it is always active.
And I'm sorry to say thjat it makes your extension 100% useless....

Hopefully, there is not the same issue with "Forget me not" extension....
I'm sad, because I expected to go back with CAD when the bug I mentioned would be fixed...
"On the paper", CAD is better than "Forget me not" on containers management.
But only "on the paper", since actually, CAD do not work at all.....

**Comment by kennethtran93** [comment]
My apologies there.  I'm trying to push out a version with more debug lines so that it can be more helpful.  There's another localstorage bug in the meantime as well so I'll try to get them fixed as soon as I can.

**Comment by kennethtran93** [comment]
At risk of repeating myself, see PR #713 for a possible build that may fix this.
