### ISSUE TITLE
Permissions too open

### ISSUE THREAD

**Issue by BikeTech** [mrdokenny/Cookie-AutoDelete#582]
The FAQ lists these reasons for requiring such open permissions:

> What are the Permissions used for?
> 
>     Access your data for all websites: CAD requests this to delete cookies for all sites
>     Clear recent browsing history, cookies and related data: Ability to delete Localstorage.

However, it seems like the latter should cover the former (which is my primary concern). Is there a possibility to remove the requirement to access data for all websites?

**Comment by kennethtran93** [comment]
To clarify the permissions a bit:

The first message is in regards to the `Host Permissions`.  It shows up due to (https://extensionworkshop.com/documentation/develop/request-the-right-permissions/#advised-permissions), notably:
![Request the right permissions  Extension Workshop - Mozilla Firefox](https://user-images.githubusercontent.com/6724477/67629958-39070b80-f83c-11e9-8d65-12021fa65403.png)

The ability to remove third-party / non-whitelisted cookies require us to look at ALL the cookies in the cookie jar...to which I reference the prerequisites below

> To use this API, you need to include the "cookies" API permission in your manifest.json file, as well as **host permissions** for the sites whose cookies you need to access

(https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies#Permissions) 

This means that to access the cookies API and remove third-party cookies, we need to know beforehand all the 3rd-party URLs that the user has no idea of.  Because of that we need to include the ALL URLS permission in order to see all cookies in the jar.

--

In regards to why the second permission isn't enough:

The second permission gives us the `browsingData` API.  While it does have cookie removal, it requires us to know beforehand which cookies to delete (either by time or specific hostnames).  

This refers to the function `browsingData.removeCookies` function which takes in the cookies to delete either by time (which would remove all cookies regardless of whitelist/greylist), and/or by hostname (to which we won't know if there were any third-party cookies set until we query the cookies database).  We only keep the URLs that were specified by the user as the ones to keep, to the above function is completely useless to our extension in that regards.

Hope this helps.

**Comment by kennethtran93** [comment]
I'll leave this issue open for discussion for a bit, but long story short there is no other way for us to do this.

**Comment by BikeTech** [comment]
Thank you for taking the time to offer a detailed explanation. The above is useful information and helps me feel more informed when using Cookie-AutoDelete.

**Comment by kennethtran93** [comment]
I'll close this then and reference my response in the FAQ.
