### ISSUE TITLE
Installation instructions needed

### ISSUE THREAD

**Issue by visualcurrent** [mrdokenny/Cookie-AutoDelete#592]
All documentation and FAQs assume extension is already installed. I don't see any documentation on basic installation.

Obviously this page is where one would normally go to install.
https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/
But the extension is broken there.
> Installation aborted because the add-on appears to be corrupt.
> This extension isn’t monitored by Mozilla. Make sure you trust the extension before you install it.

Often extensions can be downloaded independently and dragged into Firefox to install. For people that don't know how to build code, it would be nice if there was mention of some location to find a download like this in the FAQ or documentation.

**Comment by kennethtran93** [comment]
As this extension (and its third-party libraries) haven't been updated to their most recent versions, that's probably why Mozilla silently claims that it is corrupt/not recommended despite hosting it via their site.

Otherwise, there's the github releases page which also has those signed addons:  https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/releases.  I can update the FAQ / documentation within Github.

**Comment by visualcurrent** [comment]
Ahhh! There it is!

I don't know why I didn't see that. I appreciate the link

All the best!

**Comment by kennethtran93** [comment]
wiki is also updated.  Closing this issue as resolved now.
