### ISSUE TITLE
Cookie-AutoDelete Auto Resets

### ISSUE THREAD

**Issue by CBill100** [mrdokenny/Cookie-AutoDelete#603]
Cookie-AutoDelete on Firefox on 2 laptops. Same setup all around on both.

Adjusted CAD settings enabling Auto-Clean, etc. . However, on one laptop CAD resets each day to 'Auto- Clean Disabled.

No idea why it resets and only on one of two laptops..

Thanks

**Comment by kennethtran93** [comment]
If I recall correctly, this may be due to a corrupted Firefox file on one of those laptops as similar issues were resolved through either reinstalling firefox or external programs.  Are you running any external cleaning programs like CCleaner on the affected laptop - that may actually have an effect depending on its cleanup actions.  Aside from the autoclean disabled, is there any other settings being reset on the affected laptop?

**Comment by kennethtran93** [comment]
@CBill100 any updates on this?  I believe we do use a bit of Firefox's storage for webextensions including the settings.

**Comment by kennethtran93** [comment]
Closing support issue due to staleness.

**Comment by CBill100** [comment]
Sorry never saw your reply. Yes, I use CCleaner. But it is used on both laptops but only affects one.
Is there a way to adjust this in CCleaner settings?
Thanks.

**Comment by kennethtran93** [comment]
I'm not sure - you'll need to check your settings in each CCleaner.

You may need to try to reinstall Firefox on the affected machine.
