### ISSUE TITLE
Implement blacklist [clean cookies for specific domains after every page load]

### ISSUE THREAD

**Issue by kekukui** [mrdokenny/Cookie-AutoDelete#604]
For sites which limit the number of page views, a new feature is needed which will clean the cookies for that domain each time a page is loaded.

I dont know how browser extensions interface with the cookies API, but I wonder if it might be possible to accept cookies for the domain and then immediately rename them or pipe them to 'null' instead of writing to disk.

**Comment by kennethtran93** [comment]
I think you're asking for a Blacklist feature where the cookie will be destroyed upon creation.  There should be another feature request open for that already. (#134).

How the cookie is accepted goes through the browser first.  We deal with cookies after it gets accepted and written to disk (or however the browser keeps the cookies).

The alternate solution for now is to close all tabs for that site, wait for the auto cleanup timer, then open that site again.

Closing due to duplicate.  If you think this should be reopened as a separate feature request, please provide additional details.
