### ISSUE TITLE
[SUPPORT]  Is there a noob's guide to what this actually does (from a user experience perspective) anywhere?

### ISSUE THREAD

**Issue by loki-zen** [mrdokenny/Cookie-AutoDelete#647]
Hi; I'm on here because I couldn't find this info or any other way of contacting the developers. 

I'm interested in this add-on because it's firefox-approved and sounds good, but I'm struggling to find a low/no-context explanation of what it does. 

Specifically, I think my issue is that I don't know what is meant by 'cookies that aren't being used.' 

If what this means is that it will delete cookies that end up on my computer that don't benefit me, and are only there because a combination of dark patterns and my exhausted ADD brain means that I can't always track down or work out exactly what I need to click to make that not happen, then that sounds great.

But (see aforementioned exhausted ADD brain) I am less interested in something that will go around deleting time-saving cookies (I think it's cookies?) that do things like 'mean I don't have to type in my username every time I want to log in to a site'. 

So what I'm looking for, I guess, is how getting this add-on would actually affect my experience as a web user. If there's a simple way to configure it to do the former thing but not the latter, that would be even better.

**Comment by kennethtran93** [comment]
> Specifically, I think my issue is that I don't know what is meant by 'cookies that aren't being used.'

Might need to reword that on our end - what we mean is that cookies that you don't want to keep or use - those will get deleted as long as you don't put that domain under whitelist or greylist.

> If what this means is that it will delete cookies that end up on my computer that don't benefit me, and are only there because a combination of dark patterns and my exhausted ADD brain means that I can't always track down or work out exactly what I need to click to make that not happen, then that sounds great.

Unfortunately it not an 'install and forget' extension as this require a bit of configuration.  It takes a bit of time to get it configured from scratch (the domains you want to keep initially).  You'll need to configure it yourself, either by supplying expressions to import (see FAQ) or by manually going to each site you want to use, then going into the popup by clicking on the icon and clicking whitelist (never delete) or greylist (remove after browser restart) depending on whether you want it only for that domain only, subdomain+domain, or any subdomains of that domain.  When you first install this, it won't do anything yet (autocleaning is disabled) such that you can manually configure the domains to keep.  

There are **no** domains configured at start. That means that if you were to enable auto cleaning off the bat, then most cookies will be erased, except the domains in open tabs unless that is enabled too.  (Before this, I'd highly recommend you to go into the extension settings and enable 'Cleanup log and counter' as that will allow you to 'undo' the cookies that this web extenion deleted, either manually clicking 'clean' in the popup or when the automatic cleanup is enabled.  The cleanup logs will also show you the domains and cookies for that domain that were removed.  From the cleanup log in settings, you can copy the domain you wish to keep, add it into the expressions section, then undo the cleanup and then hit the cleanup button again.)


> But (see aforementioned exhausted ADD brain) I am less interested in something that will go around deleting time-saving cookies (I think it's cookies?) that do things like 'mean I don't have to type in my username every time I want to log in to a site'.

If you're just looking for something what will automatically input your username and password, Firefox has its own credential password manager that should suffice for you. (The 'remember username/password for this site' messages that Firefox will show you if you have 'remember passwords' enabled in Firefox preferences).  If you are looking to keep cookies because you are already logged in to those sites, then have that site whitelisted either through the popup or settings.

> So what I'm looking for, I guess, is how getting this add-on would actually affect my experience as a web user. If there's a simple way to configure it to do the former thing but not the latter, that would be even better.

As a recap, this web extension won't do any cleanup upon install.  This gives you a chance to visit each site you want to keep cookies for and whitelist them.  The simple way of configuring this is to go directly to each site, then click on the extension icon, then click the whitelist for either that domain or include all subdomains (the line with the `*.subdomain.domain.com`).   Once you think you have all the ones whitelisted, then you can enable automatic cleaning (as above, should enable cleanup log and counter just in case there's cookies/domains you have missed so that you can undo what the extension did.)

Let me know if this helps.  It's a bit worded but it should explain what you had asked for.

**Comment by loki-zen** [comment]
That's helpful, thank you. I do have the password saving enabled in firefox
and am getting a program/extension for that - I just hadn't thought
through, I think, how that would naturally remove the need to also have
cookies saving login info. But you gotta whitelist if you want to be
already logged in, it sounds like.

Thanks, anyway - I understand how and why I would use this now. :)
