### ISSUE TITLE
[FEATURE REQUEST]  Add option to disable new tab popup on extension update

### ISSUE THREAD

**Issue by ghost** [mrdokenny/Cookie-AutoDelete#661]
**Is your feature request related to a problem? Please describe.**

The new 3.1.1 release mentions "Added: The welcome page with release notes will now open up whenever a new version is released."

**Describe the solution you'd like**

Please include an option to disable the pop-up. If I wish to view release notes I will go read the release notes. :)

**Describe alternatives you've considered**

I will consider ditching CAD as I don't wish for my software to constantly pop things up like I'm on a 90s Windows PC.

**Comment by Exagone313** [comment]
I'm grateful I'm the only one coming for that issue.

**Comment by rhizome** [comment]
I'm sure we're all looking forward to this rudeness during a video job interview or something equally unimportant.

**Comment by ghost** [comment]
To the maintainers, this is not to throw shade on the excellent work that has been put into this wonderful project - we just feel that there's a time and place for pop-ups, and new release are not that :)

**Comment by petarb** [comment]
Friends and family using CAD will be very confused by this.

**Comment by kennethtran93** [comment]
My apologies everyone - I had thought that would help but I guess it didn't receive a welcome reception - I'm still pretty new at this so it'll be a bumpy road at this time.  v3.1.2 will either have the option to enable release note popups or I'll just remove that one line.

**Comment by ssokolow** [comment]
I was about to leave a review with this knocking a whole star off my rating before I thought to come here and check for open issues.

I have a popup blocker... I don't need my extensions being a source of popups.

**Comment by petarb** [comment]
I think this should be opt-in, not opt-out.

Thanks to this change, I can opt-out. But others can't (because they don't maintain their setup and are unaware of the extension) and won't (because it will confuse them and they'll click it away) and therefore will get the pop-up tab on each update.

Also I don't think that extensions should do this on updates unless something needs immediate attention.

So can I motivate you to reconsider?

**Comment by kennethtran93** [comment]
Fair Point.  I'll revise it so that it would only show up the first time it is installed, and for those who opt in to it.  At a later stage, I may use the update popup for some attention regardless of opt in/out.

The only bright side so far is that people are actually leaving a review (or just stars) on the Firefox side as the amount of reviews have jumped up since.  Firefox apparently maps reviews to each version, as when I disable previous versions their formula excludes those ratings.
