### ISSUE TITLE
[BUG] v 3.3.0 - Oversized UI in Firefox

### ISSUE THREAD

**Issue by Acid-Crash** [mrdokenny/Cookie-AutoDelete#736]
**Describe the bug**
Update 3.3.0 made UI oversized on Firefox. Because of this the amount of scrolling increased drastically. Also, this is noticeable when compared to other browser content and other extension tooltips. Previous version had more practical and pleasant Font size, margins and paddings

**To Reproduce**

1. Open either popUp or settings
2. Compare UI to other browser content.

**Expected behavior**

The extension UI (font-size, margins and paddings) should be more consistent with the other browser content.

**Screenshots**
![изображение](https://user-images.githubusercontent.com/32600318/82426015-fc2c8b80-9a8f-11ea-912a-23bfbb19bd1c.png)

![изображение](https://user-images.githubusercontent.com/32600318/82426154-2aaa6680-9a90-11ea-97dd-8f6ad28a2b20.png)

**Your System Info (please complete the following information):**

 - OS: Windows 10x64, 100DPI, default theme
 - Browser Info: Firefox 76.0.1
 - CookieAutoDelete Version: 3.3.0

**Additional context**

As stated before, previous version of the extension (3.2.0) did not suffer from this issue.
See more screenshots comparisons
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/399#issuecomment-625166712

**Comment by mondocane80** [comment]
On my 14" laptop, this covers almost 35% of my screen.  Old menu size was **much** better.

**Comment by kennethtran93** [comment]
Others have asked the reason why the popup text wasn't selectable - it was because the browser_style that firefox added in prevented that.

For the most part the css work I did was the color of icons in popup expressions and the settings page.  I'll need to figure out a way to allow users to set sizing, unless somebody knows and are willing to assist with the fix.

**Comment by Acid-Crash** [comment]
@kennethtran93 
I am not sure how the 'popUp selectable' issue is related to the increased font size...
For my personal use I've managed to make font back to the 3.2.0 version by overwriting this style via userContent.css
This approach is considered as 'hacky-way' so I am not sure how to restore styles in the proper way.
Still, hope this will help you...
```css
:root {font:12px menu !important;}
```

This seems to restore original Font sizes for the popUp, however Settings page Fonts gets bit to small.


Another this that I used is this (for reducing margins for the checkbox-styled options)
 ```css
.form-group {margin-bottom: auto !important;}
```

**Comment by kennethtran93** [comment]
@Acid-Crash It was because of https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Browser_styles.  When it was used previously, the browser itself added additional CSS on top of the extension's CSS, which may have modified the font size through there.

Also the margin-bottom was there for touch-devices as this extension would also work on Firefox Android.  I'm going to need to create more option in regards to CSS styling for mobile/touchscreen usage vs regular mouse/keyboard.

**Comment by kennethtran93** [comment]
I'll shrink `form-group` to half of the current one as it was initially set by bootstrap.

**Comment by kennethtran93** [comment]
Per bootstrap's default, 1rem = browser-provided default of 16px.

I'm going to override it though a global css
```css
html { font-size: 14px; }
```

**Comment by kennethtran93** [comment]
Mentioning Issue #598 as this is applies to both browsers.  Most likely adding the above will resolve the issue in Chrome as well.

I'm going to make an option to enlarge/shrink the size so it will cover more people's preferences.

**Comment by Acid-Crash** [comment]
> I'm going to make an option to enlarge/shrink the size so it will cover more people's preferences.

Yes this would be a great idea.
An option that allows to set it up from a predefined range (for example from 10 to 24) or the possibility to set it up manually

**Comment by kennethtran93** [comment]
update: Instead of global css, I'm going to use javascript for updating the font size via     
```js
document.documentElement.style.fontSize = `${this.props.state.settings.sizePopup.value as number || 16}px`;
```

This allows flexibility through settings, and to preserve the previous default browser setting of 16px if no setting is found (as a backup since the setting should always be there unless it somehow got set to a weird value).

If you haven't noticed, there will be two additional setting value - one for the settings page, and one for the popup.  More flexibility!.

**Comment by kennethtran93** [comment]
Try this alpha - https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/releases/tag/v3.3.1-alpha in a fresh/blank profile

**Comment by Acid-Crash** [comment]
@kennethtran93 
Hi, I have tested alpha (Firefox) and it seems to me working ok.
