### ISSUE TITLE
[FEATURE REQUEST]  Clean all cookies per each new tab

### ISSUE THREAD

**Issue by oberstet** [mrdokenny/Cookie-AutoDelete#752]
**Is your feature request related to a problem? Please describe.**

Some site only allow N articles to be read. To work around this, I have to restart the browser, so auto-cleaning of cookies kicks in. This is slower than just opening a new tab.

**Describe the solution you'd like**

Upon enabling this new option, when a new tab is opened, this tab will start from a completely empty cookie/localstore.

So say I'm on a site limited like described, I would just right-click and open in new tab another article on that site. the site will ask me again to accept their cookies, which I am happy to do, since it'll be deleted automatically after reading the article and closing the tab. So it's useless for them to identify me anyways.

**Describe alternatives you've considered**

none

**Additional context**

**Comment by kennethtran93** [comment]
The only issue I see with this is that the cookies may not be cleared in time when the page loads.
I also think this is site specific and a blacklist would be better control for this...once implemented.

**Comment by kennethtran93** [comment]
> Upon enabling this new option, when a new tab is opened, this tab will start from a completely empty cookie/localstore.

In the meantime, you may be better off using a webextension that creates temporary containers so that those tabs always start with a fresh / no cookie state.

Unfortunately cleaning all cookies for each new tab is not feasible enough due to implications with other open tabs/containers.  Therefore I'm closing this issue in favor of the blacklist feature request #134.
