### ISSUE TITLE
[FEATURE REQUEST]  An better size for the elements in the UI.

### ISSUE THREAD

**Issue by Loughty** [mrdokenny/Cookie-AutoDelete#768]
**Is your feature request related to a problem? Please describe.**

Everything it's too big, that could be comfy for those who uses on touch screen, but on a PC it's better a normal or a tiny size.

**Describe the solution you'd like**

Maybe and option to change the size for fonts and the icons, or even to hide some of the elements that you don't use or don't need.

**Describe alternatives you've considered**

An alternative could be create _something_ to detect your resolution or your scaling preferences and only put that big icons and text only when it's necessary.

**Additional context**

Here some captures for comparing Cookie-AD's UI with other extensions.

![captura](https://user-images.githubusercontent.com/52808915/84591685-7097e780-ae0e-11ea-858c-2dc5ed46d23f.png)
![captura](https://user-images.githubusercontent.com/52808915/84591725-af2da200-ae0e-11ea-91d5-d6acd86f2046.png)
![captura](https://user-images.githubusercontent.com/52808915/84591753-e2703100-ae0e-11ea-8022-33ed9751e94d.png)

**Comment by kennethtran93** [comment]
Go into settings. You'll see option to control the sizes of both the popup and settings font sizes. This was added recently. Had you enabled show popup on new versions then it would have been made known to you via release notes.

**Comment by Marek33** [comment]
@kennethtran93  I don't think that we need to have something to detect the screen size, but an option to make the fonts and icons smaller would be nice. Personally, I would like to see the option to be able to see the whole window like with the 3.2.0 version, which had its text smaller. Now it hardly, shows the list of all deleted cookies on the whole window screen, unless I make the window size smaller, but the fonts and images are smaller.

Plus, for some odd reason, on Firefox platforms, it was quite small, but I prefer it, over the bigger window on the Chromium platforms.

**The new settings menu looks nice, but I would like to know, how to remove that grey moving bar on the right (can't remember, how it's called). The reason is, that the text is either too small, or the window is too big.**

_And why does the version number say: 3.999.999?_

**Comment by kennethtran93** [comment]
> @kennethtran93 I don't think that we need to have something to detect the screen size, but an option to make the fonts and icons smaller would be nice. Personally, I would like to see the option to be able to see the whole window like with the 3.2.0 version, which had its text smaller. Now it hardly, shows the list of all deleted cookies on the whole window screen, unless I make the window size smaller, but the fonts and images are smaller.

Font size setting is available in latest 3.3.1 if you haven't caught on already. 

> 
> Plus, for some odd reason, on Firefox platforms, it was quite small, but I prefer it, over the bigger window on the Chromium platforms.

Previously it was because the browser default global font size was 16px. Now it can be set accordingly (font size should scale the font and button sizes accordingly) 

> **The new settings menu looks nice, but I would like to know, how to remove that grey moving bar on the right (can't remember, how it's called). The reason is, that the text is either too small, or the window is too big.**

The grey bar on the right? Isn't that a scrolling thing? Usually only shows if there is more content below. 

> _And why does the version number say: 3.999.999?_

That is a Dev build you may have installed. I do that so I don't have to tweak the number when sending out test Dev builds. The official builds will have the release version adjusted accordingly.

**Comment by Marek33** [comment]
I haven't seen it there, only the _Size of Popup (in px) and Size of Setting Pages (in px)_, which doesn't change the window, how it used to be before.

I understand, and I do have the **3.2.0** on Firefox, because of that.

Exactly! That scrolling bar, which was not in the Firefox, even if I had a lot of cookies deleted. It would only show, if I would click on the cookies, which is as it should be.

Yes, it's a dev build, and thanks for the info!

**Comment by kennethtran93** [comment]
> I haven't seen it there, only the _Size of Popup (in px) and Size of Setting Pages (in px)_, which doesn't change the window, how it used to be before.

Those are the two I mentioned. The min window width was a necessary thing in Chrome (otherwise the popup window doesn't show up properly) so I had to look at each font size and attempt to set min-width to just a little before the actual width of everything, based off of the tests I've done in Firefox Dev Edition.   I had removed the browser css to allow the selection of texts in popup, which made the window sizing fall in line to what people on Chrome were experiencing. 

> I understand, and I do have the **3.2.0** on Firefox, because of that.



> Exactly! That scrolling bar, which was not in the Firefox, even if I had a lot of cookies deleted. It would only show, if I would click on the cookies, which is as it should be.

I'll take a look in the future, but will not be done in the upcoming version.

**Comment by kennethtran93** [comment]
Also know that support will only be given  for the latest release.

**Comment by Marek33** [comment]
I was afraid, that you would say that. The Firefox style of that older version was my favorite, and it had no issues, so I kept using it, since I have seen the new popup window on the Brave, and I didn't much like it.

That's good to hear, and I hope that you will add that!

No problem, and there are no issues with anything for me, so no problem. When they would be issued, I would first upgrade, and then see if its fixed (I can upgrade it, thought the sandbox, and see, if it was fixed or not).

**Comment by kennethtran93** [comment]
Did you try font size 12?  The window sizing may just be about the same as previous versions.

**Comment by kennethtran93** [comment]
@Marek33 can you send me a screenshot of what you are referring to?

From my end it looks fine...  In addition, the overflow css is set to `auto` already so it shouldn't appear unless there's too much content.
![Screenshot_20200615_112524](https://user-images.githubusercontent.com/6724477/84693206-0198bc80-aefc-11ea-9a1d-e736a41b87ef.png)

![Screenshot_20200615_112827](https://user-images.githubusercontent.com/6724477/84693331-2d1ba700-aefc-11ea-823a-da6ea77b029f.png)
![Screenshot_20200615_113255](https://user-images.githubusercontent.com/6724477/84693341-30169780-aefc-11ea-9c74-16d38906303b.png)

**Comment by Marek33** [comment]
@kennethtran93  I think I did, since I tried a lot of combinations, but that has fixed it, in both browser versions. The popup window, is almost the same, except the icons are a bit closer to another, and also the text is a bit smaller in the new version.

Also, some cookies, which I **get back** from the older versions on the Iridium and Ungoogled, does have this error: **Secure-3PSID**, even on the latest version, and dev build as well. I haven't started a new issue, since I know those browsers are not supported (, but hopefully will be), though, since they are way more private than the Google Chrome, I use them.

**Comment by kennethtran93** [comment]
> @kennethtran93 I think I did, since I tried a lot of combinations, but that has fixed it, in both browser versions. The popup window, is almost the same, except the icons are a bit closer to another, and also the text is a bit smaller in the new version.

Good to hear (though nothing has changed on my end :D).  I'll leave the icon spacing as is.  I can't be fixing spacing that often when the font size is user controlled.  As for the text...that's the font size as well.


> Also, some cookies, which I **get back** from the older versions on the Iridium and Ungoogled, does have this error: **Secure-3PSID**, even on the latest version, and dev build as well. I haven't started a new issue, since I know those browsers are not supported (, but hopefully will be), though, since they are way more private than the Google Chrome, I use them.

That's a cookie name you've given rather than the error that was received?  enabling debug log may be of use if it can be replicated.

**Comment by Marek33** [comment]
I understand, and that's not a problem.

No, that is a type of error, which I get: **Failed to parse or set a cookie named: Secure-3PSID**

**Comment by kennethtran93** [comment]
I think you brought up a bug.  I've referenced it in a new issue.

Here's some background info:

Presuming that your cookie name is supposed to be prefixed with two underscores `__` as well.

https://googlechrome.github.io/samples/cookie-prefixes/ -or -
https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#Cookie_prefixes

in regards to cookies starting with `__Secure-` or `__Host-` is something we should probably check for and code accordingly.  At this time, according to the walk-through of the code in question, it seems that when 'undoing' the cleared cookies, we didn't include `domain` and `secure` fields when we probably should've include everything that the cookie had.  Your cookie, because we didn't set the `secure` parameter to `true`, by MDN's doc, it is set to `false` by default.

**Comment by Marek33** [comment]
I haven't yet, seen it, on the Firefox, so I wouldn't start an issue for it. Though, it did happen on both, Ungoogled and Iridium, so it should be looked into.
