### ISSUE TITLE
Chrome Extension Delay 0.03 ( ͡° ͜ʖ ͡°)

### ISSUE THREAD

**Issue by RandomGOTI** [mrdokenny/Cookie-AutoDelete#77]
59.0.3071.115 (Official Build) (64-bit) and 1.4.0 CAD
It seems to be working just fine , even with instant clean on tab close ¯\_(ツ)_/¯
Tested on single and multiple tabs
Whatever the reason it's awesome for users confortable with lower values

**Comment by mrdokenny** [comment]
Is that the unpacked version or the one on the Chrome Webstore because I still get this:

`_generated_background_page.html:1 Alarm delay is less than minimum of 1 minutes. In released .crx, alarm "activeModeAlarm" will fire in approximately 1 minutes.`

which means that the minimum is still 1 minute in the packed (Chrome Webstore) version.

**Comment by RandomGOTI** [comment]
I had CAD on chrome for a longer time and i only installed from the webstore
For me it just acts as the firefox one , runs at tab close with the specified delay

**Comment by mrdokenny** [comment]
Not sure what's going but it is what it is. :)

**Comment by RandomGOTI** [comment]
[CAD.mp4.zip](https://github.com/mrdokenny/Cookie-AutoDelete/files/1116811/CAD.mp4.zip)
Added a ~2MB recording of a guy streaming on twitch and me opening github for a couple of times for the cookies notifications , frist time i logged into the account the other times just opened and closed the tab Used CAD's github shortcut from rightclick menu
Not sure why it's working on my chrome ... but oh well xD
