### ISSUE TITLE
[SUPPORT]  Question about end-result power usage

### ISSUE THREAD

**Issue by ghost** [mrdokenny/Cookie-AutoDelete#778]
Sorry if this is not the appropriate place to ask/discuss this, but the email address listed on the Chrome store (cad-developers@googlegroups.com) bounced back.

Hello, first thanks so much for the extension!

I have a very theoretical question about using the app on a battery powered laptop: if one is concerned about performance and using less battery, is it better to keep cookies/not use the extension, or use it? 

Because I am thinking, is it not using more power to delete x amount of cookies with each tab you close if you surf the web a lot?

Then, don't websites have to recreate cookies that were previously deleted? So with every page visited and left, there is much more writing and deleting occuring on the hard drive. So more reading/writing/deleting=more power usage/less battery life?

I'm not saying this is actually the case, I am just very curious if you think this is true? Just hypothetical and out of curiosity/interest

**Comment by kennethtran93** [comment]
> Sorry if this is not the appropriate place to ask/discuss this, but the email address listed on the Chrome store ([cad-developers@googlegroups.com](mailto:cad-developers@googlegroups.com)) bounced back.

Whoops we'll adjust the setting there, but for the most part issues/requests/support should be done here, mainly so that others can look it up.


> I have a very theoretical question about using the app on a battery powered laptop: if one is concerned about performance and using less battery, is it better to keep cookies/not use the extension, or use it?
> 
> Because I am thinking, is it not using more power to delete x amount of cookies with each tab you close if you surf the web a lot?
> 
> Then, don't websites have to recreate cookies that were previously deleted? So with every page visited and left, there is much more writing and deleting occuring on the hard drive. So more reading/writing/deleting=more power usage/less battery life?
> 
> I'm not saying this is actually the case, I am just very curious if you think this is true? Just hypothetical and out of curiosity/interest

There's no definite response for this - it is ultimately up to each individual.  Lean towards increasing Performance/battery or increase privacy.  

Technologically speaking, speculatively, writing to disk doesn't take up that much time (well there's HDD vs SSD but I won't get into that).  The browser will always read and write cookies from each site you visit as the websites send cookies to your browser, even if it doesn't need to be updated.  In addition, depending on the browser, it will also trigger its own cookie cleanup if the cookies have expired.

Not to mention browsers generally store parts of the website in the cache (more reading/writing/deleting from disk)...

Note sure if this is the response you were looking for.
