### ISSUE TITLE
[BUG] Not working with Container Addons like Simple Tab Groups

### ISSUE THREAD

**Issue by tsonntig** [mrdokenny/Cookie-AutoDelete#783]
Open an link i get:

"
Can't open the URL into Freizeit container

Simple Tab Groups addon can't open URL:
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentation#delay-before-automatic-cleaning

Group Freizeit was assigned to open tabs in Freizeit container.

Another addon, which has UUID:
3c7a58a2-8574-4ee9-bd29-5a1fffa81d2c

tries to open this URL in No container container. Move the tab to another group or forbid the addon 3c7a58a2-8574-4ee9-bd29-5a1fffa81d2c to perform this action.

You can find out the addon by UUID on the page:
about:debugging#/runtime/this-firefox"

if i choose to open it in the wanted container it seems to be working without any erros.

**Comment by kennethtran93** [comment]
That is not a CAD bug as we only have online documentation - the only `browser.tabs.create` webextension API that we call is the one to open the CAD settings pages.  All the documentation links are regular links that opens in a new tab because we put `target="_blank"` as part of the `<a>` link tag (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#target).  There's a reason why we have documentation open in a new tab so as to not replace the Setting Pages.  Here's our template code for what you're clicking on:
```html
    <a href={link} target="_blank" rel="noreferrer" className="tooltipCustom">
      <FontAwesomeIcon size={'lg'} icon={['far', 'question-circle']} />
    </a>
```

Upon a quick look at the webextension page of your addon, it also says the following:
![Screenshot_20200624_075351](https://user-images.githubusercontent.com/6724477/85580826-ebbc8300-b5f0-11ea-9b25-dd567ecf9277.png)

to which references the tab opening part, though we don't control it

**Comment by kennethtran93** [comment]
The only thing we can try and do is to open the settings page that is triggered through the popup to open in the same container that the current tab is in.
