### ISSUE TITLE
[BUG] No cleanup since 2020-06-11

### ISSUE THREAD

**Issue by RubenKelevra** [mrdokenny/Cookie-AutoDelete#791]
**Describe the bug**

The last entry in my cleaning log is from the 11th of June. I just have a couple of websites which I don't clean, so there should be plenty of entries since this date.

**Expected behavior**

Cleanups on closed tabs.

**Your System Info (please complete the following information):**

 - OS: Linux
 - Browser Info: Brave | 1.10.97 Chromium: 83.0.4103.116 (Official Build) unknown (64-bit)
 - CookieAutoDelete Version 3.4.0

**Comment by kennethtran93** [comment]
Weird, considering our 3.4.0 was released on Chrome WebStore around June 19th, and the previous one was near end of May.

- What's your settings like?  
- Are you using Incognito mode (temporary/permanent) for those tabs/sites?
- What happens when you click `clean` in the popup?

It is working on Google Chrome (83.0.4103.116) and Firefox, so there's not much other basic support I can give.  

Screenshot was taken from Chrome.
![BUG  No cleanup since 2020-06-11 · Issue #791 · Cookie-AutoDeleteCookie-AutoDelete](https://user-images.githubusercontent.com/6724477/86156351-a8638800-baba-11ea-890c-106cd1cc95b3.png)

**Comment by RubenKelevra** [comment]
> Weird, considering our 3.4.0 was released on Chrome WebStore around June 19th, and the previous one was near end of May.
> 
> * What's your settings like?

![Screenshot_20200701_005717](https://user-images.githubusercontent.com/614929/86185107-d89c3c80-bb35-11ea-9403-139c951eeaed.png)

> * Are you using Incognito mode (temporary/permanent) for those tabs/sites?

I never use the incognito mode.

> * What happens when you click `clean` in the popup?

Nothing, except that it turns green and then yellow again.

**Comment by RubenKelevra** [comment]
Damn, I figured it out. The plugin was set to `can read and change site data` and then `when you click on it`.

Sorry!

**Comment by kennethtran93** [comment]
Awesome.  Glad it got resolved.

**Comment by RubenKelevra** [comment]
> Awesome. Glad it got resolved.

Maybe there's a way to check for this "rights" and show a warning that the plugin won't be able to work if the user selects the wrong one :D

**Comment by kennethtran93** [comment]
> Maybe there's a way to check for this "rights" and show a warning that the plugin won't be able to work if the user selects the wrong one :D

Not that I can see of unfortunately.  If you want to check, then check out the WebExtension APIs for [Google Chrome](https://developer.chrome.com/extensions/api_index)
