### ISSUE TITLE
[BUG] No popup on manual clean of "Clean, include open tabs"

### ISSUE THREAD

**Issue by redactedscribe** [mrdokenny/Cookie-AutoDelete#842]
**Describe the bug**
With the option "Show Notification from Manual Site Data Cleanups" *enabled* (and the above option for Automatic cleanup *disabled*), pressing "Clean, include open tabs" does not show a popup (though a log entry appears). However, pressing any of the other clean functions (beneath the warning text) does produce a popup.

**To Reproduce**

1. Click the browser button for CAD.
2. Open the dropdown menu for Clean.
3. "Clean, include open tabs": No popup.

**Expected behavior**

A popup should show, just like when manually cleaning other Clean options.

**Your System Info (please complete the following information):**

 - Browser Info: Firefox 79.0
 - CookieAutoDelete Version 3.5.0

**Comment by kennethtran93** [comment]
May want to read the documentation on this: https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentation#show-notification-from-manual-site-data-cleanups

Long story short:
`Clean` and `Clean, include open tabs` are treated as automatic cleanup items as they go through the configured lists.

Only the rest of the options below that is considered manual clean as it bypasses all the configured lists.
Seems like I may need to reword a few things.

This is because both the above buttons call exactly the same function as the automatic cleanup.  We have yet to differentiate those ones at this time.

Maybe I just need a different term to differentiate those that ignore the configured lists...

**Comment by redactedscribe** [comment]
Good to know it's expected, though from a user's perspective, it feels somewhat unexpected.

It seems the problem was that clicking the (?) for the manual notification option leads to the [wiki home](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki) (so I assumed it wasn't written).

A closer look reveals that the (?) link is broken: `https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentationshow-notification-from-manual-site-data-cleanups` (no `#` between `Documentation` and `show`).

**Comment by kennethtran93** [comment]
> It seems the problem was that clicking the (?) for the manual notification option leads to the [wiki home](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki) (so I assumed it wasn't written).
> 
> A closer look reveals that the (?) link is broken: `https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentationshow-notification-from-manual-site-data-cleanups` (no `#` between `Documentation` and `show`).

Whoops forgot to include the # in the code portion you're right.  That link is here: https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentation#show-notification-from-manual-site-data-cleanups

Will be fixed as part of #841.
