### ISSUE TITLE
[SUPPORT] Effects of not whitelisting the CAD temporary cookie "CookieAutoDeleteBrowsingDataCleanup"?

### ISSUE THREAD

**Issue by redactedscribe** [mrdokenny/Cookie-AutoDelete#857]
**Please describe what you need support with.**
When choosing select cookies to not be cleaned for a whitelisted site, what is the effect of not also checking "CookieAutoDeleteBrowsingDataCleanup"?

**Additional context**
It's not clear to me whether I should be checking this cookie (along with others I wish to keep), or not. Greylisting must be re-writing this cookie when needed: why can we whitelist it? What benefit is there to whitelisting it?

I've read [the wiki entry](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentation#other-browsing-data-cleanup-options), from my understanding, this cookie is only present when a site has no cookie set, but later, a site cookie may be set, revealing it and the temporary cookie in the list of cookies CAD displays. Perhaps it's a "bug" that the temp cookie is displayed as I assume it's purpose is void since the site now has a cookie set? Please excuse any misunderstandings.

Thanks!

**Comment by kennethtran93** [comment]
I should probably remove it from the list of cookies shown to white/greylist as it will be 'removed' on each automatic clean run (and be regenerated afterwards on each page/tab load).

Prior to 3.5.1, the cookie would be set if no cookies were created after a given amount of time (in seconds).  Cleaning other browsing data types require at least one cookie to be removed from that site, so if extra cookies are there then our internal cookie may be kept/removed if at least one cookie was going to be removed.

However, this has been changed in 3.5.1 onwards to always create an internal cookie that triggers other browsing data type cleanups due to the fact that some cookies aren't set to the specific subdomain (rather the base domain), so in those cases the data from subdomains aren't properly removed.
