### ISSUE TITLE
Invoke cleanup of LocalStorage

### ISSUE THREAD

**Issue by Boing777** [mrdokenny/Cookie-AutoDelete#869]
I have looked through FAQ and Issues and cannot find information regarding...

Brave browser on Windows

Whenever I close any tab or change domain in a tab I am seeing notification:
Invoked cleanup of LocalStorage for: www.example.com

The expression for www.example.com is whitelisted and has KeepLocalStorage disabled

Why do the notification always appear, regardless of what tab is closed or domain is used?

**Comment by kennethtran93** [comment]
Seeing as this is your first issue, I'll respond to this incomplete issue.  Next time, please select 'support' issue instead as what you're asking falls into the 'support' section.  In addition the template headers must be kept.

> Brave browser on Windows

We do not officially support Brave Browser - just Google Chrome and Microsoft Edge Chromium on the Chromium side.  Very limited support will be given.

Do you have a tab open or recently closed with 'www.example.com'?   We only create an internal cookie you have recently visited that page after an automatic cleaning.  Each automatic clean will clean our internal cookie, which triggers that domain to clean the other browsing data.  This is because only cookies can be enumerated.  All other browsing data types (cache, indexedDB, localStorage, PluginData, ServiceWorker) must already know the domain to remove beforehand.

**Comment by Boing777** [comment]
Not sure if this reply will even get through, as I see the thread is marked 'closed'.  I am not a programmer and do not have the familiarity in using the github system; thus, my error in procedure.

The issue arose after some months.  Regardless of what tab is opened and closed for any domain, the notification appears.  There are no tabs that have www.example.com during this time.  I had to enable KeepLocalStorage for www.examlpe.com, so that notifications do not frequently appear.

If Brave is not supported, I understand.

Thanks for the initial assistance anyway.

Boing777

**Comment by kennethtran93** [comment]
There may have been another internal cookie that did not get erased or something.  See if you can go into viewing the site data in Brave (in Chrome it was somewhere in settings and site data), then remove the entries for example.com.

**Comment by 1u** [comment]
same problem here:
Cookie AutoDelete 3.5.1   -  Chromium 84.0.4147.105  Ubuntu  (64-bit)

I never visit hp.com and it shows this alert each time i open a new page or close a tab.

![image](https://user-images.githubusercontent.com/4281072/93247630-e5244e80-f78e-11ea-8e2d-5606ceed55f6.png)
![image](https://user-images.githubusercontent.com/4281072/93247664-f2413d80-f78e-11ea-97ed-ed5a7bc5f348.png)
![image](https://user-images.githubusercontent.com/4281072/93247817-303e6180-f78f-11ea-80c4-c8a1f8e4ec08.png)
![image](https://user-images.githubusercontent.com/4281072/93247864-40eed780-f78f-11ea-8e72-d1b2c1a3433c.png)

**Comment by kennethtran93** [comment]
That may have been a third-party cookie or something. Try the proposed steps above.

Maybe that cookie was set because you had installed a hp printer? Could have resulted in a request to load hp product registration.

**Comment by 1u** [comment]
In my case, might be useful for someone else:  
Updating and restarting browser didn't help. Disabling all other addons didn't help neither. After disabling and re-enabling CAD, it didn't show any notifications any more although still enabled. reinstalling CAD fixed the problem. (incl. ex- and importing whitelist)
