### ISSUE TITLE
[SUPPORT] Greylist not working

### ISSUE THREAD

**Issue by ThomasSeeker** [mrdokenny/Cookie-AutoDelete#885]
If I go manually to the toolbar icon and click "Clean all for this domain" ... I get the refreshed content after restart of Firefox 80.0.

If I greylist the domain, the old content gets displayed after restart.

**Comment by kennethtran93** [comment]
A) Please follow the relevant issue template next time. https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/new/choose

- Missing CAD Version

B)  I'm going to need more information than what is initially given. 

- Domains in question, the CAD Expression you used, and CAD settings.

 
> If I greylist the domain, the old content gets displayed after restart.

C) Was the tab already open at restart?
D) Is greylist cleanup enabled in CAD Settings?

**Comment by ThomasSeeker** [comment]
Thank you for your answer!
I'm sorry for not taking the right route here! 
(I'm new here.)

A. CAD Version: 3.5.1

B. Domains in question: all I tried. E.g. youtube.

CAD Expression you used: "*.youtube.com" and "youtube.com"

CAD settings: I tried it with all the boxes checked for both and also    with all the boxes unchecked. Closed FF and restarted it again.

C. Was the tab already open at restart? I use session restore. So the tabs are open, and I tried both: activated and not activated.

D. Is greylist cleanup enabled in CAD Settings? Yes.

**Comment by kennethtran93** [comment]
As mentioned in the FAQ/Documentation, because we need to initialize the extension on every browser startup, sometimes the page finishes loading before CAD has a chance to do anything to its data.

**Comment by ThomasSeeker** [comment]
"sometimes the page finishes loading before CAD ..."

In my case it didn't work a single time in 20 tries.

I also unchecked all the "keep till restart"-boxes ... no success either.

Must be a different issue it seems, doesn't it?

**Comment by kennethtran93** [comment]
What is your other CAD settings at, notably at the 'other Browsing Data' section?

> CAD settings: I tried it with all the boxes checked for both and also with all the boxes unchecked. Closed FF and restarted it again.

When I say CAD Settings, I mean the actual settings of CAD (globally) and not per Expression - those we call Expression options.

> I also unchecked all the "keep till restart"-boxes ... no success either.

If you uncheck them in greylist, then they should be removed on the next cleanup / tab close.

> C. Was the tab already open at restart? I use session restore. So the tabs are open, and I tried both: activated and not activated.

Please clarify what you mean by activated and not activated in this instance.

Is this option enabled as well:  `Clean Cookies from Open Tabs on Startup`

**Comment by ThomasSeeker** [comment]
At the 'other Browsing Data' section all boxes are unchecked.

Basically it is only "Enable Greylist Cleanup on Browser Restart" checked (and a few notification-options at the bottom.

"Please clarify what you mean by activated and not activated in this instance." ... On FF-startup my old session gets restored. All the tabs are there. But the pages behind them are not loaded yet. Only the one tab, which is active/open has of course a loaded page. The others I called "not acitivated". CAD doesn't work on either of them.

"Is this option enabled as well: Clean Cookies from Open Tabs on Startup" ... No, because I only want to delete the cookies from specific tabs, not from all.

**Comment by kennethtran93** [comment]
> At the 'other Browsing Data' section all boxes are unchecked.
> Basically it is only "Enable Greylist Cleanup on Browser Restart" checked (and a few notification-options at the bottom.

That would be one of the main issue you were facing. This is a global setting which affects all expression options. Keep in mind that enabling any of this will clear all related data of that type. Once that is enabled then the expression options are checked afterwards for cleaning. 

YouTube and other sites store data not only in cookies but LocalStorage and indexedDB as well. 

'Clean {X} for this site' bypasses any expression configurations, including CAD settings, for cleaning and just cleans it up. 


> "Please clarify what you mean by activated and not activated in this instance." ... On FF-startup my old session gets restored. All the tabs are there. But the pages behind them are not loaded yet. Only the one tab, which is active/open has of course a loaded page. The others I called "not acitivated". CAD doesn't work on either of them.


In our extension, any tabs that are there are considered 'open'. We do not distinguish between activated or not (unless there is another extension that changes the domain name temporarily if unloaded to which point that domain may be cleaned up as it may be treated as not opened) 

> "Is this option enabled as well: Clean Cookies from Open Tabs on Startup" ... No, because I only want to delete the cookies from specific tabs, not from all.


This is the other issue - this needs to be enabled, otherwise those tabs won't be touched even if there is an expression configuration for it. For other sites that should not have its data cleaned up, set a whitelist for it.

**Comment by ThomasSeeker** [comment]
Just to be perfectly clear: In the case, that I just want 1 Tab to be cleared, i.e. youtube ... and all other Tabs not be cleared ... I need to enable "Other Browsing Data Cleanup Options"?

Ok, and if I understand right,  "Clean Cookies from Open Tabs on Startup" needs to be checked too and all exceptions need to be white-listed. ... 

Is there a way to white-list all which is not grey-listed?

**Comment by kennethtran93** [comment]
> Just to be perfectly clear: In the case, that I just want 1 Tab to be cleared, i.e. youtube ... and all other Tabs not be cleared ... I need to enable "Other Browsing Data Cleanup Options"?

It does not matter if it is just one site. If sites are storing 'other browsing data' other than cookies then yes. (This extension originally started off with cookie cleaning, thus why 'other' was used).

The reason why the warning is there is because ideally we would like to start off in a 'clean' slate as those 'other browsing data' cannot be enumerated for cleaning - thus we rely on cookies for the domain name. 


> Ok, and if I understand right,  "Clean Cookies from Open Tabs on Startup" needs to be checked too and all exceptions need to be white-listed. ... 

Correct. 


> Is there a way to white-list all which is not grey-listed?

Nope. Whitelist takes precedence over greylist. We do not have a blacklist yet for specific cleanup that should always happen.

**Comment by ThomasSeeker** [comment]
So this basically means, that with CAD I can not just clear 1 tab on startup, ... if the others constantly change from day to day. Right?

**Comment by kennethtran93** [comment]
> So this basically means, that with CAD I can not just clear 1 tab on startup, ... if the others constantly change from day to day. Right?

Depends. 

Your best bet is to use a separate container for constantly changing tabs, putting `*` on whitelist for that container.

Another container can then simply have YouTube and its greylist expression.

However, due to Firefox internal api limitations, when one domain's 'other browsing data' is cleared, it is cleaned for all containers. I.e. If YouTube's data is cleared, and if you somehow have YouTube in the constantly changing container, then those YouTube data will also be erased (except cookies) despite being included in the all-inclusive whitelist.

**Comment by ThomasSeeker** [comment]
Thank you for your help @kennethtran93!

With your instructions I managed to whitelist all changing tabs. As well es putting all greylisted tabs into a separate container.

Hovering over the CAD-toolbar-icon shows correctly "white" or "grey".

But for some reason my FF still keeps showing old versions of the grey-listed pages. 

In the settings I have all "Other Browsing Data Cleanup Options" checked. I have "Clean Cookies from Open Tabs on Startup" checked as well as "Clear greylist on startup".

Strangely, now even manually "clearing all for this domain" does prevent FF from showing the old page on the next startup. I think this did work in the past already, but I'm not sure. 

What am I missing here?

**Comment by kennethtran93** [comment]
When you first enabled the 'other browsing data' options, they each gets wiped completely, so that we start off in a 'clean' slate.

Unfortunately like I had mentioned before, the site may still load (especially on the active tab(s) on restart) before this extension has a chance to complete its startup prodecures and cleaning.

**Comment by ThomasSeeker** [comment]
" the site may still load (especially on the active tab(s) on restart) before this extension has a chance to complete its startup prodecures and cleaning."

But shouldn't then at least the tabs, which are open on startup, but without their pages being loaded yet ... shouldn't CAD at least work on these?

And also, if all the boxes ("keep cache till restart", ...) are unchecked ... shouldn't CAD then have enough time to clean up before(!) the restart?

**Comment by kennethtran93** [comment]
> But shouldn't then at least the tabs, which are open on startup, but without their pages being loaded yet ... shouldn't CAD at least work on these?

I am unsure how Firefox loads the tabs. In any case it should be cleaned up if it is not loaded, unless the website somehow added itself to the 'protectedWeb' section, to which the api has not been added for cleanup yet (I.e. Webapps like the angry birds game on their website was the example given). As we cannot enumerate it all we can do is blindly clean it. That being said if you enable debug mode and check the console logs through the instructions given, then you can see if it has been triggered as we list the sites being sent to the specific data type for cleanup. To check you'll need to enable the option, then restart the browser. 

I was going to ask if you were on mobile but you couldn't be as you were using ff80. 

> And also, if all the boxes ("keep cache till restart", ...) are unchecked ... shouldn't CAD then have enough time to clean up before(!) the restart?

If unchecked, then it will be handled by the automatic cleanup, which only triggers through tab close (and domain change if enabled) which will only happen after the delay (in seconds) set by you.  This will never run if browser was shutdown during the delay. We cannot do anything on browser shutdown/before restart. Hence why the greylist is executed on browser startup.

**Comment by ThomasSeeker** [comment]
I copied the debug log and filtered for a specific gleylisted site. Can you see anything in it?

*EDIT:  Removed historic log entries as invalid filter applied.*

**Comment by kennethtran93** [comment]
Nope sorry. You'll need to send me the entire log file as snippets of filtered log will not give me the whole story of what, why or how each entry came to be. Not all log lines have the domain in it, and not all domains will have `https` in it nor the specific page you were at as we don't care abour that. 

With what you have given me, I'm not sure if you actually restarted the browser after enabling the debug mode. All this tells me is that the you navigated to that domain, and that our extension updated the cookie count almost every time the tab was updated (we also force update when cookies for that domain/tab was changed as well). 

Easier if you just filter by `CAD_` to get all our extension debug, then copy-paste it all to a text file and upload it here.

**Comment by ThomasSeeker** [comment]
Ok, here is the file. What is strange: I find no entry of the 7 pinned tabs and the normal one where youtube is open in.
[CAD.txt](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/files/5212402/CAD.txt)

**Comment by kennethtran93** [comment]
The greylist works on my personal FireFox profile 80.0.1 (linux).

Can you give me your FULL CAD Settings - You can export that through Settings and upload it here.  That file will not include any lists or expressions if that's what you're worried about.

Also on the logs, ensure that all types of console output is enabled - Error, Logs, Debug, Warning, Info and that the filter is only `CAD_`

There should be a LOT more lines than that.  Especially the background cleanup info which I don't see here (may be hidden)?  See if `background.greyCleanup:  dispatching browser restart greyCleanup` is in there after a restart.  I know I need to work on a better debug output.

startup cleanup does not work instantly - it needs to parse through everything, so leave it running for about 10 seconds before copy-paste the output.

Did you enable cleanup log and counter?  That will also assist you in seeing what CAD has cleaned (in the cleanup details you can see if any cookies were cleaned because of startup).

**Comment by ThomasSeeker** [comment]
Here are the Settings and a new log.

"Error, Logs, Debug, Warning, Info and that the filter is only CAD_" ... done!

"so leave it running for about 10 seconds before copy-paste the output." ... done!

I noticed, that the log grows with new entries, when unloaded tabs get clicked and thus loaded. Maybe this is interesting?

`background.greyCleanup: dispatching browser restart greyCleanup` is not in there!

"Did you enable cleanup log and counter?" ... yes!

In the cleanup-protocols it says: "No protocols were found"

[CAD.txt](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/files/5213698/CAD.txt)

[CAD_CoreSettings_2020-09-13_08.00.51.txt](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/files/5213700/CAD_CoreSettings_2020-09-13_08.00.51.txt)

**Comment by kennethtran93** [comment]
I found your main problem - you had `Enable Automatic Cleanup` disabled.  That's why no cleanups were done.  This has to be enabled otherwise this extension does nothing other than updating the cookie count.  Note that with this disabled the icon is grey.  When enabled, you will see either blue, red, or yellow icon.

My apologies for not asking this question earlier.  This may have saved a few comments.

This can be enabled either in the CAD Settings (First Checkbox), or through the popup - if popup, ensure that the button is green and it says 'Auto-clean Enabled'.

Once that is enabled, restart the browser and see what happens then.


> I noticed, that the log grows with new entries, when unloaded tabs get clicked and thus loaded. Maybe this is interesting?

That is supposed to happen as we listen to the tab update events.  These events include domain changes, tab unloaded/loaded/discarded, etc.

> In the cleanup-protocols it says: "No protocols were found"

That would happen when you did not enable automatic clean so this extension has yet to clean anything.

The `Clean X for this site` are what we call 'manual clean' thus no log entries will be generated for those as those are what you cleaned on your own.  The log entries will only show what CAD cleaned through automatic cleaning.

**Comment by ThomasSeeker** [comment]
Ok, now the icons have colour. ... And on startup popups appear telling me, that 5 cookies have been cleared from the grey-listed sites. 

But the content of the pages is still the old one.

And even if I do a 'manual clean' ... "clean all from this site" ... after restart the content is still old.

**Comment by kennethtran93** [comment]
> Ok, now the icons have colour. ... And on startup popups appear telling me, that 5 cookies have been cleared from the grey-listed sites.

Then greylist is working.

> But the content of the pages is still the old one.
> 
> And even if I do a 'manual clean' ... "clean all from this site" ... after restart the content is still old.

to clarify, Is this still youtube we're talking about here?

If the manual clean still does the same thing, then I suspect that the site in question has registered as a webapp / hosted app, which then falls under `protectedWeb` category that the API has yet to be implemented for cleaning.  Chrome does have it but CAD hasn't implemented cleanup for `protectedWeb` portions yet.  (See https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/851#issuecomment-678598935) for an explanation for 'protectedWeb'.

**Comment by ThomasSeeker** [comment]
"to clarify, Is this still youtube we're talking about here?" ... many sites, and youtube too, yes! ... even a manual cleanup with CAD shows the old content after restart!

In contrast: a simple click on the refresh-button immediately shows the fresh page.

**Comment by kennethtran93** [comment]
> "to clarify, Is this still youtube we're talking about here?" ... many sites, and youtube too, yes! ... even a manual cleanup with CAD shows the old content after restart!
> 
> In contrast: a simple click on the refresh-button immediately shows the fresh page.

You have to refresh manually after CAD performed its cleanup. 

On restart the page may be loaded before CAD has a chance to clear those sites. 

This may be the same for those tabs not loaded yet, but they *should* be cleared as long as Firefox hasn't secretly loaded the data in the background.

**Comment by ThomasSeeker** [comment]
"You have to refresh manually after CAD performed its cleanup."

Refreshing manually always shows the fresh content ... whether or not a manual CAD-cleanup was performed before.

And a manual CAD-cleanup says it cleaned cookies, but after restart the old page is loaded still.

**Comment by kennethtran93** [comment]
I think this is now not just a specific issue with CAD but with how the browser internals work. All we can do, with using the browser Webextension API, is execute `browser.browsingdata.remove` and pass in the site data type to clean (cache, indexedDB, localstorage, plugin Data, Service Workers) as well as the domain name. We don't get a status back as to whether or not it actually was cleaned or not. Hence why the cleanup log and notifications say **'Invoked site Data cleanup for'**.

You've already proven that CAD has performed its greylist functions correctly, and that this support issue should be considered closed now.

I do understand, however, that the tab should be forced to reload after CAD has performed greylist cleanup on affected domains. That may already be an open request for it.

**Comment by ThomasSeeker** [comment]
Ok, I hope, I could clarify the problem. 
And I leave the rest to you guys!

Thank you!
