### ISSUE TITLE
[BUG]  INVALID CONTAINER appears 38 times under list of expressions for all containers

### ISSUE THREAD

**Issue by crispi1971** [mrdokenny/Cookie-AutoDelete#891]
**Describe the bug**

See screenshot. Just opening the CAD preferences shows that the list of expressions has lots of weird output

**To Reproduce**

Under List of Expressions, "INVALID CONTAINER" appears 38 times (in red)

** Steps to reproduce the behavior ** :

1. Open CAD Settings
2. Go to "List of Expressions"
3. See error

**Expected Behavior**

Have not seen this behaviour before. The same output appears under each container

**Screenshots**

See screenshot:

![image](https://user-images.githubusercontent.com/53639985/92449537-91998a00-f1fd-11ea-9c9c-a8ad6268d571.png)

**Your System Info**

- MacOS 10.15.6
- Firefox 80.0.1 (64-bit)
- CookieAutoDelete Version: 3.5.1

**Comment by crispi1971** [comment]
@kennethtran93  - why was this closed? What's missing?

**Comment by kennethtran93** [comment]
It was closed most likely because the keywords 'browser' and 'os' was missing. Also in the expected behaviour the default text was kept as is.

If you click on each 'invalid container' you'll notice that each one has a different container ID (shown above the tabs) 

Mostly likely you are using some form of temporary containers, or you are creating and removing containers yourselves. CAD does not work well with temporary containers mainly due to the fact that each container must be configured separately. 

Until the next update or so, any containers created (either through another webextension or yourself) will still show up (and needs to be manually removed).

A future update will automatically remove freshly removed containers. Existing invalid containers will need to be removed manually.

**Comment by crispi1971** [comment]
Hi there.

I fixed the symptoms of the problem. I had to export the expressions, edit
the json file, and take out empty containers with no content
(eg "   "firefox-container-8380": [],"), delete all expressions, and then
reimport the edited file.

(Yes, I do use temporary containers, and also firefox synching). I just
haven't seen this issue before.

Thank for getting back to me
-Chris

**Comment by kennethtran93** [comment]
Those container will be regenerated again as long as temporary containers are used AND you had configure something for it, either through the popup or List of Expressions.

This expression list were always there beforehand (and could be seen on export). The recent updates only exposes it on the List of Expressions.
