### ISSUE TITLE
[SUPPORT]  Cache and localstorage do not get deleted, despite settings

### ISSUE THREAD

**Issue by ghost** [mrdokenny/Cookie-AutoDelete#920]
**Describe the bug** 

Some data does not get deleted, despite the fact that I want them to get deleted. Undesirable data does **not** include cookies, it is only cache and local storage. That type of data is stored for non-whitelisted websites.

**To Reproduce** 

1. Have all "Other Browsing Data Cleanup Options" enabled, few sites in whitelist.
2. Browse as usual for a long time.
3. Go to brave://settings/siteData (or chrome, that probably will work but I haven't checked)
4. Clean data using this extension again to make sure

**Expected Behavior** 

I should see data only for whitelisted sites.

**Screenshots** 

Screenshots will not be provided because it should contain websites.

**Your System Info** 
- OS: macOS 11.0 beta
- Browser Info: Brave Version 1.14.84 Chromium: 85.0.4183.121 (Official Build) (64-bit)
- CookieAutoDelete Version: 3.5.1

**Additional context** 

Not included

**Comment by ghost** [comment]
@kennethtran93 I think I included all necessary sections.

**Comment by kennethtran93** [comment]
A few things:
- I did fix the issue with the autocloser. It was due to the spelling of behavior vs behaviour.
- because you are using Brave I can only provide basic support as that is not part of our officially supported browser.  This 'bug' is now a support issue instead. 
-As with the browsing Data, sites may fall under the 'protectedWeb' section which we have an open Issue for. Should read up on that. 
- check the debug logs. If the site in question is noted in the 'Invoke cleanup of [browsing data type] for [domain(s)]' then we have passed that domain (and its supposed default variations) to the browser for cleanup. It is up to the browser to do so as we have no way to checking its result as the return of that function doesn't return anything useful. The previous note applies here for the protectedWeb part if so. 
-if it is a third party site storing browsing data without cookies, that is also an existing bug as we rely on cookies to get domains for all browsing data types as that is the only enumerable thing I can parse through.
