### ISSUE TITLE
[SUPPORT]  Cookies not deleting Vivaldi

### ISSUE THREAD

**Issue by rustyjarz** [mrdokenny/Cookie-AutoDelete#950]
**Please describe what you need support with.** 

Hi, yeah I've recently noticed I'm not getting notifications for CAD cookie deletes, and on further investigation it appears CAD isn't deleting my cookies. 

**Describe the solution you'd like** 

Hopefully a fix to the issue described above. 

**Additional context** 

I'm on Vivaldi 3.4.2066.90 (Stable channel) (64-bit). I do have other extensions installed so I'm not sure if this could be extensions stepping over each other. 
Decentraleyes
DuckDuckGo Privacy Essentials
Pop up blocker for Chrome™ - Poper Blocker
KeePass Tusk - Password Access and Autofill
uBlock Origin
uBlock Origin Extra
Video Adblocker for Youtube™ Extension

( I have others but they are disabled )

I have tried resetting the CAD settings, manually clearing out cookies, adjusting the notification timer to no avail 
![image](https://user-images.githubusercontent.com/28703300/97818149-eedd2380-1cf4-11eb-9733-d37faf455923.png)
![image](https://user-images.githubusercontent.com/28703300/97818160-fe5c6c80-1cf4-11eb-9129-3b7f70719b9b.png)

**Comment by rustyjarz** [comment]
@kennethtran93 What's wrong with my support request, as far as I can see it meets all the requirements.

**Comment by kennethtran93** [comment]
You've left the text that you should have replaced in there.

**Comment by rustyjarz** [comment]
> You've left the text that you should have replaced in there.

Text, what text and where?

**Comment by kennethtran93** [comment]
If you would like to troubleshoot them yourself then feel free to enable debug mode and follow its instructions then.

In the browser extension area, is CAD allowed to work on all sites? I recall an option in Chrome what adjusts the limit there as well. It must be kept to all sites or whatever is the most open/allowed.

Lastly, if whatever steps you follow in that browser works in Google Chrome, then that's where I draw the line at this time.

**Comment by rustyjarz** [comment]
Enabled Debug, and yes it's allowed on all sites.

DevTools failed to load SourceMap: Could not load content for chrome-extension://fhcgjolkccmbidfldomjliifgaodjagh/global_files/browser-polyfill.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

![image](https://user-images.githubusercontent.com/28703300/97830822-637a8700-1d22-11eb-8198-5913157a2b37.png)

**Comment by kennethtran93** [comment]
You can ignore source maps. They shouldn't affect the extension at all.

**Comment by rustyjarz** [comment]
> You can ignore source maps. They shouldn't affect the extension at all.

I tried uninstalling and re-installing but same behaviour, still not deleting cookies.

**Comment by kennethtran93** [comment]
When you enable debug mode there is usually a lot more details that I have it output. If you're not seeing it then you're on the wrong console output area.

It may fall either under debug, log, or info depending on what it is outputting. If you can follow along that you may be able to see what we're processing / doing.

**Comment by kennethtran93** [comment]
Is it a specific cookie/site that's not being removed? I recall that some sites may be set using 'protectedWeb' status (google that for more information - I believe the example given was 'angry birds progress' if played on a site.). If your sites fall into that (unsure exactly how to go about checking that) then we have yet to implement cleanup for those contents yet.

**Comment by rustyjarz** [comment]
No it's all sites that cookies aren't being removed. Attached verbose logging output. 
[CAD_Logging.txt](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/files/5473150/CAD_Logging.txt)

**Comment by kennethtran93** [comment]
The first half of that log shows that the cookies enumerated/checked through were kept because of opened tabs.  You then proceeded to open a new site and close it.  However, there's insufficient debug log after that to see the second full cleanup in action, so I could not see what our parsed result of `gpspower.net` came to be.

**Comment by rustyjarz** [comment]
> The first half of that log shows that the cookies enumerated/checked through were kept because of opened tabs. You then proceeded to open a new site and close it. However, there's insufficient debug log after that to see the second full cleanup in action, so I could not see what our parsed result of `gpspower.net` came to be.

Yeah that's because I did a copy and paste of the log output because it wasn't obvious where I could export the log file. Can you export the logs? If so I'll do that and get a more detailed picture for you.

**Comment by kennethtran93** [comment]
> Yeah that's because I did a copy and paste of the log output because it wasn't obvious where I could export the log file. Can you export the logs? If so I'll do that and get a more detailed picture for you.

Not at this time.  It's on my list to make a better internal debug.  In the meantime, you'll need to try and wait until the log entries somewhat slow down enough without you doing anything else.

**Comment by rustyjarz** [comment]
Updated log file, hopefully it has the data you need.

[CAD_Logging.txt](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/files/5485188/CAD_Logging.txt)

**Comment by kennethtran93** [comment]
So from what I deciphered as I don't have any timestamps to base it off from:
- 1st clean: automatic from closing of tab with `gpspower.net`
  - (17) `gpspower.net` cookies have been internally marked and should have been sent for removal.
  - No other cookies were marked for removal.
  - All other cookies were kept due to either open tabs or whitelist entry.
  - No errors were caught, so presumed it should have been cleaned.
  - A cleanup log entry should have been generated detailing this site and its (17) cookie names that *should* have been removed.
- (There were some `Uncaught (in Promise) Object` that may have been from the tab closure below but our extension had an incoming change detected and set a small delay that got ran to update the cookie count on the icon after the tab closed).
- 2nd clean: automatic from tab closing from site `bonusbitcoin.co`
  - (5) `bonusbitcoin.co` cookies have been internally marked and should have been sent for removal.
  - No other cookies were marked for removal.
  - All other cookies were kept due to either open tabs or whitelist entry.
  - No errors were caught, so presumed it should have been cleaned.
  - A cleanup log entry should have been generated detailing this site and its (5) cookie names that *should* have been removed.
- A tab opened to duckduckgo which then changed to `gpspower.net`
- 3rd clean: automatic from tab closing from site `gpspower.net`
  - (17) `gpspower.net` cookies have been internally marked and should have been sent for removal.
  - No other cookies were marked for removal.
  - All other cookies were kept due to either open tabs or whitelist entry.
  - No errors were caught, so presumed it should have been cleaned.
  - A cleanup log entry should have been generated detailing this site and its (17) cookie names that *should* have been removed.
- A tab opened to duckduckgo which then changed to `gpspower.net`
- 4th clean: automatic from tab closing from site `gpspower.net`
  - (17) `gpspower.net` cookies have been internally marked and should have been sent for removal.
  - No other cookies were marked for removal.
  - All other cookies were kept due to either open tabs or whitelist entry.
  - No errors were caught, so presumed it should have been cleaned.
  - A cleanup log entry should have been generated detailing this site and its (17) cookie names that *should* have been removed.

What cookies were remaining that you think should have been removed?  a list of domains or screenshot of the siteData page filtered with the lingering data from domain will do.
