### ISSUE TITLE
[FEATURE REQUEST]  Safari Cookie-Autodelete

### ISSUE THREAD

**Issue by kistanovdev** [mrdokenny/Cookie-AutoDelete#964]
Now that the new version of Safari is able to support a broader range of extensions, is it possible to port cookie-autodelete?
This is the only extension that is stopping me from moving to Safari fully!
I love this extension and consider it essential for my daily internet usage.

Best,

Daniil K

**Comment by kennethtran93** [comment]
Long Story Short:  Despite the recent bridging attempt by Apple, it is still unlikely at this time.

Until the [Apple Developer Program](https://developer.apple.com/support/compare-memberships) is either free just to develop and publish Safari Web Extensions, or a small one-time fee, it is highly unlikely.  Do you think it is feasible that an open-source extension should fork out **$99 USD per year** to enroll in their developer program just to publish a *free* extension?  We may be able to only if we can sustain at least that amount in donations per year.  Also an 'Organization' has to be a registered/legal one, otherwise it would go under one person's name (i.e. Kenny Do).  This also means that only he will be able to compile/publish it under his Apple ID.

EDIT:  I briefly read over the [fee wavier portion](https://developer.apple.com/support/membership-fee-waiver/), and it applies to non-profits and whatnot.  Explicitly states not for individuals/sole-partnerships/etc, but unsure about open source (though realistically only the two of us manages it at this point).

According to [this doc](https://developer.apple.com/documentation/safariservices/safari_web_extensions/converting_a_web_extension_for_safari), 'porting' our web extension requires wrapping our code into a safari app for publishing to the app store.  In addition, at least one function (namely the `cookies.onChanged` listener) is not supported, so additional code needs to be injected to check and disable that function (which also means that the cookie count may not be up to date at times).

**Comment by kistanovdev** [comment]
Thank you for the clarification!
